// Code generated by lexgen. DO NOT EDIT.

package bsky

import (
	"context"
	lextypes "github.com/jcalabro/atmos/api/lextypes"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/atmos/xrpc"
	"github.com/jcalabro/gt"
)

// Precomputed JSON key tokens for ActorGetSuggestions_Output.
var (
	jsonKey_ActorGetSuggestions_Output_dollar_type = []byte("\"$type\":")
	jsonKey_ActorGetSuggestions_Output_actors      = []byte("\"actors\":")
	jsonKey_ActorGetSuggestions_Output_cursor      = []byte("\"cursor\":")
	jsonKey_ActorGetSuggestions_Output_recId       = []byte("\"recId\":")
	jsonKey_ActorGetSuggestions_Output_recIdStr    = []byte("\"recIdStr\":")
)

func (s *ActorGetSuggestions_Output) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *ActorGetSuggestions_Output) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_ActorGetSuggestions_Output_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_ActorGetSuggestions_Output_actors...)
	buf = append(buf, '[')
	for i, item := range s.Actors {
		if i > 0 {
			buf = append(buf, ',')
		}
		var err error
		buf, err = item.AppendJSON(buf)
		if err != nil {
			return nil, err
		}
	}
	buf = append(buf, ']')
	first = false
	if s.Cursor.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_ActorGetSuggestions_Output_cursor...)
		buf = cbor.AppendJSONString(buf, s.Cursor.Val())
		first = false
	}
	if s.RecId.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_ActorGetSuggestions_Output_recId...)
		buf = cbor.AppendJSONInt(buf, s.RecId.Val())
		first = false
	}
	if s.RecIdStr.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_ActorGetSuggestions_Output_recIdStr...)
		buf = cbor.AppendJSONString(buf, s.RecIdStr.Val())
		first = false
	}
	for _, ef := range s.extraJSON {
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *ActorGetSuggestions_Output) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *ActorGetSuggestions_Output) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extraJSON = nil
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "actors":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.Actors = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem ActorDefs_ProfileView
					pos, err = elem.UnmarshalJSONAt(data, pos)
					if err != nil {
						return 0, err
					}
					s.Actors = append(s.Actors, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case "cursor":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v string
				v, pos, err = cbor.ReadJSONString(data, pos)
				if err != nil {
					return 0, err
				}
				s.Cursor = gt.Some(v)
			}
		case "recId":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v int64
				v, pos, err = cbor.ReadJSONInt(data, pos)
				if err != nil {
					return 0, err
				}
				s.RecId = gt.Some(v)
			}
		case "recIdStr":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v string
				v, pos, err = cbor.ReadJSONString(data, pos)
				if err != nil {
					return 0, err
				}
				s.RecIdStr = gt.Some(v)
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extraJSON = append(s.extraJSON, lextypes.ExtraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...)})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for ActorGetSuggestions_Output.
var (
	cborKey_ActorGetSuggestions_Output_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_ActorGetSuggestions_Output_recId       = cbor.AppendTextKey(nil, "recId")
	cborKey_ActorGetSuggestions_Output_actors      = cbor.AppendTextKey(nil, "actors")
	cborKey_ActorGetSuggestions_Output_cursor      = cbor.AppendTextKey(nil, "cursor")
	cborKey_ActorGetSuggestions_Output_recIdStr    = cbor.AppendTextKey(nil, "recIdStr")
)

func (s *ActorGetSuggestions_Output) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *ActorGetSuggestions_Output) AppendCBOR(buf []byte) ([]byte, error) {
	n := 1 + len(s.extraCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	if s.RecId.HasVal() {
		n++
	}
	if s.Cursor.HasVal() {
		n++
	}
	if s.RecIdStr.HasVal() {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	ei := 0
	ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "$type", buf)
	if s.LexiconTypeID != "" {
		buf = append(buf, cborKey_ActorGetSuggestions_Output_dollar_type...)
		buf = cbor.AppendText(buf, s.LexiconTypeID)
	}
	ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "recId", buf)
	if s.RecId.HasVal() {
		buf = append(buf, cborKey_ActorGetSuggestions_Output_recId...)
		buf = cbor.AppendInt(buf, s.RecId.Val())
	}
	ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "actors", buf)
	buf = append(buf, cborKey_ActorGetSuggestions_Output_actors...)
	buf = cbor.AppendArrayHeader(buf, uint64(len(s.Actors)))
	for _, item := range s.Actors {
		var err error
		buf, err = item.AppendCBOR(buf)
		if err != nil {
			return nil, err
		}
	}
	ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "cursor", buf)
	if s.Cursor.HasVal() {
		buf = append(buf, cborKey_ActorGetSuggestions_Output_cursor...)
		buf = cbor.AppendText(buf, s.Cursor.Val())
	}
	ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "recIdStr", buf)
	if s.RecIdStr.HasVal() {
		buf = append(buf, cborKey_ActorGetSuggestions_Output_recIdStr...)
		buf = cbor.AppendText(buf, s.RecIdStr.Val())
	}
	_, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "", buf)
	return buf, nil
}

func (s *ActorGetSuggestions_Output) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *ActorGetSuggestions_Output) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extraCBOR = nil
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "recId" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v int64
					v, pos, err = cbor.ReadInt(data, pos)
					if err != nil {
						return 0, err
					}
					s.RecId = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
			}
		case 6:
			if string(data[keyStart:keyEnd]) == "actors" {
				{
					arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
					if err != nil {
						return 0, err
					}
					pos = newPos
					s.Actors = make([]ActorDefs_ProfileView, arrLen)
					for idx := range arrLen {
						pos, err = s.Actors[idx].UnmarshalCBORAt(data, pos)
						if err != nil {
							return 0, err
						}
					}
				}
			} else if string(data[keyStart:keyEnd]) == "cursor" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v string
					v, pos, err = cbor.ReadText(data, pos)
					if err != nil {
						return 0, err
					}
					s.Cursor = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
			}
		case 8:
			if string(data[keyStart:keyEnd]) == "recIdStr" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v string
					v, pos, err = cbor.ReadText(data, pos)
					if err != nil {
						return 0, err
					}
					s.RecIdStr = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
		}
	}
	return pos, nil
}

type ActorGetSuggestions_Output struct {
	LexiconTypeID string                  `json:"$type,omitempty"`
	Actors        []ActorDefs_ProfileView `json:"actors"`
	Cursor        gt.Option[string]       `json:"cursor,omitzero"`
	RecId         gt.Option[int64]        `json:"recId,omitzero"`    // DEPRECATED: use recIdStr instead.
	RecIdStr      gt.Option[string]       `json:"recIdStr,omitzero"` // Snowflake for this recommendation, use when submitting recommendation events.

	// extraJSON and extraCBOR preserve unknown fields for same-format round-trips.
	extraJSON []lextypes.ExtraField
	extraCBOR []lextypes.ExtraField
}

// ActorGetSuggestions calls the XRPC query "app.bsky.actor.getSuggestions".
//
// Get a list of suggested actors. Expected use is discovery of accounts to follow during new account onboarding.
func ActorGetSuggestions(ctx context.Context, c *xrpc.Client, cursor string, limit int64) (*ActorGetSuggestions_Output, error) {
	params := map[string]any{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	var out ActorGetSuggestions_Output
	return &out, c.Query(ctx, "app.bsky.actor.getSuggestions", params, &out)
}
