// Code generated by lexgen. DO NOT EDIT.

package bsky

import (
	"encoding/json"
	"fmt"
	lextypes "github.com/jcalabro/atmos/api/lextypes"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/gt"
)

// EmbedGallery_Image is a "image" in the app.bsky.embed.gallery schema.
type EmbedGallery_Image struct {
	LexiconTypeID string                `json:"$type,omitempty"`
	Alt           string                `json:"alt"` // Alt text description of the image, for accessibility.
	AspectRatio   EmbedDefs_AspectRatio `json:"aspectRatio"`
	Image         lextypes.LexBlob      `json:"image"`

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// Precomputed CBOR key tokens for EmbedGallery_Image.
var (
	cborKey_EmbedGallery_Image_alt         = cbor.AppendTextKey(nil, "alt")
	cborKey_EmbedGallery_Image_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_EmbedGallery_Image_image       = cbor.AppendTextKey(nil, "image")
	cborKey_EmbedGallery_Image_aspectRatio = cbor.AppendTextKey(nil, "aspectRatio")
)

func (s *EmbedGallery_Image) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *EmbedGallery_Image) AppendCBOR(buf []byte) ([]byte, error) {
	n := 3 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "alt", buf)
		buf = append(buf, cborKey_EmbedGallery_Image_alt...)
		buf = cbor.AppendText(buf, s.Alt)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_EmbedGallery_Image_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "image", buf)
		buf = append(buf, cborKey_EmbedGallery_Image_image...)
		{
			var err error
			buf, err = s.Image.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "aspectRatio", buf)
		buf = append(buf, cborKey_EmbedGallery_Image_aspectRatio...)
		{
			var err error
			buf, err = s.AspectRatio.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		buf = append(buf, cborKey_EmbedGallery_Image_alt...)
		buf = cbor.AppendText(buf, s.Alt)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_EmbedGallery_Image_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		buf = append(buf, cborKey_EmbedGallery_Image_image...)
		{
			var err error
			buf, err = s.Image.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
		buf = append(buf, cborKey_EmbedGallery_Image_aspectRatio...)
		{
			var err error
			buf, err = s.AspectRatio.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
	}
	return buf, nil
}

func (s *EmbedGallery_Image) UnmarshalCBOR(data []byte) error {
	pos, err := s.UnmarshalCBORAt(data, 0)
	if err != nil {
		return err
	}
	return cbor.CheckTrailingData(pos, len(data))
}

func (s *EmbedGallery_Image) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	var prevKeyStart, prevKeyEnd int
	keyOrderValid := false
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		if keyOrderValid {
			if err := cbor.CheckMapKeyOrder(data, prevKeyStart, prevKeyEnd, keyStart, keyEnd); err != nil {
				return 0, err
			}
		}
		prevKeyStart, prevKeyEnd = keyStart, keyEnd
		keyOrderValid = true
		pos = newPos
		switch keyEnd - keyStart {
		case 3:
			if string(data[keyStart:keyEnd]) == "alt" {
				s.Alt, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "image" {
				pos, err = s.Image.UnmarshalCBORAt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 11:
			if string(data[keyStart:keyEnd]) == "aspectRatio" {
				pos, err = s.AspectRatio.UnmarshalCBORAt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

// Precomputed JSON key tokens for EmbedGallery_Image.
var (
	jsonKey_EmbedGallery_Image_dollar_type = []byte("\"$type\":")
	jsonKey_EmbedGallery_Image_alt         = []byte("\"alt\":")
	jsonKey_EmbedGallery_Image_aspectRatio = []byte("\"aspectRatio\":")
	jsonKey_EmbedGallery_Image_image       = []byte("\"image\":")
)

func (s *EmbedGallery_Image) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *EmbedGallery_Image) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_EmbedGallery_Image_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_EmbedGallery_Image_alt...)
	buf = cbor.AppendJSONString(buf, s.Alt)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_EmbedGallery_Image_aspectRatio...)
	{
		var err error
		buf, err = s.AspectRatio.AppendJSON(buf)
		if err != nil {
			return nil, err
		}
	}
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_EmbedGallery_Image_image...)
	{
		var err error
		buf, err = s.Image.AppendJSON(buf)
		if err != nil {
			return nil, err
		}
	}
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *EmbedGallery_Image) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *EmbedGallery_Image) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "alt":
			s.Alt, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "aspectRatio":
			pos, err = s.AspectRatio.UnmarshalJSONAt(data, pos)
			if err != nil {
				return 0, err
			}
		case "image":
			pos, err = s.Image.UnmarshalJSONAt(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// EmbedGallery is a "main" in the app.bsky.embed.gallery schema.
type EmbedGallery struct {
	LexiconTypeID string               `json:"$type,omitempty"`
	Items         []EmbedGallery_Items `json:"items"` // The schema-level maxLength of 20 is a future-proof ceiling. Clients should currently enforce a so...

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// EmbedGallery_Items is a union type.
type EmbedGallery_Items struct {
	EmbedGallery_Image gt.Ref[EmbedGallery_Image]
	Unknown            gt.Ref[lextypes.UnknownUnionVariant]
}

func (u EmbedGallery_Items) MarshalJSON() ([]byte, error) {
	return u.AppendJSON(make([]byte, 0, 256))
}

func (u EmbedGallery_Items) AppendJSON(buf []byte) ([]byte, error) {
	if u.EmbedGallery_Image.HasVal() {
		v := *u.EmbedGallery_Image.Val()
		v.LexiconTypeID = "app.bsky.embed.gallery#image"
		return v.AppendJSON(buf)
	}
	if u.Unknown.HasVal() {
		return append(buf, u.Unknown.Val().Raw...), nil
	}
	return nil, fmt.Errorf("cannot marshal empty union EmbedGallery_Items")
}

func (u *EmbedGallery_Items) UnmarshalJSON(data []byte) error {
	_, err := u.UnmarshalJSONAt(data, 0)
	return err
}

func (u *EmbedGallery_Items) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	endPos, err := cbor.SkipJSONValue(data, pos)
	if err != nil {
		return 0, err
	}
	typ, err := cbor.PeekJSONType(data[pos:endPos])
	if err != nil {
		return 0, err
	}
	switch typ {
	case "app.bsky.embed.gallery#image":
		var v EmbedGallery_Image
		endPos, err = v.UnmarshalJSONAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.EmbedGallery_Image = gt.SomeRef(v)
		return endPos, nil
	default:
		u.Unknown = gt.SomeRef(lextypes.UnknownUnionVariant{Type: typ, Raw: json.RawMessage(data[pos:endPos])})
		return endPos, nil
	}
}

func (u EmbedGallery_Items) MarshalCBOR() ([]byte, error) {
	return u.AppendCBOR(make([]byte, 0, 256))
}

func (u EmbedGallery_Items) AppendCBOR(buf []byte) ([]byte, error) {
	if u.EmbedGallery_Image.HasVal() {
		v := *u.EmbedGallery_Image.Val()
		v.LexiconTypeID = "app.bsky.embed.gallery#image"
		return v.AppendCBOR(buf)
	}
	if u.Unknown.HasVal() {
		return append(buf, u.Unknown.Val().RawCBOR...), nil
	}
	return nil, fmt.Errorf("cannot marshal empty union EmbedGallery_Items")
}

func (u *EmbedGallery_Items) UnmarshalCBOR(data []byte) error {
	pos, err := u.UnmarshalCBORAt(data, 0)
	if err != nil {
		return err
	}
	return cbor.CheckTrailingData(pos, len(data))
}

func (u *EmbedGallery_Items) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	typ, err := cbor.PeekTypeAt(data, pos)
	if err != nil {
		return 0, err
	}
	switch typ {
	case "app.bsky.embed.gallery#image":
		var v EmbedGallery_Image
		pos, err = v.UnmarshalCBORAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.EmbedGallery_Image = gt.SomeRef(v)
		return pos, nil
	default:
		startPos := pos
		pos, err = cbor.SkipValue(data, pos)
		if err != nil {
			return 0, err
		}
		raw := make([]byte, pos-startPos)
		copy(raw, data[startPos:pos])
		u.Unknown = gt.SomeRef(lextypes.UnknownUnionVariant{Type: typ, RawCBOR: raw})
		return pos, nil
	}
}

// Precomputed CBOR key tokens for EmbedGallery.
var (
	cborKey_EmbedGallery_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_EmbedGallery_items       = cbor.AppendTextKey(nil, "items")
)

func (s *EmbedGallery) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *EmbedGallery) AppendCBOR(buf []byte) ([]byte, error) {
	n := 1 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_EmbedGallery_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "items", buf)
		buf = append(buf, cborKey_EmbedGallery_items...)
		buf = cbor.AppendArrayHeader(buf, uint64(len(s.Items)))
		for _, item := range s.Items {
			var err error
			buf, err = item.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_EmbedGallery_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		buf = append(buf, cborKey_EmbedGallery_items...)
		buf = cbor.AppendArrayHeader(buf, uint64(len(s.Items)))
		for _, item := range s.Items {
			var err error
			buf, err = item.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
	}
	return buf, nil
}

func (s *EmbedGallery) UnmarshalCBOR(data []byte) error {
	pos, err := s.UnmarshalCBORAt(data, 0)
	if err != nil {
		return err
	}
	return cbor.CheckTrailingData(pos, len(data))
}

func (s *EmbedGallery) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	var prevKeyStart, prevKeyEnd int
	keyOrderValid := false
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		if keyOrderValid {
			if err := cbor.CheckMapKeyOrder(data, prevKeyStart, prevKeyEnd, keyStart, keyEnd); err != nil {
				return 0, err
			}
		}
		prevKeyStart, prevKeyEnd = keyStart, keyEnd
		keyOrderValid = true
		pos = newPos
		switch keyEnd - keyStart {
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "items" {
				{
					arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
					if err != nil {
						return 0, err
					}
					if err := cbor.CheckArrayLen(arrLen, data, newPos); err != nil {
						return 0, err
					}
					pos = newPos
					s.Items = make([]EmbedGallery_Items, arrLen)
					for idx := range arrLen {
						pos, err = s.Items[idx].UnmarshalCBORAt(data, pos)
						if err != nil {
							return 0, err
						}
					}
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

// Precomputed JSON key tokens for EmbedGallery.
var (
	jsonKey_EmbedGallery_dollar_type = []byte("\"$type\":")
	jsonKey_EmbedGallery_items       = []byte("\"items\":")
)

func (s *EmbedGallery) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *EmbedGallery) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_EmbedGallery_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_EmbedGallery_items...)
	buf = append(buf, '[')
	for i, item := range s.Items {
		if i > 0 {
			buf = append(buf, ',')
		}
		var err error
		buf, err = item.AppendJSON(buf)
		if err != nil {
			return nil, err
		}
	}
	buf = append(buf, ']')
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *EmbedGallery) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *EmbedGallery) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "items":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.Items = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem EmbedGallery_Items
					pos, err = elem.UnmarshalJSONAt(data, pos)
					if err != nil {
						return 0, err
					}
					s.Items = append(s.Items, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// EmbedGallery_View is a "view" in the app.bsky.embed.gallery schema.
type EmbedGallery_View struct {
	LexiconTypeID string                    `json:"$type,omitempty"`
	Items         []EmbedGallery_View_Items `json:"items"`

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// EmbedGallery_View_Items is a union type.
type EmbedGallery_View_Items struct {
	EmbedGallery_ViewImage gt.Ref[EmbedGallery_ViewImage]
	Unknown                gt.Ref[lextypes.UnknownUnionVariant]
}

func (u EmbedGallery_View_Items) MarshalJSON() ([]byte, error) {
	return u.AppendJSON(make([]byte, 0, 256))
}

func (u EmbedGallery_View_Items) AppendJSON(buf []byte) ([]byte, error) {
	if u.EmbedGallery_ViewImage.HasVal() {
		v := *u.EmbedGallery_ViewImage.Val()
		v.LexiconTypeID = "app.bsky.embed.gallery#viewImage"
		return v.AppendJSON(buf)
	}
	if u.Unknown.HasVal() {
		return append(buf, u.Unknown.Val().Raw...), nil
	}
	return nil, fmt.Errorf("cannot marshal empty union EmbedGallery_View_Items")
}

func (u *EmbedGallery_View_Items) UnmarshalJSON(data []byte) error {
	_, err := u.UnmarshalJSONAt(data, 0)
	return err
}

func (u *EmbedGallery_View_Items) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	endPos, err := cbor.SkipJSONValue(data, pos)
	if err != nil {
		return 0, err
	}
	typ, err := cbor.PeekJSONType(data[pos:endPos])
	if err != nil {
		return 0, err
	}
	switch typ {
	case "app.bsky.embed.gallery#viewImage":
		var v EmbedGallery_ViewImage
		endPos, err = v.UnmarshalJSONAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.EmbedGallery_ViewImage = gt.SomeRef(v)
		return endPos, nil
	default:
		u.Unknown = gt.SomeRef(lextypes.UnknownUnionVariant{Type: typ, Raw: json.RawMessage(data[pos:endPos])})
		return endPos, nil
	}
}

func (u EmbedGallery_View_Items) MarshalCBOR() ([]byte, error) {
	return u.AppendCBOR(make([]byte, 0, 256))
}

func (u EmbedGallery_View_Items) AppendCBOR(buf []byte) ([]byte, error) {
	if u.EmbedGallery_ViewImage.HasVal() {
		v := *u.EmbedGallery_ViewImage.Val()
		v.LexiconTypeID = "app.bsky.embed.gallery#viewImage"
		return v.AppendCBOR(buf)
	}
	if u.Unknown.HasVal() {
		return append(buf, u.Unknown.Val().RawCBOR...), nil
	}
	return nil, fmt.Errorf("cannot marshal empty union EmbedGallery_View_Items")
}

func (u *EmbedGallery_View_Items) UnmarshalCBOR(data []byte) error {
	pos, err := u.UnmarshalCBORAt(data, 0)
	if err != nil {
		return err
	}
	return cbor.CheckTrailingData(pos, len(data))
}

func (u *EmbedGallery_View_Items) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	typ, err := cbor.PeekTypeAt(data, pos)
	if err != nil {
		return 0, err
	}
	switch typ {
	case "app.bsky.embed.gallery#viewImage":
		var v EmbedGallery_ViewImage
		pos, err = v.UnmarshalCBORAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.EmbedGallery_ViewImage = gt.SomeRef(v)
		return pos, nil
	default:
		startPos := pos
		pos, err = cbor.SkipValue(data, pos)
		if err != nil {
			return 0, err
		}
		raw := make([]byte, pos-startPos)
		copy(raw, data[startPos:pos])
		u.Unknown = gt.SomeRef(lextypes.UnknownUnionVariant{Type: typ, RawCBOR: raw})
		return pos, nil
	}
}

// Precomputed CBOR key tokens for EmbedGallery_View.
var (
	cborKey_EmbedGallery_View_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_EmbedGallery_View_items       = cbor.AppendTextKey(nil, "items")
)

func (s *EmbedGallery_View) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *EmbedGallery_View) AppendCBOR(buf []byte) ([]byte, error) {
	n := 1 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_EmbedGallery_View_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "items", buf)
		buf = append(buf, cborKey_EmbedGallery_View_items...)
		buf = cbor.AppendArrayHeader(buf, uint64(len(s.Items)))
		for _, item := range s.Items {
			var err error
			buf, err = item.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_EmbedGallery_View_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		buf = append(buf, cborKey_EmbedGallery_View_items...)
		buf = cbor.AppendArrayHeader(buf, uint64(len(s.Items)))
		for _, item := range s.Items {
			var err error
			buf, err = item.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
	}
	return buf, nil
}

func (s *EmbedGallery_View) UnmarshalCBOR(data []byte) error {
	pos, err := s.UnmarshalCBORAt(data, 0)
	if err != nil {
		return err
	}
	return cbor.CheckTrailingData(pos, len(data))
}

func (s *EmbedGallery_View) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	var prevKeyStart, prevKeyEnd int
	keyOrderValid := false
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		if keyOrderValid {
			if err := cbor.CheckMapKeyOrder(data, prevKeyStart, prevKeyEnd, keyStart, keyEnd); err != nil {
				return 0, err
			}
		}
		prevKeyStart, prevKeyEnd = keyStart, keyEnd
		keyOrderValid = true
		pos = newPos
		switch keyEnd - keyStart {
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "items" {
				{
					arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
					if err != nil {
						return 0, err
					}
					if err := cbor.CheckArrayLen(arrLen, data, newPos); err != nil {
						return 0, err
					}
					pos = newPos
					s.Items = make([]EmbedGallery_View_Items, arrLen)
					for idx := range arrLen {
						pos, err = s.Items[idx].UnmarshalCBORAt(data, pos)
						if err != nil {
							return 0, err
						}
					}
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

// Precomputed JSON key tokens for EmbedGallery_View.
var (
	jsonKey_EmbedGallery_View_dollar_type = []byte("\"$type\":")
	jsonKey_EmbedGallery_View_items       = []byte("\"items\":")
)

func (s *EmbedGallery_View) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *EmbedGallery_View) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_EmbedGallery_View_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_EmbedGallery_View_items...)
	buf = append(buf, '[')
	for i, item := range s.Items {
		if i > 0 {
			buf = append(buf, ',')
		}
		var err error
		buf, err = item.AppendJSON(buf)
		if err != nil {
			return nil, err
		}
	}
	buf = append(buf, ']')
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *EmbedGallery_View) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *EmbedGallery_View) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "items":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.Items = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem EmbedGallery_View_Items
					pos, err = elem.UnmarshalJSONAt(data, pos)
					if err != nil {
						return 0, err
					}
					s.Items = append(s.Items, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// EmbedGallery_ViewImage is a "viewImage" in the app.bsky.embed.gallery schema.
type EmbedGallery_ViewImage struct {
	LexiconTypeID string                `json:"$type,omitempty"`
	Alt           string                `json:"alt"` // Alt text description of the image, for accessibility.
	AspectRatio   EmbedDefs_AspectRatio `json:"aspectRatio"`
	Fullsize      string                `json:"fullsize"`  // Fully-qualified URL where a large version of the image can be fetched. May or may not be the exac...
	Thumbnail     string                `json:"thumbnail"` // Fully-qualified URL where a thumbnail of the image can be fetched. For example, CDN location prov...

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// Precomputed CBOR key tokens for EmbedGallery_ViewImage.
var (
	cborKey_EmbedGallery_ViewImage_alt         = cbor.AppendTextKey(nil, "alt")
	cborKey_EmbedGallery_ViewImage_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_EmbedGallery_ViewImage_fullsize    = cbor.AppendTextKey(nil, "fullsize")
	cborKey_EmbedGallery_ViewImage_thumbnail   = cbor.AppendTextKey(nil, "thumbnail")
	cborKey_EmbedGallery_ViewImage_aspectRatio = cbor.AppendTextKey(nil, "aspectRatio")
)

func (s *EmbedGallery_ViewImage) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *EmbedGallery_ViewImage) AppendCBOR(buf []byte) ([]byte, error) {
	n := 4 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "alt", buf)
		buf = append(buf, cborKey_EmbedGallery_ViewImage_alt...)
		buf = cbor.AppendText(buf, s.Alt)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_EmbedGallery_ViewImage_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "fullsize", buf)
		buf = append(buf, cborKey_EmbedGallery_ViewImage_fullsize...)
		buf = cbor.AppendText(buf, s.Fullsize)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "thumbnail", buf)
		buf = append(buf, cborKey_EmbedGallery_ViewImage_thumbnail...)
		buf = cbor.AppendText(buf, s.Thumbnail)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "aspectRatio", buf)
		buf = append(buf, cborKey_EmbedGallery_ViewImage_aspectRatio...)
		{
			var err error
			buf, err = s.AspectRatio.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		buf = append(buf, cborKey_EmbedGallery_ViewImage_alt...)
		buf = cbor.AppendText(buf, s.Alt)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_EmbedGallery_ViewImage_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		buf = append(buf, cborKey_EmbedGallery_ViewImage_fullsize...)
		buf = cbor.AppendText(buf, s.Fullsize)
		buf = append(buf, cborKey_EmbedGallery_ViewImage_thumbnail...)
		buf = cbor.AppendText(buf, s.Thumbnail)
		buf = append(buf, cborKey_EmbedGallery_ViewImage_aspectRatio...)
		{
			var err error
			buf, err = s.AspectRatio.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
	}
	return buf, nil
}

func (s *EmbedGallery_ViewImage) UnmarshalCBOR(data []byte) error {
	pos, err := s.UnmarshalCBORAt(data, 0)
	if err != nil {
		return err
	}
	return cbor.CheckTrailingData(pos, len(data))
}

func (s *EmbedGallery_ViewImage) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	var prevKeyStart, prevKeyEnd int
	keyOrderValid := false
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		if keyOrderValid {
			if err := cbor.CheckMapKeyOrder(data, prevKeyStart, prevKeyEnd, keyStart, keyEnd); err != nil {
				return 0, err
			}
		}
		prevKeyStart, prevKeyEnd = keyStart, keyEnd
		keyOrderValid = true
		pos = newPos
		switch keyEnd - keyStart {
		case 3:
			if string(data[keyStart:keyEnd]) == "alt" {
				s.Alt, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 8:
			if string(data[keyStart:keyEnd]) == "fullsize" {
				s.Fullsize, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 9:
			if string(data[keyStart:keyEnd]) == "thumbnail" {
				s.Thumbnail, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 11:
			if string(data[keyStart:keyEnd]) == "aspectRatio" {
				pos, err = s.AspectRatio.UnmarshalCBORAt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

// Precomputed JSON key tokens for EmbedGallery_ViewImage.
var (
	jsonKey_EmbedGallery_ViewImage_dollar_type = []byte("\"$type\":")
	jsonKey_EmbedGallery_ViewImage_alt         = []byte("\"alt\":")
	jsonKey_EmbedGallery_ViewImage_aspectRatio = []byte("\"aspectRatio\":")
	jsonKey_EmbedGallery_ViewImage_fullsize    = []byte("\"fullsize\":")
	jsonKey_EmbedGallery_ViewImage_thumbnail   = []byte("\"thumbnail\":")
)

func (s *EmbedGallery_ViewImage) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *EmbedGallery_ViewImage) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_EmbedGallery_ViewImage_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_EmbedGallery_ViewImage_alt...)
	buf = cbor.AppendJSONString(buf, s.Alt)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_EmbedGallery_ViewImage_aspectRatio...)
	{
		var err error
		buf, err = s.AspectRatio.AppendJSON(buf)
		if err != nil {
			return nil, err
		}
	}
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_EmbedGallery_ViewImage_fullsize...)
	buf = cbor.AppendJSONString(buf, s.Fullsize)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_EmbedGallery_ViewImage_thumbnail...)
	buf = cbor.AppendJSONString(buf, s.Thumbnail)
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *EmbedGallery_ViewImage) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *EmbedGallery_ViewImage) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "alt":
			s.Alt, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "aspectRatio":
			pos, err = s.AspectRatio.UnmarshalJSONAt(data, pos)
			if err != nil {
				return 0, err
			}
		case "fullsize":
			s.Fullsize, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "thumbnail":
			s.Thumbnail, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}
