// Code generated by lexgen. DO NOT EDIT.

package bsky

import (
	"encoding/json"
	"fmt"
	comatproto "github.com/jcalabro/atmos/api/comatproto"
	lextypes "github.com/jcalabro/atmos/api/lextypes"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/gt"
)

const (
	NSIDFeedPost = "app.bsky.feed.post" // Record containing a Bluesky post.

)

// FeedPost_Entity is a "entity" in the app.bsky.feed.post schema.
//
// Deprecated: use facets instead.
type FeedPost_Entity struct {
	LexiconTypeID string             `json:"$type,omitempty"`
	Index         FeedPost_TextSlice `json:"index"`
	Type          string             `json:"type"` // Expected values are 'mention' and 'link'.
	Value         string             `json:"value"`

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// Precomputed CBOR key tokens for FeedPost_Entity.
var (
	cborKey_FeedPost_Entity_type        = cbor.AppendTextKey(nil, "type")
	cborKey_FeedPost_Entity_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_FeedPost_Entity_index       = cbor.AppendTextKey(nil, "index")
	cborKey_FeedPost_Entity_value       = cbor.AppendTextKey(nil, "value")
)

func (s *FeedPost_Entity) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *FeedPost_Entity) AppendCBOR(buf []byte) ([]byte, error) {
	n := 3 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "type", buf)
		buf = append(buf, cborKey_FeedPost_Entity_type...)
		buf = cbor.AppendText(buf, s.Type)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_FeedPost_Entity_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "index", buf)
		buf = append(buf, cborKey_FeedPost_Entity_index...)
		{
			var err error
			buf, err = s.Index.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "value", buf)
		buf = append(buf, cborKey_FeedPost_Entity_value...)
		buf = cbor.AppendText(buf, s.Value)
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		buf = append(buf, cborKey_FeedPost_Entity_type...)
		buf = cbor.AppendText(buf, s.Type)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_FeedPost_Entity_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		buf = append(buf, cborKey_FeedPost_Entity_index...)
		{
			var err error
			buf, err = s.Index.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
		buf = append(buf, cborKey_FeedPost_Entity_value...)
		buf = cbor.AppendText(buf, s.Value)
	}
	return buf, nil
}

func (s *FeedPost_Entity) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *FeedPost_Entity) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 4:
			if string(data[keyStart:keyEnd]) == "type" {
				s.Type, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "index" {
				pos, err = s.Index.UnmarshalCBORAt(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "value" {
				s.Value, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

// Precomputed JSON key tokens for FeedPost_Entity.
var (
	jsonKey_FeedPost_Entity_dollar_type = []byte("\"$type\":")
	jsonKey_FeedPost_Entity_index       = []byte("\"index\":")
	jsonKey_FeedPost_Entity_type        = []byte("\"type\":")
	jsonKey_FeedPost_Entity_value       = []byte("\"value\":")
)

func (s *FeedPost_Entity) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *FeedPost_Entity) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_FeedPost_Entity_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_FeedPost_Entity_index...)
	{
		var err error
		buf, err = s.Index.AppendJSON(buf)
		if err != nil {
			return nil, err
		}
	}
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_FeedPost_Entity_type...)
	buf = cbor.AppendJSONString(buf, s.Type)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_FeedPost_Entity_value...)
	buf = cbor.AppendJSONString(buf, s.Value)
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *FeedPost_Entity) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *FeedPost_Entity) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "index":
			pos, err = s.Index.UnmarshalJSONAt(data, pos)
			if err != nil {
				return 0, err
			}
		case "type":
			s.Type, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "value":
			s.Value, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// FeedPost is a "app.bsky.feed.post" record.
//
// Record containing a Bluesky post.
type FeedPost struct {
	LexiconTypeID string                       `json:"$type,omitempty" cborgen:"$type,const=app.bsky.feed.post"`
	CreatedAt     string                       `json:"createdAt"` // Client-declared timestamp when this post was originally created.
	Embed         gt.Option[FeedPost_Embed]    `json:"embed,omitzero"`
	Entities      []FeedPost_Entity            `json:"entities,omitempty"` // DEPRECATED: replaced by app.bsky.richtext.facet.
	Facets        []RichtextFacet              `json:"facets,omitempty"`   // Annotations of text (mentions, URLs, hashtags, etc)
	Labels        gt.Option[FeedPost_Labels]   `json:"labels,omitzero"`    // Self-label values for this post. Effectively content warnings.
	Langs         []string                     `json:"langs,omitempty"`    // Indicates human language of post primary text content.
	Reply         gt.Option[FeedPost_ReplyRef] `json:"reply,omitzero"`
	Tags          []string                     `json:"tags,omitempty"` // Additional hashtags, in addition to any included in post text and facets.
	Text          string                       `json:"text"`           // The primary post content. May be an empty string, if there are embeds.

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// FeedPost_Embed is a union type.
type FeedPost_Embed struct {
	EmbedImages          gt.Ref[EmbedImages]
	EmbedVideo           gt.Ref[EmbedVideo]
	EmbedExternal        gt.Ref[EmbedExternal]
	EmbedRecord          gt.Ref[EmbedRecord]
	EmbedRecordWithMedia gt.Ref[EmbedRecordWithMedia]
	Unknown              gt.Ref[lextypes.UnknownUnionVariant]
}

func (u FeedPost_Embed) MarshalJSON() ([]byte, error) {
	return u.AppendJSON(make([]byte, 0, 256))
}

func (u FeedPost_Embed) AppendJSON(buf []byte) ([]byte, error) {
	if u.EmbedImages.HasVal() {
		v := *u.EmbedImages.Val()
		v.LexiconTypeID = "app.bsky.embed.images"
		return v.AppendJSON(buf)
	}
	if u.EmbedVideo.HasVal() {
		v := *u.EmbedVideo.Val()
		v.LexiconTypeID = "app.bsky.embed.video"
		return v.AppendJSON(buf)
	}
	if u.EmbedExternal.HasVal() {
		v := *u.EmbedExternal.Val()
		v.LexiconTypeID = "app.bsky.embed.external"
		return v.AppendJSON(buf)
	}
	if u.EmbedRecord.HasVal() {
		v := *u.EmbedRecord.Val()
		v.LexiconTypeID = "app.bsky.embed.record"
		return v.AppendJSON(buf)
	}
	if u.EmbedRecordWithMedia.HasVal() {
		v := *u.EmbedRecordWithMedia.Val()
		v.LexiconTypeID = "app.bsky.embed.recordWithMedia"
		return v.AppendJSON(buf)
	}
	if u.Unknown.HasVal() {
		return append(buf, u.Unknown.Val().Raw...), nil
	}
	return nil, fmt.Errorf("cannot marshal empty union FeedPost_Embed")
}

func (u *FeedPost_Embed) UnmarshalJSON(data []byte) error {
	_, err := u.UnmarshalJSONAt(data, 0)
	return err
}

func (u *FeedPost_Embed) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	endPos, err := cbor.SkipJSONValue(data, pos)
	if err != nil {
		return 0, err
	}
	typ, err := cbor.PeekJSONType(data[pos:endPos])
	if err != nil {
		return 0, err
	}
	switch typ {
	case "app.bsky.embed.images":
		var v EmbedImages
		endPos, err = v.UnmarshalJSONAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.EmbedImages = gt.SomeRef(v)
		return endPos, nil
	case "app.bsky.embed.video":
		var v EmbedVideo
		endPos, err = v.UnmarshalJSONAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.EmbedVideo = gt.SomeRef(v)
		return endPos, nil
	case "app.bsky.embed.external":
		var v EmbedExternal
		endPos, err = v.UnmarshalJSONAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.EmbedExternal = gt.SomeRef(v)
		return endPos, nil
	case "app.bsky.embed.record":
		var v EmbedRecord
		endPos, err = v.UnmarshalJSONAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.EmbedRecord = gt.SomeRef(v)
		return endPos, nil
	case "app.bsky.embed.recordWithMedia":
		var v EmbedRecordWithMedia
		endPos, err = v.UnmarshalJSONAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.EmbedRecordWithMedia = gt.SomeRef(v)
		return endPos, nil
	default:
		u.Unknown = gt.SomeRef(lextypes.UnknownUnionVariant{Type: typ, Raw: json.RawMessage(data[pos:endPos])})
		return endPos, nil
	}
}

func (u FeedPost_Embed) MarshalCBOR() ([]byte, error) {
	return u.AppendCBOR(make([]byte, 0, 256))
}

func (u FeedPost_Embed) AppendCBOR(buf []byte) ([]byte, error) {
	if u.EmbedImages.HasVal() {
		v := *u.EmbedImages.Val()
		v.LexiconTypeID = "app.bsky.embed.images"
		return v.AppendCBOR(buf)
	}
	if u.EmbedVideo.HasVal() {
		v := *u.EmbedVideo.Val()
		v.LexiconTypeID = "app.bsky.embed.video"
		return v.AppendCBOR(buf)
	}
	if u.EmbedExternal.HasVal() {
		v := *u.EmbedExternal.Val()
		v.LexiconTypeID = "app.bsky.embed.external"
		return v.AppendCBOR(buf)
	}
	if u.EmbedRecord.HasVal() {
		v := *u.EmbedRecord.Val()
		v.LexiconTypeID = "app.bsky.embed.record"
		return v.AppendCBOR(buf)
	}
	if u.EmbedRecordWithMedia.HasVal() {
		v := *u.EmbedRecordWithMedia.Val()
		v.LexiconTypeID = "app.bsky.embed.recordWithMedia"
		return v.AppendCBOR(buf)
	}
	if u.Unknown.HasVal() {
		return append(buf, u.Unknown.Val().RawCBOR...), nil
	}
	return nil, fmt.Errorf("cannot marshal empty union FeedPost_Embed")
}

func (u *FeedPost_Embed) UnmarshalCBOR(data []byte) error {
	_, err := u.UnmarshalCBORAt(data, 0)
	return err
}

func (u *FeedPost_Embed) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	typ, err := cbor.PeekTypeAt(data, pos)
	if err != nil {
		return 0, err
	}
	switch typ {
	case "app.bsky.embed.images":
		var v EmbedImages
		pos, err = v.UnmarshalCBORAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.EmbedImages = gt.SomeRef(v)
		return pos, nil
	case "app.bsky.embed.video":
		var v EmbedVideo
		pos, err = v.UnmarshalCBORAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.EmbedVideo = gt.SomeRef(v)
		return pos, nil
	case "app.bsky.embed.external":
		var v EmbedExternal
		pos, err = v.UnmarshalCBORAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.EmbedExternal = gt.SomeRef(v)
		return pos, nil
	case "app.bsky.embed.record":
		var v EmbedRecord
		pos, err = v.UnmarshalCBORAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.EmbedRecord = gt.SomeRef(v)
		return pos, nil
	case "app.bsky.embed.recordWithMedia":
		var v EmbedRecordWithMedia
		pos, err = v.UnmarshalCBORAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.EmbedRecordWithMedia = gt.SomeRef(v)
		return pos, nil
	default:
		startPos := pos
		pos, err = cbor.SkipValue(data, pos)
		if err != nil {
			return 0, err
		}
		raw := make([]byte, pos-startPos)
		copy(raw, data[startPos:pos])
		u.Unknown = gt.SomeRef(lextypes.UnknownUnionVariant{Type: typ, RawCBOR: raw})
		return pos, nil
	}
}

// FeedPost_Labels is a union type.
type FeedPost_Labels struct {
	LabelDefs_SelfLabels gt.Ref[comatproto.LabelDefs_SelfLabels]
	Unknown              gt.Ref[lextypes.UnknownUnionVariant]
}

func (u FeedPost_Labels) MarshalJSON() ([]byte, error) {
	return u.AppendJSON(make([]byte, 0, 256))
}

func (u FeedPost_Labels) AppendJSON(buf []byte) ([]byte, error) {
	if u.LabelDefs_SelfLabels.HasVal() {
		v := *u.LabelDefs_SelfLabels.Val()
		v.LexiconTypeID = "com.atproto.label.defs#selfLabels"
		return v.AppendJSON(buf)
	}
	if u.Unknown.HasVal() {
		return append(buf, u.Unknown.Val().Raw...), nil
	}
	return nil, fmt.Errorf("cannot marshal empty union FeedPost_Labels")
}

func (u *FeedPost_Labels) UnmarshalJSON(data []byte) error {
	_, err := u.UnmarshalJSONAt(data, 0)
	return err
}

func (u *FeedPost_Labels) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	endPos, err := cbor.SkipJSONValue(data, pos)
	if err != nil {
		return 0, err
	}
	typ, err := cbor.PeekJSONType(data[pos:endPos])
	if err != nil {
		return 0, err
	}
	switch typ {
	case "com.atproto.label.defs#selfLabels":
		var v comatproto.LabelDefs_SelfLabels
		endPos, err = v.UnmarshalJSONAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.LabelDefs_SelfLabels = gt.SomeRef(v)
		return endPos, nil
	default:
		u.Unknown = gt.SomeRef(lextypes.UnknownUnionVariant{Type: typ, Raw: json.RawMessage(data[pos:endPos])})
		return endPos, nil
	}
}

func (u FeedPost_Labels) MarshalCBOR() ([]byte, error) {
	return u.AppendCBOR(make([]byte, 0, 256))
}

func (u FeedPost_Labels) AppendCBOR(buf []byte) ([]byte, error) {
	if u.LabelDefs_SelfLabels.HasVal() {
		v := *u.LabelDefs_SelfLabels.Val()
		v.LexiconTypeID = "com.atproto.label.defs#selfLabels"
		return v.AppendCBOR(buf)
	}
	if u.Unknown.HasVal() {
		return append(buf, u.Unknown.Val().RawCBOR...), nil
	}
	return nil, fmt.Errorf("cannot marshal empty union FeedPost_Labels")
}

func (u *FeedPost_Labels) UnmarshalCBOR(data []byte) error {
	_, err := u.UnmarshalCBORAt(data, 0)
	return err
}

func (u *FeedPost_Labels) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	typ, err := cbor.PeekTypeAt(data, pos)
	if err != nil {
		return 0, err
	}
	switch typ {
	case "com.atproto.label.defs#selfLabels":
		var v comatproto.LabelDefs_SelfLabels
		pos, err = v.UnmarshalCBORAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.LabelDefs_SelfLabels = gt.SomeRef(v)
		return pos, nil
	default:
		startPos := pos
		pos, err = cbor.SkipValue(data, pos)
		if err != nil {
			return 0, err
		}
		raw := make([]byte, pos-startPos)
		copy(raw, data[startPos:pos])
		u.Unknown = gt.SomeRef(lextypes.UnknownUnionVariant{Type: typ, RawCBOR: raw})
		return pos, nil
	}
}

// Precomputed CBOR key tokens for FeedPost.
var (
	cborKey_FeedPost_tags        = cbor.AppendTextKey(nil, "tags")
	cborKey_FeedPost_text        = cbor.AppendTextKey(nil, "text")
	cborKey_FeedPost_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_FeedPost_embed       = cbor.AppendTextKey(nil, "embed")
	cborKey_FeedPost_langs       = cbor.AppendTextKey(nil, "langs")
	cborKey_FeedPost_reply       = cbor.AppendTextKey(nil, "reply")
	cborKey_FeedPost_facets      = cbor.AppendTextKey(nil, "facets")
	cborKey_FeedPost_labels      = cbor.AppendTextKey(nil, "labels")
	cborKey_FeedPost_entities    = cbor.AppendTextKey(nil, "entities")
	cborKey_FeedPost_createdAt   = cbor.AppendTextKey(nil, "createdAt")
)

func (s *FeedPost) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *FeedPost) AppendCBOR(buf []byte) ([]byte, error) {
	n := 3 + countExtra(s.extra, extraEncodingCBOR)
	if len(s.Tags) > 0 {
		n++
	}
	if s.Embed.HasVal() {
		n++
	}
	if len(s.Langs) > 0 {
		n++
	}
	if s.Reply.HasVal() {
		n++
	}
	if len(s.Facets) > 0 {
		n++
	}
	if s.Labels.HasVal() {
		n++
	}
	if len(s.Entities) > 0 {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "tags", buf)
		if len(s.Tags) > 0 {
			buf = append(buf, cborKey_FeedPost_tags...)
			buf = cbor.AppendArrayHeader(buf, uint64(len(s.Tags)))
			for _, item := range s.Tags {
				buf = cbor.AppendText(buf, item)
			}
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "text", buf)
		buf = append(buf, cborKey_FeedPost_text...)
		buf = cbor.AppendText(buf, s.Text)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		buf = append(buf, cborKey_FeedPost_dollar_type...)
		buf = cbor.AppendText(buf, s.LexiconTypeID)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "embed", buf)
		if s.Embed.HasVal() {
			buf = append(buf, cborKey_FeedPost_embed...)
			{
				v := s.Embed.Val()
				{
					var err error
					buf, err = v.AppendCBOR(buf)
					if err != nil {
						return nil, err
					}
				}
			}
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "langs", buf)
		if len(s.Langs) > 0 {
			buf = append(buf, cborKey_FeedPost_langs...)
			buf = cbor.AppendArrayHeader(buf, uint64(len(s.Langs)))
			for _, item := range s.Langs {
				buf = cbor.AppendText(buf, item)
			}
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "reply", buf)
		if s.Reply.HasVal() {
			buf = append(buf, cborKey_FeedPost_reply...)
			{
				v := s.Reply.Val()
				{
					var err error
					buf, err = v.AppendCBOR(buf)
					if err != nil {
						return nil, err
					}
				}
			}
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "facets", buf)
		if len(s.Facets) > 0 {
			buf = append(buf, cborKey_FeedPost_facets...)
			buf = cbor.AppendArrayHeader(buf, uint64(len(s.Facets)))
			for _, item := range s.Facets {
				var err error
				buf, err = item.AppendCBOR(buf)
				if err != nil {
					return nil, err
				}
			}
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "labels", buf)
		if s.Labels.HasVal() {
			buf = append(buf, cborKey_FeedPost_labels...)
			{
				v := s.Labels.Val()
				{
					var err error
					buf, err = v.AppendCBOR(buf)
					if err != nil {
						return nil, err
					}
				}
			}
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "entities", buf)
		if len(s.Entities) > 0 {
			buf = append(buf, cborKey_FeedPost_entities...)
			buf = cbor.AppendArrayHeader(buf, uint64(len(s.Entities)))
			for _, item := range s.Entities {
				var err error
				buf, err = item.AppendCBOR(buf)
				if err != nil {
					return nil, err
				}
			}
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "createdAt", buf)
		buf = append(buf, cborKey_FeedPost_createdAt...)
		buf = cbor.AppendText(buf, s.CreatedAt)
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		if len(s.Tags) > 0 {
			buf = append(buf, cborKey_FeedPost_tags...)
			buf = cbor.AppendArrayHeader(buf, uint64(len(s.Tags)))
			for _, item := range s.Tags {
				buf = cbor.AppendText(buf, item)
			}
		}
		buf = append(buf, cborKey_FeedPost_text...)
		buf = cbor.AppendText(buf, s.Text)
		buf = append(buf, cborKey_FeedPost_dollar_type...)
		buf = cbor.AppendText(buf, s.LexiconTypeID)
		if s.Embed.HasVal() {
			buf = append(buf, cborKey_FeedPost_embed...)
			{
				v := s.Embed.Val()
				{
					var err error
					buf, err = v.AppendCBOR(buf)
					if err != nil {
						return nil, err
					}
				}
			}
		}
		if len(s.Langs) > 0 {
			buf = append(buf, cborKey_FeedPost_langs...)
			buf = cbor.AppendArrayHeader(buf, uint64(len(s.Langs)))
			for _, item := range s.Langs {
				buf = cbor.AppendText(buf, item)
			}
		}
		if s.Reply.HasVal() {
			buf = append(buf, cborKey_FeedPost_reply...)
			{
				v := s.Reply.Val()
				{
					var err error
					buf, err = v.AppendCBOR(buf)
					if err != nil {
						return nil, err
					}
				}
			}
		}
		if len(s.Facets) > 0 {
			buf = append(buf, cborKey_FeedPost_facets...)
			buf = cbor.AppendArrayHeader(buf, uint64(len(s.Facets)))
			for _, item := range s.Facets {
				var err error
				buf, err = item.AppendCBOR(buf)
				if err != nil {
					return nil, err
				}
			}
		}
		if s.Labels.HasVal() {
			buf = append(buf, cborKey_FeedPost_labels...)
			{
				v := s.Labels.Val()
				{
					var err error
					buf, err = v.AppendCBOR(buf)
					if err != nil {
						return nil, err
					}
				}
			}
		}
		if len(s.Entities) > 0 {
			buf = append(buf, cborKey_FeedPost_entities...)
			buf = cbor.AppendArrayHeader(buf, uint64(len(s.Entities)))
			for _, item := range s.Entities {
				var err error
				buf, err = item.AppendCBOR(buf)
				if err != nil {
					return nil, err
				}
			}
		}
		buf = append(buf, cborKey_FeedPost_createdAt...)
		buf = cbor.AppendText(buf, s.CreatedAt)
	}
	return buf, nil
}

func (s *FeedPost) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *FeedPost) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 4:
			if string(data[keyStart:keyEnd]) == "tags" {
				{
					arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
					if err != nil {
						return 0, err
					}
					pos = newPos
					s.Tags = make([]string, arrLen)
					for idx := range arrLen {
						s.Tags[idx], pos, err = cbor.ReadText(data, pos)
						if err != nil {
							return 0, err
						}
					}
				}
			} else if string(data[keyStart:keyEnd]) == "text" {
				s.Text, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "embed" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v FeedPost_Embed
					pos, err = v.UnmarshalCBORAt(data, pos)
					if err != nil {
						return 0, err
					}
					s.Embed = gt.Some(v)
				}
			} else if string(data[keyStart:keyEnd]) == "langs" {
				{
					arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
					if err != nil {
						return 0, err
					}
					pos = newPos
					s.Langs = make([]string, arrLen)
					for idx := range arrLen {
						s.Langs[idx], pos, err = cbor.ReadText(data, pos)
						if err != nil {
							return 0, err
						}
					}
				}
			} else if string(data[keyStart:keyEnd]) == "reply" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v FeedPost_ReplyRef
					pos, err = v.UnmarshalCBORAt(data, pos)
					if err != nil {
						return 0, err
					}
					s.Reply = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 6:
			if string(data[keyStart:keyEnd]) == "facets" {
				{
					arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
					if err != nil {
						return 0, err
					}
					pos = newPos
					s.Facets = make([]RichtextFacet, arrLen)
					for idx := range arrLen {
						pos, err = s.Facets[idx].UnmarshalCBORAt(data, pos)
						if err != nil {
							return 0, err
						}
					}
				}
			} else if string(data[keyStart:keyEnd]) == "labels" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v FeedPost_Labels
					pos, err = v.UnmarshalCBORAt(data, pos)
					if err != nil {
						return 0, err
					}
					s.Labels = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 8:
			if string(data[keyStart:keyEnd]) == "entities" {
				{
					arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
					if err != nil {
						return 0, err
					}
					pos = newPos
					s.Entities = make([]FeedPost_Entity, arrLen)
					for idx := range arrLen {
						pos, err = s.Entities[idx].UnmarshalCBORAt(data, pos)
						if err != nil {
							return 0, err
						}
					}
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 9:
			if string(data[keyStart:keyEnd]) == "createdAt" {
				s.CreatedAt, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

// Precomputed JSON key tokens for FeedPost.
var (
	jsonKey_FeedPost_dollar_type = []byte("\"$type\":")
	jsonKey_FeedPost_createdAt   = []byte("\"createdAt\":")
	jsonKey_FeedPost_embed       = []byte("\"embed\":")
	jsonKey_FeedPost_entities    = []byte("\"entities\":")
	jsonKey_FeedPost_facets      = []byte("\"facets\":")
	jsonKey_FeedPost_labels      = []byte("\"labels\":")
	jsonKey_FeedPost_langs       = []byte("\"langs\":")
	jsonKey_FeedPost_reply       = []byte("\"reply\":")
	jsonKey_FeedPost_tags        = []byte("\"tags\":")
	jsonKey_FeedPost_text        = []byte("\"text\":")
)

func (s *FeedPost) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *FeedPost) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_FeedPost_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_FeedPost_createdAt...)
	buf = cbor.AppendJSONString(buf, s.CreatedAt)
	first = false
	if s.Embed.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_FeedPost_embed...)
		{
			v := s.Embed.Val()
			{
				var err error
				buf, err = v.AppendJSON(buf)
				if err != nil {
					return nil, err
				}
			}
		}
		first = false
	}
	if len(s.Entities) > 0 {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_FeedPost_entities...)
		buf = append(buf, '[')
		for i, item := range s.Entities {
			if i > 0 {
				buf = append(buf, ',')
			}
			var err error
			buf, err = item.AppendJSON(buf)
			if err != nil {
				return nil, err
			}
		}
		buf = append(buf, ']')
		first = false
	}
	if len(s.Facets) > 0 {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_FeedPost_facets...)
		buf = append(buf, '[')
		for i, item := range s.Facets {
			if i > 0 {
				buf = append(buf, ',')
			}
			var err error
			buf, err = item.AppendJSON(buf)
			if err != nil {
				return nil, err
			}
		}
		buf = append(buf, ']')
		first = false
	}
	if s.Labels.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_FeedPost_labels...)
		{
			v := s.Labels.Val()
			{
				var err error
				buf, err = v.AppendJSON(buf)
				if err != nil {
					return nil, err
				}
			}
		}
		first = false
	}
	if len(s.Langs) > 0 {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_FeedPost_langs...)
		buf = append(buf, '[')
		for i, item := range s.Langs {
			if i > 0 {
				buf = append(buf, ',')
			}
			buf = cbor.AppendJSONString(buf, item)
		}
		buf = append(buf, ']')
		first = false
	}
	if s.Reply.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_FeedPost_reply...)
		{
			v := s.Reply.Val()
			{
				var err error
				buf, err = v.AppendJSON(buf)
				if err != nil {
					return nil, err
				}
			}
		}
		first = false
	}
	if len(s.Tags) > 0 {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_FeedPost_tags...)
		buf = append(buf, '[')
		for i, item := range s.Tags {
			if i > 0 {
				buf = append(buf, ',')
			}
			buf = cbor.AppendJSONString(buf, item)
		}
		buf = append(buf, ']')
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_FeedPost_text...)
	buf = cbor.AppendJSONString(buf, s.Text)
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *FeedPost) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *FeedPost) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "createdAt":
			s.CreatedAt, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "embed":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v FeedPost_Embed
				pos, err = v.UnmarshalJSONAt(data, pos)
				if err != nil {
					return 0, err
				}
				s.Embed = gt.Some(v)
			}
		case "entities":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.Entities = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem FeedPost_Entity
					pos, err = elem.UnmarshalJSONAt(data, pos)
					if err != nil {
						return 0, err
					}
					s.Entities = append(s.Entities, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case "facets":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.Facets = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem RichtextFacet
					pos, err = elem.UnmarshalJSONAt(data, pos)
					if err != nil {
						return 0, err
					}
					s.Facets = append(s.Facets, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case "labels":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v FeedPost_Labels
				pos, err = v.UnmarshalJSONAt(data, pos)
				if err != nil {
					return 0, err
				}
				s.Labels = gt.Some(v)
			}
		case "langs":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.Langs = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem string
					elem, pos, err = cbor.ReadJSONString(data, pos)
					if err != nil {
						return 0, err
					}
					s.Langs = append(s.Langs, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case "reply":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v FeedPost_ReplyRef
				pos, err = v.UnmarshalJSONAt(data, pos)
				if err != nil {
					return 0, err
				}
				s.Reply = gt.Some(v)
			}
		case "tags":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.Tags = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem string
					elem, pos, err = cbor.ReadJSONString(data, pos)
					if err != nil {
						return 0, err
					}
					s.Tags = append(s.Tags, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case "text":
			s.Text, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// FeedPost_ReplyRef is a "replyRef" in the app.bsky.feed.post schema.
type FeedPost_ReplyRef struct {
	LexiconTypeID string                   `json:"$type,omitempty"`
	Parent        comatproto.RepoStrongRef `json:"parent"`
	Root          comatproto.RepoStrongRef `json:"root"`

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// Precomputed CBOR key tokens for FeedPost_ReplyRef.
var (
	cborKey_FeedPost_ReplyRef_root        = cbor.AppendTextKey(nil, "root")
	cborKey_FeedPost_ReplyRef_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_FeedPost_ReplyRef_parent      = cbor.AppendTextKey(nil, "parent")
)

func (s *FeedPost_ReplyRef) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *FeedPost_ReplyRef) AppendCBOR(buf []byte) ([]byte, error) {
	n := 2 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "root", buf)
		buf = append(buf, cborKey_FeedPost_ReplyRef_root...)
		{
			var err error
			buf, err = s.Root.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_FeedPost_ReplyRef_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "parent", buf)
		buf = append(buf, cborKey_FeedPost_ReplyRef_parent...)
		{
			var err error
			buf, err = s.Parent.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		buf = append(buf, cborKey_FeedPost_ReplyRef_root...)
		{
			var err error
			buf, err = s.Root.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_FeedPost_ReplyRef_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		buf = append(buf, cborKey_FeedPost_ReplyRef_parent...)
		{
			var err error
			buf, err = s.Parent.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
	}
	return buf, nil
}

func (s *FeedPost_ReplyRef) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *FeedPost_ReplyRef) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 4:
			if string(data[keyStart:keyEnd]) == "root" {
				pos, err = s.Root.UnmarshalCBORAt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 6:
			if string(data[keyStart:keyEnd]) == "parent" {
				pos, err = s.Parent.UnmarshalCBORAt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

// Precomputed JSON key tokens for FeedPost_ReplyRef.
var (
	jsonKey_FeedPost_ReplyRef_dollar_type = []byte("\"$type\":")
	jsonKey_FeedPost_ReplyRef_parent      = []byte("\"parent\":")
	jsonKey_FeedPost_ReplyRef_root        = []byte("\"root\":")
)

func (s *FeedPost_ReplyRef) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *FeedPost_ReplyRef) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_FeedPost_ReplyRef_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_FeedPost_ReplyRef_parent...)
	{
		var err error
		buf, err = s.Parent.AppendJSON(buf)
		if err != nil {
			return nil, err
		}
	}
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_FeedPost_ReplyRef_root...)
	{
		var err error
		buf, err = s.Root.AppendJSON(buf)
		if err != nil {
			return nil, err
		}
	}
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *FeedPost_ReplyRef) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *FeedPost_ReplyRef) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "parent":
			pos, err = s.Parent.UnmarshalJSONAt(data, pos)
			if err != nil {
				return 0, err
			}
		case "root":
			pos, err = s.Root.UnmarshalJSONAt(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// FeedPost_TextSlice is a "textSlice" in the app.bsky.feed.post schema.
//
// Deprecated. Use app.bsky.richtext instead -- A text segment. Start is inclusive, end is exclusive. Indices are for utf16-encoded strings.
type FeedPost_TextSlice struct {
	LexiconTypeID string `json:"$type,omitempty"`
	End           int64  `json:"end"`
	Start         int64  `json:"start"`

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// Precomputed CBOR key tokens for FeedPost_TextSlice.
var (
	cborKey_FeedPost_TextSlice_end         = cbor.AppendTextKey(nil, "end")
	cborKey_FeedPost_TextSlice_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_FeedPost_TextSlice_start       = cbor.AppendTextKey(nil, "start")
)

func (s *FeedPost_TextSlice) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *FeedPost_TextSlice) AppendCBOR(buf []byte) ([]byte, error) {
	n := 2 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "end", buf)
		buf = append(buf, cborKey_FeedPost_TextSlice_end...)
		buf = cbor.AppendInt(buf, s.End)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_FeedPost_TextSlice_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "start", buf)
		buf = append(buf, cborKey_FeedPost_TextSlice_start...)
		buf = cbor.AppendInt(buf, s.Start)
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		buf = append(buf, cborKey_FeedPost_TextSlice_end...)
		buf = cbor.AppendInt(buf, s.End)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_FeedPost_TextSlice_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		buf = append(buf, cborKey_FeedPost_TextSlice_start...)
		buf = cbor.AppendInt(buf, s.Start)
	}
	return buf, nil
}

func (s *FeedPost_TextSlice) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *FeedPost_TextSlice) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 3:
			if string(data[keyStart:keyEnd]) == "end" {
				s.End, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "start" {
				s.Start, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

// Precomputed JSON key tokens for FeedPost_TextSlice.
var (
	jsonKey_FeedPost_TextSlice_dollar_type = []byte("\"$type\":")
	jsonKey_FeedPost_TextSlice_end         = []byte("\"end\":")
	jsonKey_FeedPost_TextSlice_start       = []byte("\"start\":")
)

func (s *FeedPost_TextSlice) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *FeedPost_TextSlice) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_FeedPost_TextSlice_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_FeedPost_TextSlice_end...)
	buf = cbor.AppendJSONInt(buf, s.End)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_FeedPost_TextSlice_start...)
	buf = cbor.AppendJSONInt(buf, s.Start)
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *FeedPost_TextSlice) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *FeedPost_TextSlice) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "end":
			s.End, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "start":
			s.Start, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}
