// Code generated by lexgen. DO NOT EDIT.

package bsky

import (
	"context"
	lextypes "github.com/jcalabro/atmos/api/lextypes"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/atmos/xrpc"
	"github.com/jcalabro/gt"
)

// Precomputed JSON key tokens for FeedGetQuotes_Output.
var (
	jsonKey_FeedGetQuotes_Output_dollar_type = []byte("\"$type\":")
	jsonKey_FeedGetQuotes_Output_cid         = []byte("\"cid\":")
	jsonKey_FeedGetQuotes_Output_cursor      = []byte("\"cursor\":")
	jsonKey_FeedGetQuotes_Output_posts       = []byte("\"posts\":")
	jsonKey_FeedGetQuotes_Output_uri         = []byte("\"uri\":")
)

func (s *FeedGetQuotes_Output) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *FeedGetQuotes_Output) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_FeedGetQuotes_Output_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if s.CID.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_FeedGetQuotes_Output_cid...)
		buf = cbor.AppendJSONString(buf, s.CID.Val())
		first = false
	}
	if s.Cursor.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_FeedGetQuotes_Output_cursor...)
		buf = cbor.AppendJSONString(buf, s.Cursor.Val())
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_FeedGetQuotes_Output_posts...)
	buf = append(buf, '[')
	for i, item := range s.Posts {
		if i > 0 {
			buf = append(buf, ',')
		}
		var err error
		buf, err = item.AppendJSON(buf)
		if err != nil {
			return nil, err
		}
	}
	buf = append(buf, ']')
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_FeedGetQuotes_Output_uri...)
	buf = cbor.AppendJSONString(buf, s.URI)
	first = false
	for _, ef := range s.extraJSON {
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *FeedGetQuotes_Output) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *FeedGetQuotes_Output) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extraJSON = nil
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "cid":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v string
				v, pos, err = cbor.ReadJSONString(data, pos)
				if err != nil {
					return 0, err
				}
				s.CID = gt.Some(v)
			}
		case "cursor":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v string
				v, pos, err = cbor.ReadJSONString(data, pos)
				if err != nil {
					return 0, err
				}
				s.Cursor = gt.Some(v)
			}
		case "posts":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.Posts = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem FeedDefs_PostView
					pos, err = elem.UnmarshalJSONAt(data, pos)
					if err != nil {
						return 0, err
					}
					s.Posts = append(s.Posts, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case "uri":
			s.URI, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extraJSON = append(s.extraJSON, lextypes.ExtraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...)})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for FeedGetQuotes_Output.
var (
	cborKey_FeedGetQuotes_Output_cid         = cbor.AppendTextKey(nil, "cid")
	cborKey_FeedGetQuotes_Output_uri         = cbor.AppendTextKey(nil, "uri")
	cborKey_FeedGetQuotes_Output_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_FeedGetQuotes_Output_posts       = cbor.AppendTextKey(nil, "posts")
	cborKey_FeedGetQuotes_Output_cursor      = cbor.AppendTextKey(nil, "cursor")
)

func (s *FeedGetQuotes_Output) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *FeedGetQuotes_Output) AppendCBOR(buf []byte) ([]byte, error) {
	n := 2 + len(s.extraCBOR)
	if s.CID.HasVal() {
		n++
	}
	if s.LexiconTypeID != "" {
		n++
	}
	if s.Cursor.HasVal() {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	ei := 0
	ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "cid", buf)
	if s.CID.HasVal() {
		buf = append(buf, cborKey_FeedGetQuotes_Output_cid...)
		buf = cbor.AppendText(buf, s.CID.Val())
	}
	ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "uri", buf)
	buf = append(buf, cborKey_FeedGetQuotes_Output_uri...)
	buf = cbor.AppendText(buf, s.URI)
	ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "$type", buf)
	if s.LexiconTypeID != "" {
		buf = append(buf, cborKey_FeedGetQuotes_Output_dollar_type...)
		buf = cbor.AppendText(buf, s.LexiconTypeID)
	}
	ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "posts", buf)
	buf = append(buf, cborKey_FeedGetQuotes_Output_posts...)
	buf = cbor.AppendArrayHeader(buf, uint64(len(s.Posts)))
	for _, item := range s.Posts {
		var err error
		buf, err = item.AppendCBOR(buf)
		if err != nil {
			return nil, err
		}
	}
	ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "cursor", buf)
	if s.Cursor.HasVal() {
		buf = append(buf, cborKey_FeedGetQuotes_Output_cursor...)
		buf = cbor.AppendText(buf, s.Cursor.Val())
	}
	_, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "", buf)
	return buf, nil
}

func (s *FeedGetQuotes_Output) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *FeedGetQuotes_Output) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extraCBOR = nil
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 3:
			if string(data[keyStart:keyEnd]) == "cid" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v string
					v, pos, err = cbor.ReadText(data, pos)
					if err != nil {
						return 0, err
					}
					s.CID = gt.Some(v)
				}
			} else if string(data[keyStart:keyEnd]) == "uri" {
				s.URI, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
			}
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "posts" {
				{
					arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
					if err != nil {
						return 0, err
					}
					pos = newPos
					s.Posts = make([]FeedDefs_PostView, arrLen)
					for idx := range arrLen {
						pos, err = s.Posts[idx].UnmarshalCBORAt(data, pos)
						if err != nil {
							return 0, err
						}
					}
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
			}
		case 6:
			if string(data[keyStart:keyEnd]) == "cursor" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v string
					v, pos, err = cbor.ReadText(data, pos)
					if err != nil {
						return 0, err
					}
					s.Cursor = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
		}
	}
	return pos, nil
}

type FeedGetQuotes_Output struct {
	LexiconTypeID string              `json:"$type,omitempty"`
	CID           gt.Option[string]   `json:"cid,omitzero"`
	Cursor        gt.Option[string]   `json:"cursor,omitzero"`
	Posts         []FeedDefs_PostView `json:"posts"`
	URI           string              `json:"uri"`

	// extraJSON and extraCBOR preserve unknown fields for same-format round-trips.
	extraJSON []lextypes.ExtraField
	extraCBOR []lextypes.ExtraField
}

// FeedGetQuotes calls the XRPC query "app.bsky.feed.getQuotes".
//
// Get a list of quotes for a given post.
func FeedGetQuotes(ctx context.Context, c *xrpc.Client, cid string, cursor string, limit int64, uri string) (*FeedGetQuotes_Output, error) {
	params := map[string]any{}
	if cid != "" {
		params["cid"] = cid
	}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	params["uri"] = uri
	var out FeedGetQuotes_Output
	return &out, c.Query(ctx, "app.bsky.feed.getQuotes", params, &out)
}
