// Code generated by lexgen. DO NOT EDIT.

package bsky

import (
	"encoding/json"
	"fmt"
	"github.com/jcalabro/gt"
	comatproto "github.com/jcalabro/atmos/api/comatproto"
	lextypes "github.com/jcalabro/atmos/api/lextypes"
	"github.com/jcalabro/atmos/cbor"
)

const (
	NSIDFeedGenerator = "app.bsky.feed.generator" // Record declaring of the existence of a feed generator, and containing metadata about it. The reco...

)

// FeedGenerator is a "app.bsky.feed.generator" record.
//
// Record declaring of the existence of a feed generator, and containing metadata about it. The record can exist in any repository.
type FeedGenerator struct {
	LexiconTypeID       string                          `json:"$type,omitempty" cborgen:"$type,const=app.bsky.feed.generator"`
	AcceptsInteractions gt.Option[bool]                 `json:"acceptsInteractions,omitzero"` // Declaration that a feed accepts feedback interactions from a client through app.bsky.feed.sendInt...
	Avatar              gt.Option[lextypes.LexBlob]     `json:"avatar,omitzero"`
	ContentMode         gt.Option[string]               `json:"contentMode,omitzero"`
	CreatedAt           string                          `json:"createdAt"`
	Description         gt.Option[string]               `json:"description,omitzero"`
	DescriptionFacets   []RichtextFacet                 `json:"descriptionFacets,omitempty"`
	DID                 string                          `json:"did"`
	DisplayName         string                          `json:"displayName"`
	Labels              gt.Option[FeedGenerator_Labels] `json:"labels,omitzero"` // Self-label values
}

// FeedGenerator_Labels is a union type.
type FeedGenerator_Labels struct {
	LabelDefs_SelfLabels gt.Ref[comatproto.LabelDefs_SelfLabels]
	Unknown              gt.Ref[lextypes.UnknownUnionVariant]
}

func (u FeedGenerator_Labels) MarshalJSON() ([]byte, error) {
	return u.AppendJSON(make([]byte, 0, 256))
}

func (u FeedGenerator_Labels) AppendJSON(buf []byte) ([]byte, error) {
	if u.LabelDefs_SelfLabels.HasVal() {
		v := u.LabelDefs_SelfLabels.Val()
		v.LexiconTypeID = "com.atproto.label.defs#selfLabels"
		return v.AppendJSON(buf)
	}
	if u.Unknown.HasVal() {
		return append(buf, u.Unknown.Val().Raw...), nil
	}
	return nil, fmt.Errorf("cannot marshal empty union FeedGenerator_Labels")
}

func (u *FeedGenerator_Labels) UnmarshalJSON(data []byte) error {
	_, err := u.UnmarshalJSONAt(data, 0)
	return err
}

func (u *FeedGenerator_Labels) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	endPos, err := cbor.SkipJSONValue(data, pos)
	if err != nil {
		return 0, err
	}
	typ, err := cbor.PeekJSONType(data[pos:endPos])
	if err != nil {
		return 0, err
	}
	switch typ {
	case "com.atproto.label.defs#selfLabels":
		var v comatproto.LabelDefs_SelfLabels
		endPos, err = v.UnmarshalJSONAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.LabelDefs_SelfLabels = gt.SomeRef(v)
		return endPos, nil
	default:
		u.Unknown = gt.SomeRef(lextypes.UnknownUnionVariant{Type: typ, Raw: json.RawMessage(data[pos:endPos])})
		return endPos, nil
	}
}

func (u FeedGenerator_Labels) MarshalCBOR() ([]byte, error) {
	return u.AppendCBOR(make([]byte, 0, 256))
}

func (u FeedGenerator_Labels) AppendCBOR(buf []byte) ([]byte, error) {
	if u.LabelDefs_SelfLabels.HasVal() {
		v := u.LabelDefs_SelfLabels.Val()
		v.LexiconTypeID = "com.atproto.label.defs#selfLabels"
		return v.AppendCBOR(buf)
	}
	if u.Unknown.HasVal() {
		return append(buf, u.Unknown.Val().RawCBOR...), nil
	}
	return nil, fmt.Errorf("cannot marshal empty union FeedGenerator_Labels")
}

func (u *FeedGenerator_Labels) UnmarshalCBOR(data []byte) error {
	_, err := u.UnmarshalCBORAt(data, 0)
	return err
}

func (u *FeedGenerator_Labels) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	typ, err := cbor.PeekTypeAt(data, pos)
	if err != nil {
		return 0, err
	}
	switch typ {
	case "com.atproto.label.defs#selfLabels":
		var v comatproto.LabelDefs_SelfLabels
		pos, err = v.UnmarshalCBORAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.LabelDefs_SelfLabels = gt.SomeRef(v)
		return pos, nil
	default:
		startPos := pos
		pos, err = cbor.SkipValue(data, pos)
		if err != nil {
			return 0, err
		}
		raw := make([]byte, pos-startPos)
		copy(raw, data[startPos:pos])
		u.Unknown = gt.SomeRef(lextypes.UnknownUnionVariant{Type: typ, RawCBOR: raw})
		return pos, nil
	}
}

// Precomputed CBOR key tokens for FeedGenerator.
var (
	cborKey_FeedGenerator_did                 = cbor.AppendTextKey(nil, "did")
	cborKey_FeedGenerator_dollar_type         = cbor.AppendTextKey(nil, "$type")
	cborKey_FeedGenerator_avatar              = cbor.AppendTextKey(nil, "avatar")
	cborKey_FeedGenerator_labels              = cbor.AppendTextKey(nil, "labels")
	cborKey_FeedGenerator_createdAt           = cbor.AppendTextKey(nil, "createdAt")
	cborKey_FeedGenerator_contentMode         = cbor.AppendTextKey(nil, "contentMode")
	cborKey_FeedGenerator_description         = cbor.AppendTextKey(nil, "description")
	cborKey_FeedGenerator_displayName         = cbor.AppendTextKey(nil, "displayName")
	cborKey_FeedGenerator_descriptionFacets   = cbor.AppendTextKey(nil, "descriptionFacets")
	cborKey_FeedGenerator_acceptsInteractions = cbor.AppendTextKey(nil, "acceptsInteractions")
)

func (s *FeedGenerator) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *FeedGenerator) AppendCBOR(buf []byte) ([]byte, error) {
	n := 4
	if s.Avatar.HasVal() {
		n++
	}
	if s.Labels.HasVal() {
		n++
	}
	if s.ContentMode.HasVal() {
		n++
	}
	if s.Description.HasVal() {
		n++
	}
	if len(s.DescriptionFacets) > 0 {
		n++
	}
	if s.AcceptsInteractions.HasVal() {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	buf = append(buf, cborKey_FeedGenerator_did...)
	buf = cbor.AppendText(buf, s.DID)
	buf = append(buf, cborKey_FeedGenerator_dollar_type...)
	buf = cbor.AppendText(buf, s.LexiconTypeID)
	if s.Avatar.HasVal() {
		buf = append(buf, cborKey_FeedGenerator_avatar...)
		{
			v := s.Avatar.Val()
			{
				var err error
				buf, err = v.AppendCBOR(buf)
				if err != nil {
					return nil, err
				}
			}
		}
	}
	if s.Labels.HasVal() {
		buf = append(buf, cborKey_FeedGenerator_labels...)
		{
			v := s.Labels.Val()
			{
				var err error
				buf, err = v.AppendCBOR(buf)
				if err != nil {
					return nil, err
				}
			}
		}
	}
	buf = append(buf, cborKey_FeedGenerator_createdAt...)
	buf = cbor.AppendText(buf, s.CreatedAt)
	if s.ContentMode.HasVal() {
		buf = append(buf, cborKey_FeedGenerator_contentMode...)
		buf = cbor.AppendText(buf, s.ContentMode.Val())
	}
	if s.Description.HasVal() {
		buf = append(buf, cborKey_FeedGenerator_description...)
		buf = cbor.AppendText(buf, s.Description.Val())
	}
	buf = append(buf, cborKey_FeedGenerator_displayName...)
	buf = cbor.AppendText(buf, s.DisplayName)
	if len(s.DescriptionFacets) > 0 {
		buf = append(buf, cborKey_FeedGenerator_descriptionFacets...)
		buf = cbor.AppendArrayHeader(buf, uint64(len(s.DescriptionFacets)))
		for _, item := range s.DescriptionFacets {
			var err error
			buf, err = item.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
	}
	if s.AcceptsInteractions.HasVal() {
		buf = append(buf, cborKey_FeedGenerator_acceptsInteractions...)
		buf = cbor.AppendBool(buf, s.AcceptsInteractions.Val())
	}
	return buf, nil
}

func (s *FeedGenerator) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *FeedGenerator) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		key, newPos, err := cbor.ReadText(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch key {
		case "did":
			s.DID, pos, err = cbor.ReadText(data, pos)
			if err != nil {
				return 0, err
			}
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
			if err != nil {
				return 0, err
			}
		case "avatar":
			if cbor.IsNull(data, pos) {
				pos++
			} else {
				var v lextypes.LexBlob
				pos, err = v.UnmarshalCBORAt(data, pos)
				if err != nil {
					return 0, err
				}
				s.Avatar = gt.Some(v)
			}
		case "labels":
			if cbor.IsNull(data, pos) {
				pos++
			} else {
				var v FeedGenerator_Labels
				pos, err = v.UnmarshalCBORAt(data, pos)
				if err != nil {
					return 0, err
				}
				s.Labels = gt.Some(v)
			}
		case "createdAt":
			s.CreatedAt, pos, err = cbor.ReadText(data, pos)
			if err != nil {
				return 0, err
			}
		case "contentMode":
			if cbor.IsNull(data, pos) {
				pos++
			} else {
				var v string
				v, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
				s.ContentMode = gt.Some(v)
			}
		case "description":
			if cbor.IsNull(data, pos) {
				pos++
			} else {
				var v string
				v, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
				s.Description = gt.Some(v)
			}
		case "displayName":
			s.DisplayName, pos, err = cbor.ReadText(data, pos)
			if err != nil {
				return 0, err
			}
		case "descriptionFacets":
			{
				arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
				if err != nil {
					return 0, err
				}
				pos = newPos
				s.DescriptionFacets = make([]RichtextFacet, arrLen)
				for idx := range arrLen {
					pos, err = s.DescriptionFacets[idx].UnmarshalCBORAt(data, pos)
					if err != nil {
						return 0, err
					}
				}
			}
		case "acceptsInteractions":
			if cbor.IsNull(data, pos) {
				pos++
			} else {
				var v bool
				v, pos, err = cbor.ReadBool(data, pos)
				if err != nil {
					return 0, err
				}
				s.AcceptsInteractions = gt.Some(v)
			}
		default:
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
	}
	return pos, nil
}

// Precomputed JSON key tokens for FeedGenerator.
var (
	jsonKey_FeedGenerator_dollar_type         = []byte("\"$type\":")
	jsonKey_FeedGenerator_acceptsInteractions = []byte("\"acceptsInteractions\":")
	jsonKey_FeedGenerator_avatar              = []byte("\"avatar\":")
	jsonKey_FeedGenerator_contentMode         = []byte("\"contentMode\":")
	jsonKey_FeedGenerator_createdAt           = []byte("\"createdAt\":")
	jsonKey_FeedGenerator_description         = []byte("\"description\":")
	jsonKey_FeedGenerator_descriptionFacets   = []byte("\"descriptionFacets\":")
	jsonKey_FeedGenerator_did                 = []byte("\"did\":")
	jsonKey_FeedGenerator_displayName         = []byte("\"displayName\":")
	jsonKey_FeedGenerator_labels              = []byte("\"labels\":")
)

func (s *FeedGenerator) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *FeedGenerator) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_FeedGenerator_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if s.AcceptsInteractions.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_FeedGenerator_acceptsInteractions...)
		buf = cbor.AppendJSONBool(buf, s.AcceptsInteractions.Val())
		first = false
	}
	if s.Avatar.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_FeedGenerator_avatar...)
		{
			v := s.Avatar.Val()
			{
				var err error
				buf, err = v.AppendJSON(buf)
				if err != nil {
					return nil, err
				}
			}
		}
		first = false
	}
	if s.ContentMode.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_FeedGenerator_contentMode...)
		buf = cbor.AppendJSONString(buf, s.ContentMode.Val())
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_FeedGenerator_createdAt...)
	buf = cbor.AppendJSONString(buf, s.CreatedAt)
	first = false
	if s.Description.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_FeedGenerator_description...)
		buf = cbor.AppendJSONString(buf, s.Description.Val())
		first = false
	}
	if len(s.DescriptionFacets) > 0 {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_FeedGenerator_descriptionFacets...)
		buf = append(buf, '[')
		for i, item := range s.DescriptionFacets {
			if i > 0 {
				buf = append(buf, ',')
			}
			var err error
			buf, err = item.AppendJSON(buf)
			if err != nil {
				return nil, err
			}
		}
		buf = append(buf, ']')
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_FeedGenerator_did...)
	buf = cbor.AppendJSONString(buf, s.DID)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_FeedGenerator_displayName...)
	buf = cbor.AppendJSONString(buf, s.DisplayName)
	first = false
	if s.Labels.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_FeedGenerator_labels...)
		{
			v := s.Labels.Val()
			{
				var err error
				buf, err = v.AppendJSON(buf)
				if err != nil {
					return nil, err
				}
			}
		}
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *FeedGenerator) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *FeedGenerator) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "acceptsInteractions":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v bool
				v, pos, err = cbor.ReadJSONBool(data, pos)
				if err != nil {
					return 0, err
				}
				s.AcceptsInteractions = gt.Some(v)
			}
		case "avatar":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v lextypes.LexBlob
				pos, err = v.UnmarshalJSONAt(data, pos)
				if err != nil {
					return 0, err
				}
				s.Avatar = gt.Some(v)
			}
		case "contentMode":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v string
				v, pos, err = cbor.ReadJSONString(data, pos)
				if err != nil {
					return 0, err
				}
				s.ContentMode = gt.Some(v)
			}
		case "createdAt":
			s.CreatedAt, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "description":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v string
				v, pos, err = cbor.ReadJSONString(data, pos)
				if err != nil {
					return 0, err
				}
				s.Description = gt.Some(v)
			}
		case "descriptionFacets":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.DescriptionFacets = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem RichtextFacet
					pos, err = elem.UnmarshalJSONAt(data, pos)
					if err != nil {
						return 0, err
					}
					s.DescriptionFacets = append(s.DescriptionFacets, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case "did":
			s.DID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "displayName":
			s.DisplayName, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "labels":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v FeedGenerator_Labels
				pos, err = v.UnmarshalJSONAt(data, pos)
				if err != nil {
					return 0, err
				}
				s.Labels = gt.Some(v)
			}
		default:
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}
