// Code generated by lexgen. DO NOT EDIT.

package bsky

import (
	comatproto "github.com/jcalabro/atmos/api/comatproto"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/gt"
)

const (
	NSIDFeedLike = "app.bsky.feed.like" // Record declaring a 'like' of a piece of subject content.

)

// FeedLike is a "app.bsky.feed.like" record.
//
// Record declaring a 'like' of a piece of subject content.
type FeedLike struct {
	LexiconTypeID string                              `json:"$type,omitempty" cborgen:"$type,const=app.bsky.feed.like"`
	CreatedAt     string                              `json:"createdAt"`
	Subject       comatproto.RepoStrongRef            `json:"subject"`
	Via           gt.Option[comatproto.RepoStrongRef] `json:"via,omitzero"`
}

// Precomputed CBOR key tokens for FeedLike.
var (
	cborKey_FeedLike_via         = cbor.AppendTextKey(nil, "via")
	cborKey_FeedLike_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_FeedLike_subject     = cbor.AppendTextKey(nil, "subject")
	cborKey_FeedLike_createdAt   = cbor.AppendTextKey(nil, "createdAt")
)

func (s *FeedLike) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *FeedLike) AppendCBOR(buf []byte) ([]byte, error) {
	n := 3
	if s.Via.HasVal() {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if s.Via.HasVal() {
		buf = append(buf, cborKey_FeedLike_via...)
		{
			v := s.Via.Val()
			{
				var err error
				buf, err = v.AppendCBOR(buf)
				if err != nil {
					return nil, err
				}
			}
		}
	}
	buf = append(buf, cborKey_FeedLike_dollar_type...)
	buf = cbor.AppendText(buf, s.LexiconTypeID)
	buf = append(buf, cborKey_FeedLike_subject...)
	{
		var err error
		buf, err = s.Subject.AppendCBOR(buf)
		if err != nil {
			return nil, err
		}
	}
	buf = append(buf, cborKey_FeedLike_createdAt...)
	buf = cbor.AppendText(buf, s.CreatedAt)
	return buf, nil
}

func (s *FeedLike) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *FeedLike) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		key, newPos, err := cbor.ReadText(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch key {
		case "via":
			if cbor.IsNull(data, pos) {
				pos++
			} else {
				var v comatproto.RepoStrongRef
				pos, err = v.UnmarshalCBORAt(data, pos)
				if err != nil {
					return 0, err
				}
				s.Via = gt.Some(v)
			}
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
			if err != nil {
				return 0, err
			}
		case "subject":
			pos, err = s.Subject.UnmarshalCBORAt(data, pos)
			if err != nil {
				return 0, err
			}
		case "createdAt":
			s.CreatedAt, pos, err = cbor.ReadText(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
	}
	return pos, nil
}

// Precomputed JSON key tokens for FeedLike.
var (
	jsonKey_FeedLike_dollar_type = []byte("\"$type\":")
	jsonKey_FeedLike_createdAt   = []byte("\"createdAt\":")
	jsonKey_FeedLike_subject     = []byte("\"subject\":")
	jsonKey_FeedLike_via         = []byte("\"via\":")
)

func (s *FeedLike) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *FeedLike) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_FeedLike_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_FeedLike_createdAt...)
	buf = cbor.AppendJSONString(buf, s.CreatedAt)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_FeedLike_subject...)
	{
		var err error
		buf, err = s.Subject.AppendJSON(buf)
		if err != nil {
			return nil, err
		}
	}
	first = false
	if s.Via.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_FeedLike_via...)
		{
			v := s.Via.Val()
			{
				var err error
				buf, err = v.AppendJSON(buf)
				if err != nil {
					return nil, err
				}
			}
		}
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *FeedLike) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *FeedLike) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "createdAt":
			s.CreatedAt, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "subject":
			pos, err = s.Subject.UnmarshalJSONAt(data, pos)
			if err != nil {
				return 0, err
			}
		case "via":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v comatproto.RepoStrongRef
				pos, err = v.UnmarshalJSONAt(data, pos)
				if err != nil {
					return 0, err
				}
				s.Via = gt.Some(v)
			}
		default:
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}
