// Code generated by lexgen. DO NOT EDIT.

package bsky

import (
	"context"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/atmos/xrpc"
	"github.com/jcalabro/gt"
)

// Precomputed JSON key tokens for GraphGetStarterPacksWithMembership_Output.
var (
	jsonKey_GraphGetStarterPacksWithMembership_Output_dollar_type                = []byte("\"$type\":")
	jsonKey_GraphGetStarterPacksWithMembership_Output_cursor                     = []byte("\"cursor\":")
	jsonKey_GraphGetStarterPacksWithMembership_Output_starterPacksWithMembership = []byte("\"starterPacksWithMembership\":")
)

func (s *GraphGetStarterPacksWithMembership_Output) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *GraphGetStarterPacksWithMembership_Output) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_GraphGetStarterPacksWithMembership_Output_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if s.Cursor.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_GraphGetStarterPacksWithMembership_Output_cursor...)
		buf = cbor.AppendJSONString(buf, s.Cursor.Val())
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_GraphGetStarterPacksWithMembership_Output_starterPacksWithMembership...)
	buf = append(buf, '[')
	for i, item := range s.StarterPacksWithMembership {
		if i > 0 {
			buf = append(buf, ',')
		}
		var err error
		buf, err = item.AppendJSON(buf)
		if err != nil {
			return nil, err
		}
	}
	buf = append(buf, ']')
	first = false
	buf = append(buf, '}')
	return buf, nil
}

func (s *GraphGetStarterPacksWithMembership_Output) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *GraphGetStarterPacksWithMembership_Output) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "cursor":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v string
				v, pos, err = cbor.ReadJSONString(data, pos)
				if err != nil {
					return 0, err
				}
				s.Cursor = gt.Some(v)
			}
		case "starterPacksWithMembership":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.StarterPacksWithMembership = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem GraphGetStarterPacksWithMembership_StarterPackWithMembership
					pos, err = elem.UnmarshalJSONAt(data, pos)
					if err != nil {
						return 0, err
					}
					s.StarterPacksWithMembership = append(s.StarterPacksWithMembership, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		default:
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for GraphGetStarterPacksWithMembership_Output.
var (
	cborKey_GraphGetStarterPacksWithMembership_Output_dollar_type                = cbor.AppendTextKey(nil, "$type")
	cborKey_GraphGetStarterPacksWithMembership_Output_cursor                     = cbor.AppendTextKey(nil, "cursor")
	cborKey_GraphGetStarterPacksWithMembership_Output_starterPacksWithMembership = cbor.AppendTextKey(nil, "starterPacksWithMembership")
)

func (s *GraphGetStarterPacksWithMembership_Output) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *GraphGetStarterPacksWithMembership_Output) AppendCBOR(buf []byte) ([]byte, error) {
	n := 1
	if s.LexiconTypeID != "" {
		n++
	}
	if s.Cursor.HasVal() {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if s.LexiconTypeID != "" {
		buf = append(buf, cborKey_GraphGetStarterPacksWithMembership_Output_dollar_type...)
		buf = cbor.AppendText(buf, s.LexiconTypeID)
	}
	if s.Cursor.HasVal() {
		buf = append(buf, cborKey_GraphGetStarterPacksWithMembership_Output_cursor...)
		buf = cbor.AppendText(buf, s.Cursor.Val())
	}
	buf = append(buf, cborKey_GraphGetStarterPacksWithMembership_Output_starterPacksWithMembership...)
	buf = cbor.AppendArrayHeader(buf, uint64(len(s.StarterPacksWithMembership)))
	for _, item := range s.StarterPacksWithMembership {
		var err error
		buf, err = item.AppendCBOR(buf)
		if err != nil {
			return nil, err
		}
	}
	return buf, nil
}

func (s *GraphGetStarterPacksWithMembership_Output) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *GraphGetStarterPacksWithMembership_Output) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case 6:
			if string(data[keyStart:keyEnd]) == "cursor" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v string
					v, pos, err = cbor.ReadText(data, pos)
					if err != nil {
						return 0, err
					}
					s.Cursor = gt.Some(v)
				}
			} else {
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case 26:
			if string(data[keyStart:keyEnd]) == "starterPacksWithMembership" {
				{
					arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
					if err != nil {
						return 0, err
					}
					pos = newPos
					s.StarterPacksWithMembership = make([]GraphGetStarterPacksWithMembership_StarterPackWithMembership, arrLen)
					for idx := range arrLen {
						pos, err = s.StarterPacksWithMembership[idx].UnmarshalCBORAt(data, pos)
						if err != nil {
							return 0, err
						}
					}
				}
			} else {
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
			}
		default:
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
	}
	return pos, nil
}

type GraphGetStarterPacksWithMembership_Output struct {
	LexiconTypeID              string                                                         `json:"$type,omitempty"`
	Cursor                     gt.Option[string]                                              `json:"cursor,omitzero"`
	StarterPacksWithMembership []GraphGetStarterPacksWithMembership_StarterPackWithMembership `json:"starterPacksWithMembership"`
}

// GraphGetStarterPacksWithMembership calls the XRPC query "app.bsky.graph.getStarterPacksWithMembership".
//
// Enumerates the starter packs created by the session user, and includes membership information about `actor` in those starter packs. Requires auth.
func GraphGetStarterPacksWithMembership(ctx context.Context, c *xrpc.Client, actor string, cursor string, limit int64) (*GraphGetStarterPacksWithMembership_Output, error) {
	params := map[string]any{}
	params["actor"] = actor
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	var out GraphGetStarterPacksWithMembership_Output
	return &out, c.Query(ctx, "app.bsky.graph.getStarterPacksWithMembership", params, &out)
}

// GraphGetStarterPacksWithMembership_StarterPackWithMembership is a "starterPackWithMembership" in the app.bsky.graph.getStarterPacksWithMembership schema.
//
// A starter pack and an optional list item indicating membership of a target user to that starter pack.
type GraphGetStarterPacksWithMembership_StarterPackWithMembership struct {
	LexiconTypeID string                            `json:"$type,omitempty"`
	ListItem      gt.Option[GraphDefs_ListItemView] `json:"listItem,omitzero"`
	StarterPack   GraphDefs_StarterPackView         `json:"starterPack"`
}

// Precomputed CBOR key tokens for GraphGetStarterPacksWithMembership_StarterPackWithMembership.
var (
	cborKey_GraphGetStarterPacksWithMembership_StarterPackWithMembership_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_GraphGetStarterPacksWithMembership_StarterPackWithMembership_listItem    = cbor.AppendTextKey(nil, "listItem")
	cborKey_GraphGetStarterPacksWithMembership_StarterPackWithMembership_starterPack = cbor.AppendTextKey(nil, "starterPack")
)

func (s *GraphGetStarterPacksWithMembership_StarterPackWithMembership) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *GraphGetStarterPacksWithMembership_StarterPackWithMembership) AppendCBOR(buf []byte) ([]byte, error) {
	n := 1
	if s.LexiconTypeID != "" {
		n++
	}
	if s.ListItem.HasVal() {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if s.LexiconTypeID != "" {
		buf = append(buf, cborKey_GraphGetStarterPacksWithMembership_StarterPackWithMembership_dollar_type...)
		buf = cbor.AppendText(buf, s.LexiconTypeID)
	}
	if s.ListItem.HasVal() {
		buf = append(buf, cborKey_GraphGetStarterPacksWithMembership_StarterPackWithMembership_listItem...)
		{
			v := s.ListItem.Val()
			{
				var err error
				buf, err = v.AppendCBOR(buf)
				if err != nil {
					return nil, err
				}
			}
		}
	}
	buf = append(buf, cborKey_GraphGetStarterPacksWithMembership_StarterPackWithMembership_starterPack...)
	{
		var err error
		buf, err = s.StarterPack.AppendCBOR(buf)
		if err != nil {
			return nil, err
		}
	}
	return buf, nil
}

func (s *GraphGetStarterPacksWithMembership_StarterPackWithMembership) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *GraphGetStarterPacksWithMembership_StarterPackWithMembership) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case 8:
			if string(data[keyStart:keyEnd]) == "listItem" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v GraphDefs_ListItemView
					pos, err = v.UnmarshalCBORAt(data, pos)
					if err != nil {
						return 0, err
					}
					s.ListItem = gt.Some(v)
				}
			} else {
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case 11:
			if string(data[keyStart:keyEnd]) == "starterPack" {
				pos, err = s.StarterPack.UnmarshalCBORAt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
			}
		default:
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
	}
	return pos, nil
}

// Precomputed JSON key tokens for GraphGetStarterPacksWithMembership_StarterPackWithMembership.
var (
	jsonKey_GraphGetStarterPacksWithMembership_StarterPackWithMembership_dollar_type = []byte("\"$type\":")
	jsonKey_GraphGetStarterPacksWithMembership_StarterPackWithMembership_listItem    = []byte("\"listItem\":")
	jsonKey_GraphGetStarterPacksWithMembership_StarterPackWithMembership_starterPack = []byte("\"starterPack\":")
)

func (s *GraphGetStarterPacksWithMembership_StarterPackWithMembership) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *GraphGetStarterPacksWithMembership_StarterPackWithMembership) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_GraphGetStarterPacksWithMembership_StarterPackWithMembership_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if s.ListItem.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_GraphGetStarterPacksWithMembership_StarterPackWithMembership_listItem...)
		{
			v := s.ListItem.Val()
			{
				var err error
				buf, err = v.AppendJSON(buf)
				if err != nil {
					return nil, err
				}
			}
		}
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_GraphGetStarterPacksWithMembership_StarterPackWithMembership_starterPack...)
	{
		var err error
		buf, err = s.StarterPack.AppendJSON(buf)
		if err != nil {
			return nil, err
		}
	}
	first = false
	buf = append(buf, '}')
	return buf, nil
}

func (s *GraphGetStarterPacksWithMembership_StarterPackWithMembership) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *GraphGetStarterPacksWithMembership_StarterPackWithMembership) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "listItem":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v GraphDefs_ListItemView
				pos, err = v.UnmarshalJSONAt(data, pos)
				if err != nil {
					return 0, err
				}
				s.ListItem = gt.Some(v)
			}
		case "starterPack":
			pos, err = s.StarterPack.UnmarshalJSONAt(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}
