// Code generated by lexgen. DO NOT EDIT.

package bsky

import (
	"github.com/jcalabro/atmos/cbor"
)

const (
	NSIDGraphReferencelistoptout = "app.bsky.graph.referencelistoptout" // Record requesting that its author be omitted from the public presentation of a reference list. Th...

)

// GraphReferencelistoptout is a "app.bsky.graph.referencelistoptout" record.
//
// Record requesting that its author be omitted from the public presentation of a reference list. This record is only enforced when the subject list's current purpose is app.bsky.graph.defs#referencelist. AppView indexes at most one record per actor and list pair, and ignores duplicate records.
type GraphReferencelistoptout struct {
	LexiconTypeID string `json:"$type,omitempty" cborgen:"$type,const=app.bsky.graph.referencelistoptout"`
	CreatedAt     string `json:"createdAt"`
	Subject       string `json:"subject"` // Canonical, DID-based AT URI of the app.bsky.graph.list record from which the author requests omis...

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// Precomputed CBOR key tokens for GraphReferencelistoptout.
var (
	cborKey_GraphReferencelistoptout_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_GraphReferencelistoptout_subject     = cbor.AppendTextKey(nil, "subject")
	cborKey_GraphReferencelistoptout_createdAt   = cbor.AppendTextKey(nil, "createdAt")
)

func (s *GraphReferencelistoptout) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *GraphReferencelistoptout) AppendCBOR(buf []byte) ([]byte, error) {
	buf = cbor.AppendMapHeader(buf, uint64(3+countExtra(s.extra, extraEncodingCBOR)))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		buf = append(buf, cborKey_GraphReferencelistoptout_dollar_type...)
		buf = cbor.AppendText(buf, "app.bsky.graph.referencelistoptout")
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "subject", buf)
		buf = append(buf, cborKey_GraphReferencelistoptout_subject...)
		buf = cbor.AppendText(buf, s.Subject)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "createdAt", buf)
		buf = append(buf, cborKey_GraphReferencelistoptout_createdAt...)
		buf = cbor.AppendText(buf, s.CreatedAt)
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		buf = append(buf, cborKey_GraphReferencelistoptout_dollar_type...)
		buf = cbor.AppendText(buf, "app.bsky.graph.referencelistoptout")
		buf = append(buf, cborKey_GraphReferencelistoptout_subject...)
		buf = cbor.AppendText(buf, s.Subject)
		buf = append(buf, cborKey_GraphReferencelistoptout_createdAt...)
		buf = cbor.AppendText(buf, s.CreatedAt)
	}
	return buf, nil
}

func (s *GraphReferencelistoptout) UnmarshalCBOR(data []byte) error {
	pos, err := s.UnmarshalCBORAt(data, 0)
	if err != nil {
		return err
	}
	return cbor.CheckTrailingData(pos, len(data))
}

func (s *GraphReferencelistoptout) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	var prevKeyStart, prevKeyEnd int
	keyOrderValid := false
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		if keyOrderValid {
			if err := cbor.CheckMapKeyOrder(data, prevKeyStart, prevKeyEnd, keyStart, keyEnd); err != nil {
				return 0, err
			}
		}
		prevKeyStart, prevKeyEnd = keyStart, keyEnd
		keyOrderValid = true
		pos = newPos
		switch keyEnd - keyStart {
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 7:
			if string(data[keyStart:keyEnd]) == "subject" {
				s.Subject, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 9:
			if string(data[keyStart:keyEnd]) == "createdAt" {
				s.CreatedAt, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

// Precomputed JSON key tokens for GraphReferencelistoptout.
var (
	jsonKey_GraphReferencelistoptout_dollar_type = []byte("\"$type\":")
	jsonKey_GraphReferencelistoptout_createdAt   = []byte("\"createdAt\":")
	jsonKey_GraphReferencelistoptout_subject     = []byte("\"subject\":")
)

func (s *GraphReferencelistoptout) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *GraphReferencelistoptout) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_GraphReferencelistoptout_dollar_type...)
	buf = cbor.AppendJSONString(buf, "app.bsky.graph.referencelistoptout")
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_GraphReferencelistoptout_createdAt...)
	buf = cbor.AppendJSONString(buf, s.CreatedAt)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_GraphReferencelistoptout_subject...)
	buf = cbor.AppendJSONString(buf, s.Subject)
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *GraphReferencelistoptout) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *GraphReferencelistoptout) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "createdAt":
			s.CreatedAt, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "subject":
			s.Subject, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}
