// Code generated by lexgen. DO NOT EDIT.

package bsky

import (
	"github.com/jcalabro/atmos/cbor"
)

const (
	NSIDGraphBlock = "app.bsky.graph.block" // Record declaring a 'block' relationship against another account. NOTE: blocks are public in Blues...

)

// GraphBlock is a "app.bsky.graph.block" record.
//
// Record declaring a 'block' relationship against another account. NOTE: blocks are public in Bluesky; see blog posts for details.
type GraphBlock struct {
	LexiconTypeID string `json:"$type,omitempty" cborgen:"$type,const=app.bsky.graph.block"`
	CreatedAt     string `json:"createdAt"`
	Subject       string `json:"subject"` // DID of the account to be blocked.

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// Precomputed CBOR key tokens for GraphBlock.
var (
	cborKey_GraphBlock_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_GraphBlock_subject     = cbor.AppendTextKey(nil, "subject")
	cborKey_GraphBlock_createdAt   = cbor.AppendTextKey(nil, "createdAt")
)

func (s *GraphBlock) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *GraphBlock) AppendCBOR(buf []byte) ([]byte, error) {
	buf = cbor.AppendMapHeader(buf, uint64(3+countExtra(s.extra, extraEncodingCBOR)))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		buf = append(buf, cborKey_GraphBlock_dollar_type...)
		buf = cbor.AppendText(buf, s.LexiconTypeID)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "subject", buf)
		buf = append(buf, cborKey_GraphBlock_subject...)
		buf = cbor.AppendText(buf, s.Subject)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "createdAt", buf)
		buf = append(buf, cborKey_GraphBlock_createdAt...)
		buf = cbor.AppendText(buf, s.CreatedAt)
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		buf = append(buf, cborKey_GraphBlock_dollar_type...)
		buf = cbor.AppendText(buf, s.LexiconTypeID)
		buf = append(buf, cborKey_GraphBlock_subject...)
		buf = cbor.AppendText(buf, s.Subject)
		buf = append(buf, cborKey_GraphBlock_createdAt...)
		buf = cbor.AppendText(buf, s.CreatedAt)
	}
	return buf, nil
}

func (s *GraphBlock) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *GraphBlock) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 7:
			if string(data[keyStart:keyEnd]) == "subject" {
				s.Subject, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 9:
			if string(data[keyStart:keyEnd]) == "createdAt" {
				s.CreatedAt, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

// Precomputed JSON key tokens for GraphBlock.
var (
	jsonKey_GraphBlock_dollar_type = []byte("\"$type\":")
	jsonKey_GraphBlock_createdAt   = []byte("\"createdAt\":")
	jsonKey_GraphBlock_subject     = []byte("\"subject\":")
)

func (s *GraphBlock) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *GraphBlock) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_GraphBlock_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_GraphBlock_createdAt...)
	buf = cbor.AppendJSONString(buf, s.CreatedAt)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_GraphBlock_subject...)
	buf = cbor.AppendJSONString(buf, s.Subject)
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *GraphBlock) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *GraphBlock) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "createdAt":
			s.CreatedAt, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "subject":
			s.Subject, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}
