// Code generated by lexgen. DO NOT EDIT.

package bsky

import (
	"context"
	"github.com/jcalabro/gt"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/atmos/xrpc"
)

// Error name constants for UnspeccedSearchStarterPacksSkeleton.
const (
	ErrUnspeccedSearchStarterPacksSkeleton_BadQueryString = "BadQueryString"
)

// Precomputed JSON key tokens for UnspeccedSearchStarterPacksSkeleton_Output.
var (
	jsonKey_UnspeccedSearchStarterPacksSkeleton_Output_dollar_type  = []byte("\"$type\":")
	jsonKey_UnspeccedSearchStarterPacksSkeleton_Output_cursor       = []byte("\"cursor\":")
	jsonKey_UnspeccedSearchStarterPacksSkeleton_Output_hitsTotal    = []byte("\"hitsTotal\":")
	jsonKey_UnspeccedSearchStarterPacksSkeleton_Output_starterPacks = []byte("\"starterPacks\":")
)

func (s *UnspeccedSearchStarterPacksSkeleton_Output) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *UnspeccedSearchStarterPacksSkeleton_Output) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_UnspeccedSearchStarterPacksSkeleton_Output_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if s.Cursor.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_UnspeccedSearchStarterPacksSkeleton_Output_cursor...)
		buf = cbor.AppendJSONString(buf, s.Cursor.Val())
		first = false
	}
	if s.HitsTotal.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_UnspeccedSearchStarterPacksSkeleton_Output_hitsTotal...)
		buf = cbor.AppendJSONInt(buf, s.HitsTotal.Val())
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_UnspeccedSearchStarterPacksSkeleton_Output_starterPacks...)
	buf = append(buf, '[')
	for i, item := range s.StarterPacks {
		if i > 0 {
			buf = append(buf, ',')
		}
		var err error
		buf, err = item.AppendJSON(buf)
		if err != nil {
			return nil, err
		}
	}
	buf = append(buf, ']')
	first = false
	buf = append(buf, '}')
	return buf, nil
}

func (s *UnspeccedSearchStarterPacksSkeleton_Output) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *UnspeccedSearchStarterPacksSkeleton_Output) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "cursor":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v string
				v, pos, err = cbor.ReadJSONString(data, pos)
				if err != nil {
					return 0, err
				}
				s.Cursor = gt.Some(v)
			}
		case "hitsTotal":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v int64
				v, pos, err = cbor.ReadJSONInt(data, pos)
				if err != nil {
					return 0, err
				}
				s.HitsTotal = gt.Some(v)
			}
		case "starterPacks":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.StarterPacks = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem UnspeccedDefs_SkeletonSearchStarterPack
					pos, err = elem.UnmarshalJSONAt(data, pos)
					if err != nil {
						return 0, err
					}
					s.StarterPacks = append(s.StarterPacks, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		default:
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for UnspeccedSearchStarterPacksSkeleton_Output.
var (
	cborKey_UnspeccedSearchStarterPacksSkeleton_Output_dollar_type  = cbor.AppendTextKey(nil, "$type")
	cborKey_UnspeccedSearchStarterPacksSkeleton_Output_cursor       = cbor.AppendTextKey(nil, "cursor")
	cborKey_UnspeccedSearchStarterPacksSkeleton_Output_hitsTotal    = cbor.AppendTextKey(nil, "hitsTotal")
	cborKey_UnspeccedSearchStarterPacksSkeleton_Output_starterPacks = cbor.AppendTextKey(nil, "starterPacks")
)

func (s *UnspeccedSearchStarterPacksSkeleton_Output) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *UnspeccedSearchStarterPacksSkeleton_Output) AppendCBOR(buf []byte) ([]byte, error) {
	n := 1
	if s.LexiconTypeID != "" {
		n++
	}
	if s.Cursor.HasVal() {
		n++
	}
	if s.HitsTotal.HasVal() {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if s.LexiconTypeID != "" {
		buf = append(buf, cborKey_UnspeccedSearchStarterPacksSkeleton_Output_dollar_type...)
		buf = cbor.AppendText(buf, s.LexiconTypeID)
	}
	if s.Cursor.HasVal() {
		buf = append(buf, cborKey_UnspeccedSearchStarterPacksSkeleton_Output_cursor...)
		buf = cbor.AppendText(buf, s.Cursor.Val())
	}
	if s.HitsTotal.HasVal() {
		buf = append(buf, cborKey_UnspeccedSearchStarterPacksSkeleton_Output_hitsTotal...)
		buf = cbor.AppendInt(buf, s.HitsTotal.Val())
	}
	buf = append(buf, cborKey_UnspeccedSearchStarterPacksSkeleton_Output_starterPacks...)
	buf = cbor.AppendArrayHeader(buf, uint64(len(s.StarterPacks)))
	for _, item := range s.StarterPacks {
		var err error
		buf, err = item.AppendCBOR(buf)
		if err != nil {
			return nil, err
		}
	}
	return buf, nil
}

func (s *UnspeccedSearchStarterPacksSkeleton_Output) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *UnspeccedSearchStarterPacksSkeleton_Output) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		key, newPos, err := cbor.ReadText(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
			if err != nil {
				return 0, err
			}
		case "cursor":
			if cbor.IsNull(data, pos) {
				pos++
			} else {
				var v string
				v, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
				s.Cursor = gt.Some(v)
			}
		case "hitsTotal":
			if cbor.IsNull(data, pos) {
				pos++
			} else {
				var v int64
				v, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
				s.HitsTotal = gt.Some(v)
			}
		case "starterPacks":
			{
				arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
				if err != nil {
					return 0, err
				}
				pos = newPos
				s.StarterPacks = make([]UnspeccedDefs_SkeletonSearchStarterPack, arrLen)
				for idx := range arrLen {
					pos, err = s.StarterPacks[idx].UnmarshalCBORAt(data, pos)
					if err != nil {
						return 0, err
					}
				}
			}
		default:
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
	}
	return pos, nil
}

type UnspeccedSearchStarterPacksSkeleton_Output struct {
	LexiconTypeID string                                    `json:"$type,omitempty"`
	Cursor        gt.Option[string]                         `json:"cursor,omitzero"`
	HitsTotal     gt.Option[int64]                          `json:"hitsTotal,omitzero"` // Count of search hits. Optional, may be rounded/truncated, and may not be possible to paginate thr...
	StarterPacks  []UnspeccedDefs_SkeletonSearchStarterPack `json:"starterPacks"`
}

// UnspeccedSearchStarterPacksSkeleton calls the XRPC query "app.bsky.unspecced.searchStarterPacksSkeleton".
//
// Backend Starter Pack search, returns only skeleton.
func UnspeccedSearchStarterPacksSkeleton(ctx context.Context, c *xrpc.Client, cursor string, limit int64, q string, viewer string) (*UnspeccedSearchStarterPacksSkeleton_Output, error) {
	params := map[string]any{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	params["q"] = q
	if viewer != "" {
		params["viewer"] = viewer
	}
	var out UnspeccedSearchStarterPacksSkeleton_Output
	return &out, c.Query(ctx, "app.bsky.unspecced.searchStarterPacksSkeleton", params, &out)
}
