// Code generated by lexgen. DO NOT EDIT.

package bsky

import (
	"context"
	lextypes "github.com/jcalabro/atmos/api/lextypes"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/atmos/xrpc"
)

// Precomputed JSON key tokens for UnspeccedGetOnboardingSuggestedStarterPacksSkeleton_Output.
var (
	jsonKey_UnspeccedGetOnboardingSuggestedStarterPacksSkeleton_Output_dollar_type  = []byte("\"$type\":")
	jsonKey_UnspeccedGetOnboardingSuggestedStarterPacksSkeleton_Output_starterPacks = []byte("\"starterPacks\":")
)

func (s *UnspeccedGetOnboardingSuggestedStarterPacksSkeleton_Output) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *UnspeccedGetOnboardingSuggestedStarterPacksSkeleton_Output) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_UnspeccedGetOnboardingSuggestedStarterPacksSkeleton_Output_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_UnspeccedGetOnboardingSuggestedStarterPacksSkeleton_Output_starterPacks...)
	buf = append(buf, '[')
	for i, item := range s.StarterPacks {
		if i > 0 {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, item)
	}
	buf = append(buf, ']')
	first = false
	for _, ef := range s.extraJSON {
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *UnspeccedGetOnboardingSuggestedStarterPacksSkeleton_Output) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *UnspeccedGetOnboardingSuggestedStarterPacksSkeleton_Output) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extraJSON = nil
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "starterPacks":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.StarterPacks = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem string
					elem, pos, err = cbor.ReadJSONString(data, pos)
					if err != nil {
						return 0, err
					}
					s.StarterPacks = append(s.StarterPacks, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extraJSON = append(s.extraJSON, lextypes.ExtraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...)})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for UnspeccedGetOnboardingSuggestedStarterPacksSkeleton_Output.
var (
	cborKey_UnspeccedGetOnboardingSuggestedStarterPacksSkeleton_Output_dollar_type  = cbor.AppendTextKey(nil, "$type")
	cborKey_UnspeccedGetOnboardingSuggestedStarterPacksSkeleton_Output_starterPacks = cbor.AppendTextKey(nil, "starterPacks")
)

func (s *UnspeccedGetOnboardingSuggestedStarterPacksSkeleton_Output) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *UnspeccedGetOnboardingSuggestedStarterPacksSkeleton_Output) AppendCBOR(buf []byte) ([]byte, error) {
	n := 1 + len(s.extraCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	ei := 0
	ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "$type", buf)
	if s.LexiconTypeID != "" {
		buf = append(buf, cborKey_UnspeccedGetOnboardingSuggestedStarterPacksSkeleton_Output_dollar_type...)
		buf = cbor.AppendText(buf, s.LexiconTypeID)
	}
	ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "starterPacks", buf)
	buf = append(buf, cborKey_UnspeccedGetOnboardingSuggestedStarterPacksSkeleton_Output_starterPacks...)
	buf = cbor.AppendArrayHeader(buf, uint64(len(s.StarterPacks)))
	for _, item := range s.StarterPacks {
		buf = cbor.AppendText(buf, item)
	}
	_, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "", buf)
	return buf, nil
}

func (s *UnspeccedGetOnboardingSuggestedStarterPacksSkeleton_Output) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *UnspeccedGetOnboardingSuggestedStarterPacksSkeleton_Output) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extraCBOR = nil
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
			}
		case 12:
			if string(data[keyStart:keyEnd]) == "starterPacks" {
				{
					arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
					if err != nil {
						return 0, err
					}
					pos = newPos
					s.StarterPacks = make([]string, arrLen)
					for idx := range arrLen {
						s.StarterPacks[idx], pos, err = cbor.ReadText(data, pos)
						if err != nil {
							return 0, err
						}
					}
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
		}
	}
	return pos, nil
}

type UnspeccedGetOnboardingSuggestedStarterPacksSkeleton_Output struct {
	LexiconTypeID string   `json:"$type,omitempty"`
	StarterPacks  []string `json:"starterPacks"`

	// extraJSON and extraCBOR preserve unknown fields for same-format round-trips.
	extraJSON []lextypes.ExtraField
	extraCBOR []lextypes.ExtraField
}

// UnspeccedGetOnboardingSuggestedStarterPacksSkeleton calls the XRPC query "app.bsky.unspecced.getOnboardingSuggestedStarterPacksSkeleton".
//
// Get a skeleton of suggested starterpacks for onboarding. Intended to be called and hydrated by app.bsky.unspecced.getOnboardingSuggestedStarterPacks
func UnspeccedGetOnboardingSuggestedStarterPacksSkeleton(ctx context.Context, c *xrpc.Client, limit int64, viewer string) (*UnspeccedGetOnboardingSuggestedStarterPacksSkeleton_Output, error) {
	params := map[string]any{}
	if limit != 0 {
		params["limit"] = limit
	}
	if viewer != "" {
		params["viewer"] = viewer
	}
	var out UnspeccedGetOnboardingSuggestedStarterPacksSkeleton_Output
	return &out, c.Query(ctx, "app.bsky.unspecced.getOnboardingSuggestedStarterPacksSkeleton", params, &out)
}
