// Code generated by lexgen. DO NOT EDIT.

package ozone

import (
	"context"
	lextypes "github.com/jcalabro/atmos/api/lextypes"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/atmos/xrpc"
	"github.com/jcalabro/gt"
)

// Precomputed JSON key tokens for ModerationListScheduledActions_Output.
var (
	jsonKey_ModerationListScheduledActions_Output_dollar_type = []byte("\"$type\":")
	jsonKey_ModerationListScheduledActions_Output_actions     = []byte("\"actions\":")
	jsonKey_ModerationListScheduledActions_Output_cursor      = []byte("\"cursor\":")
)

func (s *ModerationListScheduledActions_Output) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *ModerationListScheduledActions_Output) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_ModerationListScheduledActions_Output_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_ModerationListScheduledActions_Output_actions...)
	buf = append(buf, '[')
	for i, item := range s.Actions {
		if i > 0 {
			buf = append(buf, ',')
		}
		var err error
		buf, err = item.AppendJSON(buf)
		if err != nil {
			return nil, err
		}
	}
	buf = append(buf, ']')
	first = false
	if s.Cursor.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_ModerationListScheduledActions_Output_cursor...)
		buf = cbor.AppendJSONString(buf, s.Cursor.Val())
		first = false
	}
	for _, ef := range s.extraJSON {
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *ModerationListScheduledActions_Output) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *ModerationListScheduledActions_Output) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extraJSON = nil
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "actions":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.Actions = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem ModerationDefs_ScheduledActionView
					pos, err = elem.UnmarshalJSONAt(data, pos)
					if err != nil {
						return 0, err
					}
					s.Actions = append(s.Actions, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case "cursor":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v string
				v, pos, err = cbor.ReadJSONString(data, pos)
				if err != nil {
					return 0, err
				}
				s.Cursor = gt.Some(v)
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extraJSON = append(s.extraJSON, lextypes.ExtraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...)})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for ModerationListScheduledActions_Output.
var (
	cborKey_ModerationListScheduledActions_Output_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_ModerationListScheduledActions_Output_cursor      = cbor.AppendTextKey(nil, "cursor")
	cborKey_ModerationListScheduledActions_Output_actions     = cbor.AppendTextKey(nil, "actions")
)

func (s *ModerationListScheduledActions_Output) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *ModerationListScheduledActions_Output) AppendCBOR(buf []byte) ([]byte, error) {
	n := 1 + len(s.extraCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	if s.Cursor.HasVal() {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extraCBOR) > 0 {
		ei := 0
		ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_ModerationListScheduledActions_Output_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "cursor", buf)
		if s.Cursor.HasVal() {
			buf = append(buf, cborKey_ModerationListScheduledActions_Output_cursor...)
			buf = cbor.AppendText(buf, s.Cursor.Val())
		}
		ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "actions", buf)
		buf = append(buf, cborKey_ModerationListScheduledActions_Output_actions...)
		buf = cbor.AppendArrayHeader(buf, uint64(len(s.Actions)))
		for _, item := range s.Actions {
			var err error
			buf, err = item.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
		_, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "", buf)
	} else {
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_ModerationListScheduledActions_Output_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		if s.Cursor.HasVal() {
			buf = append(buf, cborKey_ModerationListScheduledActions_Output_cursor...)
			buf = cbor.AppendText(buf, s.Cursor.Val())
		}
		buf = append(buf, cborKey_ModerationListScheduledActions_Output_actions...)
		buf = cbor.AppendArrayHeader(buf, uint64(len(s.Actions)))
		for _, item := range s.Actions {
			var err error
			buf, err = item.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
	}
	return buf, nil
}

func (s *ModerationListScheduledActions_Output) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *ModerationListScheduledActions_Output) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extraCBOR = nil
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
			}
		case 6:
			if string(data[keyStart:keyEnd]) == "cursor" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v string
					v, pos, err = cbor.ReadText(data, pos)
					if err != nil {
						return 0, err
					}
					s.Cursor = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
			}
		case 7:
			if string(data[keyStart:keyEnd]) == "actions" {
				{
					arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
					if err != nil {
						return 0, err
					}
					pos = newPos
					s.Actions = make([]ModerationDefs_ScheduledActionView, arrLen)
					for idx := range arrLen {
						pos, err = s.Actions[idx].UnmarshalCBORAt(data, pos)
						if err != nil {
							return 0, err
						}
					}
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
		}
	}
	return pos, nil
}

type ModerationListScheduledActions_Output struct {
	LexiconTypeID string                               `json:"$type,omitempty"`
	Actions       []ModerationDefs_ScheduledActionView `json:"actions"`
	Cursor        gt.Option[string]                    `json:"cursor,omitzero"` // Cursor for next page of results

	// extraJSON and extraCBOR preserve unknown fields for same-format round-trips.
	extraJSON []lextypes.ExtraField
	extraCBOR []lextypes.ExtraField
}

// Precomputed JSON key tokens for ModerationListScheduledActions_Input.
var (
	jsonKey_ModerationListScheduledActions_Input_dollar_type = []byte("\"$type\":")
	jsonKey_ModerationListScheduledActions_Input_cursor      = []byte("\"cursor\":")
	jsonKey_ModerationListScheduledActions_Input_endsBefore  = []byte("\"endsBefore\":")
	jsonKey_ModerationListScheduledActions_Input_limit       = []byte("\"limit\":")
	jsonKey_ModerationListScheduledActions_Input_startsAfter = []byte("\"startsAfter\":")
	jsonKey_ModerationListScheduledActions_Input_statuses    = []byte("\"statuses\":")
	jsonKey_ModerationListScheduledActions_Input_subjects    = []byte("\"subjects\":")
)

func (s *ModerationListScheduledActions_Input) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *ModerationListScheduledActions_Input) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_ModerationListScheduledActions_Input_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if s.Cursor.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_ModerationListScheduledActions_Input_cursor...)
		buf = cbor.AppendJSONString(buf, s.Cursor.Val())
		first = false
	}
	if s.EndsBefore.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_ModerationListScheduledActions_Input_endsBefore...)
		buf = cbor.AppendJSONString(buf, s.EndsBefore.Val())
		first = false
	}
	if s.Limit.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_ModerationListScheduledActions_Input_limit...)
		buf = cbor.AppendJSONInt(buf, s.Limit.Val())
		first = false
	}
	if s.StartsAfter.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_ModerationListScheduledActions_Input_startsAfter...)
		buf = cbor.AppendJSONString(buf, s.StartsAfter.Val())
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_ModerationListScheduledActions_Input_statuses...)
	buf = append(buf, '[')
	for i, item := range s.Statuses {
		if i > 0 {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, item)
	}
	buf = append(buf, ']')
	first = false
	if len(s.Subjects) > 0 {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_ModerationListScheduledActions_Input_subjects...)
		buf = append(buf, '[')
		for i, item := range s.Subjects {
			if i > 0 {
				buf = append(buf, ',')
			}
			buf = cbor.AppendJSONString(buf, item)
		}
		buf = append(buf, ']')
		first = false
	}
	for _, ef := range s.extraJSON {
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *ModerationListScheduledActions_Input) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *ModerationListScheduledActions_Input) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extraJSON = nil
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "cursor":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v string
				v, pos, err = cbor.ReadJSONString(data, pos)
				if err != nil {
					return 0, err
				}
				s.Cursor = gt.Some(v)
			}
		case "endsBefore":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v string
				v, pos, err = cbor.ReadJSONString(data, pos)
				if err != nil {
					return 0, err
				}
				s.EndsBefore = gt.Some(v)
			}
		case "limit":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v int64
				v, pos, err = cbor.ReadJSONInt(data, pos)
				if err != nil {
					return 0, err
				}
				s.Limit = gt.Some(v)
			}
		case "startsAfter":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v string
				v, pos, err = cbor.ReadJSONString(data, pos)
				if err != nil {
					return 0, err
				}
				s.StartsAfter = gt.Some(v)
			}
		case "statuses":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.Statuses = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem string
					elem, pos, err = cbor.ReadJSONString(data, pos)
					if err != nil {
						return 0, err
					}
					s.Statuses = append(s.Statuses, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case "subjects":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.Subjects = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem string
					elem, pos, err = cbor.ReadJSONString(data, pos)
					if err != nil {
						return 0, err
					}
					s.Subjects = append(s.Subjects, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extraJSON = append(s.extraJSON, lextypes.ExtraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...)})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for ModerationListScheduledActions_Input.
var (
	cborKey_ModerationListScheduledActions_Input_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_ModerationListScheduledActions_Input_limit       = cbor.AppendTextKey(nil, "limit")
	cborKey_ModerationListScheduledActions_Input_cursor      = cbor.AppendTextKey(nil, "cursor")
	cborKey_ModerationListScheduledActions_Input_statuses    = cbor.AppendTextKey(nil, "statuses")
	cborKey_ModerationListScheduledActions_Input_subjects    = cbor.AppendTextKey(nil, "subjects")
	cborKey_ModerationListScheduledActions_Input_endsBefore  = cbor.AppendTextKey(nil, "endsBefore")
	cborKey_ModerationListScheduledActions_Input_startsAfter = cbor.AppendTextKey(nil, "startsAfter")
)

func (s *ModerationListScheduledActions_Input) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *ModerationListScheduledActions_Input) AppendCBOR(buf []byte) ([]byte, error) {
	n := 1 + len(s.extraCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	if s.Limit.HasVal() {
		n++
	}
	if s.Cursor.HasVal() {
		n++
	}
	if len(s.Subjects) > 0 {
		n++
	}
	if s.EndsBefore.HasVal() {
		n++
	}
	if s.StartsAfter.HasVal() {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extraCBOR) > 0 {
		ei := 0
		ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_ModerationListScheduledActions_Input_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "limit", buf)
		if s.Limit.HasVal() {
			buf = append(buf, cborKey_ModerationListScheduledActions_Input_limit...)
			buf = cbor.AppendInt(buf, s.Limit.Val())
		}
		ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "cursor", buf)
		if s.Cursor.HasVal() {
			buf = append(buf, cborKey_ModerationListScheduledActions_Input_cursor...)
			buf = cbor.AppendText(buf, s.Cursor.Val())
		}
		ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "statuses", buf)
		buf = append(buf, cborKey_ModerationListScheduledActions_Input_statuses...)
		buf = cbor.AppendArrayHeader(buf, uint64(len(s.Statuses)))
		for _, item := range s.Statuses {
			buf = cbor.AppendText(buf, item)
		}
		ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "subjects", buf)
		if len(s.Subjects) > 0 {
			buf = append(buf, cborKey_ModerationListScheduledActions_Input_subjects...)
			buf = cbor.AppendArrayHeader(buf, uint64(len(s.Subjects)))
			for _, item := range s.Subjects {
				buf = cbor.AppendText(buf, item)
			}
		}
		ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "endsBefore", buf)
		if s.EndsBefore.HasVal() {
			buf = append(buf, cborKey_ModerationListScheduledActions_Input_endsBefore...)
			buf = cbor.AppendText(buf, s.EndsBefore.Val())
		}
		ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "startsAfter", buf)
		if s.StartsAfter.HasVal() {
			buf = append(buf, cborKey_ModerationListScheduledActions_Input_startsAfter...)
			buf = cbor.AppendText(buf, s.StartsAfter.Val())
		}
		_, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "", buf)
	} else {
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_ModerationListScheduledActions_Input_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		if s.Limit.HasVal() {
			buf = append(buf, cborKey_ModerationListScheduledActions_Input_limit...)
			buf = cbor.AppendInt(buf, s.Limit.Val())
		}
		if s.Cursor.HasVal() {
			buf = append(buf, cborKey_ModerationListScheduledActions_Input_cursor...)
			buf = cbor.AppendText(buf, s.Cursor.Val())
		}
		buf = append(buf, cborKey_ModerationListScheduledActions_Input_statuses...)
		buf = cbor.AppendArrayHeader(buf, uint64(len(s.Statuses)))
		for _, item := range s.Statuses {
			buf = cbor.AppendText(buf, item)
		}
		if len(s.Subjects) > 0 {
			buf = append(buf, cborKey_ModerationListScheduledActions_Input_subjects...)
			buf = cbor.AppendArrayHeader(buf, uint64(len(s.Subjects)))
			for _, item := range s.Subjects {
				buf = cbor.AppendText(buf, item)
			}
		}
		if s.EndsBefore.HasVal() {
			buf = append(buf, cborKey_ModerationListScheduledActions_Input_endsBefore...)
			buf = cbor.AppendText(buf, s.EndsBefore.Val())
		}
		if s.StartsAfter.HasVal() {
			buf = append(buf, cborKey_ModerationListScheduledActions_Input_startsAfter...)
			buf = cbor.AppendText(buf, s.StartsAfter.Val())
		}
	}
	return buf, nil
}

func (s *ModerationListScheduledActions_Input) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *ModerationListScheduledActions_Input) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extraCBOR = nil
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "limit" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v int64
					v, pos, err = cbor.ReadInt(data, pos)
					if err != nil {
						return 0, err
					}
					s.Limit = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
			}
		case 6:
			if string(data[keyStart:keyEnd]) == "cursor" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v string
					v, pos, err = cbor.ReadText(data, pos)
					if err != nil {
						return 0, err
					}
					s.Cursor = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
			}
		case 8:
			if string(data[keyStart:keyEnd]) == "statuses" {
				{
					arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
					if err != nil {
						return 0, err
					}
					pos = newPos
					s.Statuses = make([]string, arrLen)
					for idx := range arrLen {
						s.Statuses[idx], pos, err = cbor.ReadText(data, pos)
						if err != nil {
							return 0, err
						}
					}
				}
			} else if string(data[keyStart:keyEnd]) == "subjects" {
				{
					arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
					if err != nil {
						return 0, err
					}
					pos = newPos
					s.Subjects = make([]string, arrLen)
					for idx := range arrLen {
						s.Subjects[idx], pos, err = cbor.ReadText(data, pos)
						if err != nil {
							return 0, err
						}
					}
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
			}
		case 10:
			if string(data[keyStart:keyEnd]) == "endsBefore" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v string
					v, pos, err = cbor.ReadText(data, pos)
					if err != nil {
						return 0, err
					}
					s.EndsBefore = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
			}
		case 11:
			if string(data[keyStart:keyEnd]) == "startsAfter" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v string
					v, pos, err = cbor.ReadText(data, pos)
					if err != nil {
						return 0, err
					}
					s.StartsAfter = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
		}
	}
	return pos, nil
}

type ModerationListScheduledActions_Input struct {
	LexiconTypeID string            `json:"$type,omitempty"`
	Cursor        gt.Option[string] `json:"cursor,omitzero"`      // Cursor for pagination
	EndsBefore    gt.Option[string] `json:"endsBefore,omitzero"`  // Filter actions scheduled to execute before this time
	Limit         gt.Option[int64]  `json:"limit,omitzero"`       // Maximum number of results to return
	StartsAfter   gt.Option[string] `json:"startsAfter,omitzero"` // Filter actions scheduled to execute after this time
	Statuses      []string          `json:"statuses"`             // Filter actions by status
	Subjects      []string          `json:"subjects,omitempty"`   // Filter actions for specific DID subjects

	// extraJSON and extraCBOR preserve unknown fields for same-format round-trips.
	extraJSON []lextypes.ExtraField
	extraCBOR []lextypes.ExtraField
}

// ModerationListScheduledActions calls the XRPC procedure "tools.ozone.moderation.listScheduledActions".
//
// List scheduled moderation actions with optional filtering
func ModerationListScheduledActions(ctx context.Context, c *xrpc.Client, input *ModerationListScheduledActions_Input) (*ModerationListScheduledActions_Output, error) {
	var out ModerationListScheduledActions_Output
	return &out, c.Procedure(ctx, "tools.ozone.moderation.listScheduledActions", input, &out)
}
