// Code generated by lexgen. DO NOT EDIT.

package ozone

import (
	"context"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/atmos/xrpc"
	"github.com/jcalabro/gt"
)

// Error name constants for QueueCreateQueue.
const (
	ErrQueueCreateQueue_ConflictingQueue = "ConflictingQueue" // The queue configuration conflicts with an existing queue
)

// Precomputed JSON key tokens for QueueCreateQueue_Output.
var (
	jsonKey_QueueCreateQueue_Output_dollar_type = []byte("\"$type\":")
	jsonKey_QueueCreateQueue_Output_queue       = []byte("\"queue\":")
)

func (s *QueueCreateQueue_Output) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *QueueCreateQueue_Output) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_QueueCreateQueue_Output_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_QueueCreateQueue_Output_queue...)
	{
		var err error
		buf, err = s.Queue.AppendJSON(buf)
		if err != nil {
			return nil, err
		}
	}
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *QueueCreateQueue_Output) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *QueueCreateQueue_Output) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "queue":
			pos, err = s.Queue.UnmarshalJSONAt(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for QueueCreateQueue_Output.
var (
	cborKey_QueueCreateQueue_Output_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_QueueCreateQueue_Output_queue       = cbor.AppendTextKey(nil, "queue")
)

func (s *QueueCreateQueue_Output) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *QueueCreateQueue_Output) AppendCBOR(buf []byte) ([]byte, error) {
	n := 1 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_QueueCreateQueue_Output_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "queue", buf)
		buf = append(buf, cborKey_QueueCreateQueue_Output_queue...)
		{
			var err error
			buf, err = s.Queue.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_QueueCreateQueue_Output_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		buf = append(buf, cborKey_QueueCreateQueue_Output_queue...)
		{
			var err error
			buf, err = s.Queue.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
	}
	return buf, nil
}

func (s *QueueCreateQueue_Output) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *QueueCreateQueue_Output) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "queue" {
				pos, err = s.Queue.UnmarshalCBORAt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

type QueueCreateQueue_Output struct {
	LexiconTypeID string              `json:"$type,omitempty"`
	Queue         QueueDefs_QueueView `json:"queue"`

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// Precomputed JSON key tokens for QueueCreateQueue_Input.
var (
	jsonKey_QueueCreateQueue_Input_dollar_type  = []byte("\"$type\":")
	jsonKey_QueueCreateQueue_Input_collection   = []byte("\"collection\":")
	jsonKey_QueueCreateQueue_Input_description  = []byte("\"description\":")
	jsonKey_QueueCreateQueue_Input_name         = []byte("\"name\":")
	jsonKey_QueueCreateQueue_Input_reportTypes  = []byte("\"reportTypes\":")
	jsonKey_QueueCreateQueue_Input_subjectTypes = []byte("\"subjectTypes\":")
)

func (s *QueueCreateQueue_Input) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *QueueCreateQueue_Input) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_QueueCreateQueue_Input_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if s.Collection.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_QueueCreateQueue_Input_collection...)
		buf = cbor.AppendJSONString(buf, s.Collection.Val())
		first = false
	}
	if s.Description.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_QueueCreateQueue_Input_description...)
		buf = cbor.AppendJSONString(buf, s.Description.Val())
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_QueueCreateQueue_Input_name...)
	buf = cbor.AppendJSONString(buf, s.Name)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_QueueCreateQueue_Input_reportTypes...)
	buf = append(buf, '[')
	for i, item := range s.ReportTypes {
		if i > 0 {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, item)
	}
	buf = append(buf, ']')
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_QueueCreateQueue_Input_subjectTypes...)
	buf = append(buf, '[')
	for i, item := range s.SubjectTypes {
		if i > 0 {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, item)
	}
	buf = append(buf, ']')
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *QueueCreateQueue_Input) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *QueueCreateQueue_Input) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "collection":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v string
				v, pos, err = cbor.ReadJSONString(data, pos)
				if err != nil {
					return 0, err
				}
				s.Collection = gt.Some(v)
			}
		case "description":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v string
				v, pos, err = cbor.ReadJSONString(data, pos)
				if err != nil {
					return 0, err
				}
				s.Description = gt.Some(v)
			}
		case "name":
			s.Name, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "reportTypes":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.ReportTypes = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem string
					elem, pos, err = cbor.ReadJSONString(data, pos)
					if err != nil {
						return 0, err
					}
					s.ReportTypes = append(s.ReportTypes, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case "subjectTypes":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.SubjectTypes = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem string
					elem, pos, err = cbor.ReadJSONString(data, pos)
					if err != nil {
						return 0, err
					}
					s.SubjectTypes = append(s.SubjectTypes, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for QueueCreateQueue_Input.
var (
	cborKey_QueueCreateQueue_Input_name         = cbor.AppendTextKey(nil, "name")
	cborKey_QueueCreateQueue_Input_dollar_type  = cbor.AppendTextKey(nil, "$type")
	cborKey_QueueCreateQueue_Input_collection   = cbor.AppendTextKey(nil, "collection")
	cborKey_QueueCreateQueue_Input_description  = cbor.AppendTextKey(nil, "description")
	cborKey_QueueCreateQueue_Input_reportTypes  = cbor.AppendTextKey(nil, "reportTypes")
	cborKey_QueueCreateQueue_Input_subjectTypes = cbor.AppendTextKey(nil, "subjectTypes")
)

func (s *QueueCreateQueue_Input) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *QueueCreateQueue_Input) AppendCBOR(buf []byte) ([]byte, error) {
	n := 3 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	if s.Collection.HasVal() {
		n++
	}
	if s.Description.HasVal() {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "name", buf)
		buf = append(buf, cborKey_QueueCreateQueue_Input_name...)
		buf = cbor.AppendText(buf, s.Name)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_QueueCreateQueue_Input_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "collection", buf)
		if s.Collection.HasVal() {
			buf = append(buf, cborKey_QueueCreateQueue_Input_collection...)
			buf = cbor.AppendText(buf, s.Collection.Val())
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "description", buf)
		if s.Description.HasVal() {
			buf = append(buf, cborKey_QueueCreateQueue_Input_description...)
			buf = cbor.AppendText(buf, s.Description.Val())
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "reportTypes", buf)
		buf = append(buf, cborKey_QueueCreateQueue_Input_reportTypes...)
		buf = cbor.AppendArrayHeader(buf, uint64(len(s.ReportTypes)))
		for _, item := range s.ReportTypes {
			buf = cbor.AppendText(buf, item)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "subjectTypes", buf)
		buf = append(buf, cborKey_QueueCreateQueue_Input_subjectTypes...)
		buf = cbor.AppendArrayHeader(buf, uint64(len(s.SubjectTypes)))
		for _, item := range s.SubjectTypes {
			buf = cbor.AppendText(buf, item)
		}
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		buf = append(buf, cborKey_QueueCreateQueue_Input_name...)
		buf = cbor.AppendText(buf, s.Name)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_QueueCreateQueue_Input_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		if s.Collection.HasVal() {
			buf = append(buf, cborKey_QueueCreateQueue_Input_collection...)
			buf = cbor.AppendText(buf, s.Collection.Val())
		}
		if s.Description.HasVal() {
			buf = append(buf, cborKey_QueueCreateQueue_Input_description...)
			buf = cbor.AppendText(buf, s.Description.Val())
		}
		buf = append(buf, cborKey_QueueCreateQueue_Input_reportTypes...)
		buf = cbor.AppendArrayHeader(buf, uint64(len(s.ReportTypes)))
		for _, item := range s.ReportTypes {
			buf = cbor.AppendText(buf, item)
		}
		buf = append(buf, cborKey_QueueCreateQueue_Input_subjectTypes...)
		buf = cbor.AppendArrayHeader(buf, uint64(len(s.SubjectTypes)))
		for _, item := range s.SubjectTypes {
			buf = cbor.AppendText(buf, item)
		}
	}
	return buf, nil
}

func (s *QueueCreateQueue_Input) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *QueueCreateQueue_Input) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 4:
			if string(data[keyStart:keyEnd]) == "name" {
				s.Name, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 10:
			if string(data[keyStart:keyEnd]) == "collection" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v string
					v, pos, err = cbor.ReadText(data, pos)
					if err != nil {
						return 0, err
					}
					s.Collection = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 11:
			if string(data[keyStart:keyEnd]) == "description" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v string
					v, pos, err = cbor.ReadText(data, pos)
					if err != nil {
						return 0, err
					}
					s.Description = gt.Some(v)
				}
			} else if string(data[keyStart:keyEnd]) == "reportTypes" {
				{
					arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
					if err != nil {
						return 0, err
					}
					if err := cbor.CheckArrayLen(arrLen, data, newPos); err != nil {
						return 0, err
					}
					pos = newPos
					s.ReportTypes = make([]string, arrLen)
					for idx := range arrLen {
						s.ReportTypes[idx], pos, err = cbor.ReadText(data, pos)
						if err != nil {
							return 0, err
						}
					}
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 12:
			if string(data[keyStart:keyEnd]) == "subjectTypes" {
				{
					arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
					if err != nil {
						return 0, err
					}
					if err := cbor.CheckArrayLen(arrLen, data, newPos); err != nil {
						return 0, err
					}
					pos = newPos
					s.SubjectTypes = make([]string, arrLen)
					for idx := range arrLen {
						s.SubjectTypes[idx], pos, err = cbor.ReadText(data, pos)
						if err != nil {
							return 0, err
						}
					}
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

type QueueCreateQueue_Input struct {
	LexiconTypeID string            `json:"$type,omitempty"`
	Collection    gt.Option[string] `json:"collection,omitzero"`  // Collection name for record subjects. Required if subjectTypes includes 'record'.
	Description   gt.Option[string] `json:"description,omitzero"` // Optional description of the queue
	Name          string            `json:"name"`                 // Display name for the queue (must be unique)
	ReportTypes   []string          `json:"reportTypes"`          // Report reason types (fully qualified NSIDs)
	SubjectTypes  []string          `json:"subjectTypes"`         // Subject types this queue accepts

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// QueueCreateQueue calls the XRPC procedure "tools.ozone.queue.createQueue".
//
// Create a new moderation queue. Will fail if the queue configuration conflicts with an existing queue.
func QueueCreateQueue(ctx context.Context, c *xrpc.Client, input *QueueCreateQueue_Input) (*QueueCreateQueue_Output, error) {
	var out QueueCreateQueue_Output
	return &out, c.Procedure(ctx, "tools.ozone.queue.createQueue", input, &out)
}
