// Code generated by lexgen. DO NOT EDIT.

package ozone

import (
	"github.com/jcalabro/gt"
	"github.com/jcalabro/atmos/cbor"
)

// SetDefs_Set is a "set" in the tools.ozone.set.defs schema.
type SetDefs_Set struct {
	LexiconTypeID string            `json:"$type,omitempty"`
	Description   gt.Option[string] `json:"description,omitzero"`
	Name          string            `json:"name"`
}

// Precomputed CBOR key tokens for SetDefs_Set.
var (
	cborKey_SetDefs_Set_name        = cbor.AppendTextKey(nil, "name")
	cborKey_SetDefs_Set_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_SetDefs_Set_description = cbor.AppendTextKey(nil, "description")
)

func (s *SetDefs_Set) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *SetDefs_Set) AppendCBOR(buf []byte) ([]byte, error) {
	n := 1
	if s.LexiconTypeID != "" {
		n++
	}
	if s.Description.HasVal() {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	buf = append(buf, cborKey_SetDefs_Set_name...)
	buf = cbor.AppendText(buf, s.Name)
	if s.LexiconTypeID != "" {
		buf = append(buf, cborKey_SetDefs_Set_dollar_type...)
		buf = cbor.AppendText(buf, s.LexiconTypeID)
	}
	if s.Description.HasVal() {
		buf = append(buf, cborKey_SetDefs_Set_description...)
		buf = cbor.AppendText(buf, s.Description.Val())
	}
	return buf, nil
}

func (s *SetDefs_Set) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *SetDefs_Set) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		key, newPos, err := cbor.ReadText(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch key {
		case "name":
			s.Name, pos, err = cbor.ReadText(data, pos)
			if err != nil {
				return 0, err
			}
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
			if err != nil {
				return 0, err
			}
		case "description":
			if cbor.IsNull(data, pos) {
				pos++
			} else {
				var v string
				v, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
				s.Description = gt.Some(v)
			}
		default:
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
	}
	return pos, nil
}

// Precomputed JSON key tokens for SetDefs_Set.
var (
	jsonKey_SetDefs_Set_dollar_type = []byte("\"$type\":")
	jsonKey_SetDefs_Set_description = []byte("\"description\":")
	jsonKey_SetDefs_Set_name        = []byte("\"name\":")
)

func (s *SetDefs_Set) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *SetDefs_Set) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_SetDefs_Set_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if s.Description.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_SetDefs_Set_description...)
		buf = cbor.AppendJSONString(buf, s.Description.Val())
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_SetDefs_Set_name...)
	buf = cbor.AppendJSONString(buf, s.Name)
	first = false
	buf = append(buf, '}')
	return buf, nil
}

func (s *SetDefs_Set) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *SetDefs_Set) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "description":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v string
				v, pos, err = cbor.ReadJSONString(data, pos)
				if err != nil {
					return 0, err
				}
				s.Description = gt.Some(v)
			}
		case "name":
			s.Name, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// SetDefs_SetView is a "setView" in the tools.ozone.set.defs schema.
type SetDefs_SetView struct {
	LexiconTypeID string            `json:"$type,omitempty"`
	CreatedAt     string            `json:"createdAt"`
	Description   gt.Option[string] `json:"description,omitzero"`
	Name          string            `json:"name"`
	SetSize       int64             `json:"setSize"`
	UpdatedAt     string            `json:"updatedAt"`
}

// Precomputed CBOR key tokens for SetDefs_SetView.
var (
	cborKey_SetDefs_SetView_name        = cbor.AppendTextKey(nil, "name")
	cborKey_SetDefs_SetView_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_SetDefs_SetView_setSize     = cbor.AppendTextKey(nil, "setSize")
	cborKey_SetDefs_SetView_createdAt   = cbor.AppendTextKey(nil, "createdAt")
	cborKey_SetDefs_SetView_updatedAt   = cbor.AppendTextKey(nil, "updatedAt")
	cborKey_SetDefs_SetView_description = cbor.AppendTextKey(nil, "description")
)

func (s *SetDefs_SetView) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *SetDefs_SetView) AppendCBOR(buf []byte) ([]byte, error) {
	n := 4
	if s.LexiconTypeID != "" {
		n++
	}
	if s.Description.HasVal() {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	buf = append(buf, cborKey_SetDefs_SetView_name...)
	buf = cbor.AppendText(buf, s.Name)
	if s.LexiconTypeID != "" {
		buf = append(buf, cborKey_SetDefs_SetView_dollar_type...)
		buf = cbor.AppendText(buf, s.LexiconTypeID)
	}
	buf = append(buf, cborKey_SetDefs_SetView_setSize...)
	buf = cbor.AppendInt(buf, s.SetSize)
	buf = append(buf, cborKey_SetDefs_SetView_createdAt...)
	buf = cbor.AppendText(buf, s.CreatedAt)
	buf = append(buf, cborKey_SetDefs_SetView_updatedAt...)
	buf = cbor.AppendText(buf, s.UpdatedAt)
	if s.Description.HasVal() {
		buf = append(buf, cborKey_SetDefs_SetView_description...)
		buf = cbor.AppendText(buf, s.Description.Val())
	}
	return buf, nil
}

func (s *SetDefs_SetView) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *SetDefs_SetView) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		key, newPos, err := cbor.ReadText(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch key {
		case "name":
			s.Name, pos, err = cbor.ReadText(data, pos)
			if err != nil {
				return 0, err
			}
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
			if err != nil {
				return 0, err
			}
		case "setSize":
			s.SetSize, pos, err = cbor.ReadInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "createdAt":
			s.CreatedAt, pos, err = cbor.ReadText(data, pos)
			if err != nil {
				return 0, err
			}
		case "updatedAt":
			s.UpdatedAt, pos, err = cbor.ReadText(data, pos)
			if err != nil {
				return 0, err
			}
		case "description":
			if cbor.IsNull(data, pos) {
				pos++
			} else {
				var v string
				v, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
				s.Description = gt.Some(v)
			}
		default:
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
	}
	return pos, nil
}

// Precomputed JSON key tokens for SetDefs_SetView.
var (
	jsonKey_SetDefs_SetView_dollar_type = []byte("\"$type\":")
	jsonKey_SetDefs_SetView_createdAt   = []byte("\"createdAt\":")
	jsonKey_SetDefs_SetView_description = []byte("\"description\":")
	jsonKey_SetDefs_SetView_name        = []byte("\"name\":")
	jsonKey_SetDefs_SetView_setSize     = []byte("\"setSize\":")
	jsonKey_SetDefs_SetView_updatedAt   = []byte("\"updatedAt\":")
)

func (s *SetDefs_SetView) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *SetDefs_SetView) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_SetDefs_SetView_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_SetDefs_SetView_createdAt...)
	buf = cbor.AppendJSONString(buf, s.CreatedAt)
	first = false
	if s.Description.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_SetDefs_SetView_description...)
		buf = cbor.AppendJSONString(buf, s.Description.Val())
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_SetDefs_SetView_name...)
	buf = cbor.AppendJSONString(buf, s.Name)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_SetDefs_SetView_setSize...)
	buf = cbor.AppendJSONInt(buf, s.SetSize)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_SetDefs_SetView_updatedAt...)
	buf = cbor.AppendJSONString(buf, s.UpdatedAt)
	first = false
	buf = append(buf, '}')
	return buf, nil
}

func (s *SetDefs_SetView) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *SetDefs_SetView) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "createdAt":
			s.CreatedAt, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "description":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v string
				v, pos, err = cbor.ReadJSONString(data, pos)
				if err != nil {
					return 0, err
				}
				s.Description = gt.Some(v)
			}
		case "name":
			s.Name, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "setSize":
			s.SetSize, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "updatedAt":
			s.UpdatedAt, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}
