// Code generated by lexgen. DO NOT EDIT.

package ozone

import (
	"context"
	lextypes "github.com/jcalabro/atmos/api/lextypes"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/atmos/xrpc"
)

// Error name constants for TeamDeleteMember.
const (
	ErrTeamDeleteMember_MemberNotFound   = "MemberNotFound"   // The member being deleted does not exist
	ErrTeamDeleteMember_CannotDeleteSelf = "CannotDeleteSelf" // You can not delete yourself from the team
)

// Precomputed JSON key tokens for TeamDeleteMember_Input.
var (
	jsonKey_TeamDeleteMember_Input_dollar_type = []byte("\"$type\":")
	jsonKey_TeamDeleteMember_Input_did         = []byte("\"did\":")
)

func (s *TeamDeleteMember_Input) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *TeamDeleteMember_Input) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_TeamDeleteMember_Input_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_TeamDeleteMember_Input_did...)
	buf = cbor.AppendJSONString(buf, s.DID)
	first = false
	for _, ef := range s.extraJSON {
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *TeamDeleteMember_Input) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *TeamDeleteMember_Input) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extraJSON = nil
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "did":
			s.DID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extraJSON = append(s.extraJSON, lextypes.ExtraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...)})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for TeamDeleteMember_Input.
var (
	cborKey_TeamDeleteMember_Input_did         = cbor.AppendTextKey(nil, "did")
	cborKey_TeamDeleteMember_Input_dollar_type = cbor.AppendTextKey(nil, "$type")
)

func (s *TeamDeleteMember_Input) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *TeamDeleteMember_Input) AppendCBOR(buf []byte) ([]byte, error) {
	n := 1 + len(s.extraCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extraCBOR) > 0 {
		ei := 0
		ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "did", buf)
		buf = append(buf, cborKey_TeamDeleteMember_Input_did...)
		buf = cbor.AppendText(buf, s.DID)
		ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_TeamDeleteMember_Input_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		_, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "", buf)
	} else {
		buf = append(buf, cborKey_TeamDeleteMember_Input_did...)
		buf = cbor.AppendText(buf, s.DID)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_TeamDeleteMember_Input_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
	}
	return buf, nil
}

func (s *TeamDeleteMember_Input) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *TeamDeleteMember_Input) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extraCBOR = nil
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 3:
			if string(data[keyStart:keyEnd]) == "did" {
				s.DID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
			}
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
		}
	}
	return pos, nil
}

type TeamDeleteMember_Input struct {
	LexiconTypeID string `json:"$type,omitempty"`
	DID           string `json:"did"`

	// extraJSON and extraCBOR preserve unknown fields for same-format round-trips.
	extraJSON []lextypes.ExtraField
	extraCBOR []lextypes.ExtraField
}

// TeamDeleteMember calls the XRPC procedure "tools.ozone.team.deleteMember".
//
// Delete a member from ozone team. Requires admin role.
func TeamDeleteMember(ctx context.Context, c *xrpc.Client, input *TeamDeleteMember_Input) error {
	return c.Procedure(ctx, "tools.ozone.team.deleteMember", input, nil)
}
