package lexgen

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

type recordInfo struct {
	nsid     string
	typeName string
}

// formatSource runs go/format on the generated source code.
func formatSource(filename string, src []byte) ([]byte, error) {
	out, err := format.Source(src)
	if err != nil {
		return nil, fmt.Errorf("format %s: %w\n\nsource:\n%s", filename, err, src)
	}
	return out, nil
}

// WriteFiles writes all generated files to disk, creating directories as needed.
func WriteFiles(files map[string][]byte) error {
	for path, data := range files {
		dir := filepath.Dir(path)
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("mkdir %s: %w", dir, err)
		}
		if err := os.WriteFile(path, data, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}
	return nil
}

// generateSharedTypes produces the shared types file for a package.
func generateSharedTypes(pkgName string) string {
	return `// Code generated by lexgen. DO NOT EDIT.

package ` + pkgName + `

import (
	"encoding/json"

	"github.com/jcalabro/atmos/cbor"
)

// LexBlob represents an uploaded blob reference.
type LexBlob struct {
	Type     string     ` + "`" + `json:"$type"` + "`" + `
	Ref      LexCIDLink ` + "`" + `json:"ref"` + "`" + `
	MimeType string     ` + "`" + `json:"mimeType"` + "`" + `
	Size     int64      ` + "`" + `json:"size"` + "`" + `

	// extra preserves unknown fields for same-format round-trips.
	// See extraField for design rationale.
	extra []extraField
}

// LexCIDLink is a CID reference using the $link JSON convention.
type LexCIDLink struct {
	Link string ` + "`" + `json:"$link"` + "`" + `
}

// UnknownUnionVariant holds an unrecognized union member in an open union.
type UnknownUnionVariant struct {
	Type    string          ` + "`" + `json:"$type"` + "`" + `
	Raw     json.RawMessage ` + "`" + `json:"-"` + "`" + `
	RawCBOR []byte          ` + "`" + `json:"-"` + "`" + `
}

// Precomputed CBOR key tokens for LexBlob.
var (
	cborKey_LexBlob_type     = cbor.AppendTextKey(nil, "$type")
	cborKey_LexBlob_mimeType = cbor.AppendTextKey(nil, "mimeType")
	cborKey_LexBlob_ref      = cbor.AppendTextKey(nil, "ref")
	cborKey_LexBlob_size     = cbor.AppendTextKey(nil, "size")
)

// MarshalCBOR encodes a LexBlob to DAG-CBOR.
func (b *LexBlob) MarshalCBOR() ([]byte, error) {
	return b.AppendCBOR(make([]byte, 0, 128))
}

// AppendCBOR appends the DAG-CBOR encoding to buf.
func (b *LexBlob) AppendCBOR(buf []byte) ([]byte, error) {
	buf = cbor.AppendMapHeader(buf, uint64(4 + countExtra(b.extra, extraEncodingCBOR)))
	// DAG-CBOR key order: ref(3), size(4), $type(5), mimeType(8)
	if countExtra(b.extra, extraEncodingCBOR) > 0 {
		// Extras are merged at the correct position to maintain DAG-CBOR key ordering.
		ei := 0
		ei, buf = appendCBORExtrasBefore(b.extra, ei, "ref", buf)
		buf = append(buf, cborKey_LexBlob_ref...)
		var err error
		buf, err = b.Ref.AppendCBOR(buf)
		if err != nil { return nil, err }
		ei, buf = appendCBORExtrasBefore(b.extra, ei, "size", buf)
		buf = append(buf, cborKey_LexBlob_size...)
		buf = cbor.AppendInt(buf, b.Size)
		ei, buf = appendCBORExtrasBefore(b.extra, ei, "$type", buf)
		buf = append(buf, cborKey_LexBlob_type...)
		buf = cbor.AppendText(buf, b.Type)
		ei, buf = appendCBORExtrasBefore(b.extra, ei, "mimeType", buf)
		buf = append(buf, cborKey_LexBlob_mimeType...)
		buf = cbor.AppendText(buf, b.MimeType)
		_, buf = appendCBORExtrasBefore(b.extra, ei, "", buf)
	} else {
		buf = append(buf, cborKey_LexBlob_ref...)
		var err error
		buf, err = b.Ref.AppendCBOR(buf)
		if err != nil { return nil, err }
		buf = append(buf, cborKey_LexBlob_size...)
		buf = cbor.AppendInt(buf, b.Size)
		buf = append(buf, cborKey_LexBlob_type...)
		buf = cbor.AppendText(buf, b.Type)
		buf = append(buf, cborKey_LexBlob_mimeType...)
		buf = cbor.AppendText(buf, b.MimeType)
	}
	return buf, nil
}

// UnmarshalCBOR decodes a LexBlob from DAG-CBOR.
func (b *LexBlob) UnmarshalCBOR(data []byte) error {
	_, err := b.UnmarshalCBORAt(data, 0)
	return err
}

// UnmarshalCBORAt decodes a LexBlob from DAG-CBOR starting at pos.
func (b *LexBlob) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	b.extra = clearExtra(b.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil { return 0, err }
	for i := uint64(0); i < count; i++ {
		key, newPos, err := cbor.ReadText(data, pos)
		if err != nil { return 0, err }
		pos = newPos
		switch key {
		case "$type":
			b.Type, pos, err = cbor.ReadText(data, pos)
		case "ref":
			pos, err = b.Ref.UnmarshalCBORAt(data, pos)
			if err != nil { return 0, err }
			continue
		case "mimeType":
			b.MimeType, pos, err = cbor.ReadText(data, pos)
		case "size":
			b.Size, pos, err = cbor.ReadInt(data, pos)
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil { return 0, err }
			b.extra = append(b.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			continue
		}
		if err != nil { return 0, err }
	}
	return pos, nil
}

// MarshalCBOR encodes a LexCIDLink as a DAG-CBOR CID link (tag 42).
func (c *LexCIDLink) MarshalCBOR() ([]byte, error) {
	return c.AppendCBOR(nil)
}

// AppendCBOR appends the DAG-CBOR CID link encoding to buf.
func (c *LexCIDLink) AppendCBOR(buf []byte) ([]byte, error) {
	cid, err := cbor.ParseCIDString(c.Link)
	if err != nil { return nil, err }
	return cbor.AppendCIDLink(buf, &cid), nil
}

// UnmarshalCBOR decodes a LexCIDLink from a DAG-CBOR CID link (tag 42).
func (c *LexCIDLink) UnmarshalCBOR(data []byte) error {
	_, err := c.UnmarshalCBORAt(data, 0)
	return err
}

// UnmarshalCBORAt decodes a LexCIDLink from a DAG-CBOR CID link at pos.
func (c *LexCIDLink) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	cid, newPos, err := cbor.ReadCIDLink(data, pos)
	if err != nil { return 0, err }
	c.Link = cid.String()
	return newPos, nil
}

// Precomputed JSON key tokens for LexBlob.
var (
	jsonKey_LexBlob_type     = []byte("\"$type\":")
	jsonKey_LexBlob_mimeType = []byte("\"mimeType\":")
	jsonKey_LexBlob_ref      = []byte("\"ref\":")
	jsonKey_LexBlob_size     = []byte("\"size\":")
)

// MarshalJSON encodes a LexBlob to JSON.
func (b *LexBlob) MarshalJSON() ([]byte, error) {
	return b.AppendJSON(make([]byte, 0, 128))
}

// AppendJSON appends the JSON encoding to buf.
func (b *LexBlob) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	buf = append(buf, jsonKey_LexBlob_type...)
	buf = cbor.AppendJSONString(buf, b.Type)
	buf = append(buf, ',')
	buf = append(buf, jsonKey_LexBlob_mimeType...)
	buf = cbor.AppendJSONString(buf, b.MimeType)
	buf = append(buf, ',')
	buf = append(buf, jsonKey_LexBlob_ref...)
	var err error
	buf, err = b.Ref.AppendJSON(buf)
	if err != nil { return nil, err }
	buf = append(buf, ',')
	buf = append(buf, jsonKey_LexBlob_size...)
	buf = cbor.AppendJSONInt(buf, b.Size)
	for _, ef := range b.extra {
		if ef.Encoding != extraEncodingJSON { continue }
		buf = append(buf, ',')
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
	}
	buf = append(buf, '}')
	return buf, nil
}

// UnmarshalJSON decodes a LexBlob from JSON.
func (b *LexBlob) UnmarshalJSON(data []byte) error {
	_, err := b.UnmarshalJSONAt(data, 0)
	return err
}

// UnmarshalJSONAt decodes a LexBlob from JSON starting at pos.
func (b *LexBlob) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	b.extra = clearExtra(b.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil { return 0, err }
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done { return pos, nil }
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil { return 0, err }
		switch key {
		case "$type":
			b.Type, pos, err = cbor.ReadJSONString(data, pos)
		case "ref":
			pos, err = b.Ref.UnmarshalJSONAt(data, pos)
		case "mimeType":
			b.MimeType, pos, err = cbor.ReadJSONString(data, pos)
		case "size":
			b.Size, pos, err = cbor.ReadJSONInt(data, pos)
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil { return 0, err }
			b.extra = append(b.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		if err != nil { return 0, err }
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed JSON key tokens for LexCIDLink.
var jsonKey_LexCIDLink_link = []byte("\"$link\":")

// MarshalJSON encodes a LexCIDLink to JSON.
func (c *LexCIDLink) MarshalJSON() ([]byte, error) {
	return c.AppendJSON(make([]byte, 0, 64))
}

// AppendJSON appends the JSON encoding to buf.
func (c *LexCIDLink) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	buf = append(buf, jsonKey_LexCIDLink_link...)
	buf = cbor.AppendJSONString(buf, c.Link)
	buf = append(buf, '}')
	return buf, nil
}

// UnmarshalJSON decodes a LexCIDLink from JSON.
func (c *LexCIDLink) UnmarshalJSON(data []byte) error {
	_, err := c.UnmarshalJSONAt(data, 0)
	return err
}

// UnmarshalJSONAt decodes a LexCIDLink from JSON starting at pos.
func (c *LexCIDLink) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil { return 0, err }
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done { return pos, nil }
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil { return 0, err }
		switch key {
		case "$link":
			c.Link, pos, err = cbor.ReadJSONString(data, pos)
		default:
			pos, err = cbor.SkipJSONValue(data, pos)
		}
		if err != nil { return 0, err }
		pos = cbor.SkipJSONComma(data, pos)
	}
}
`
}

// generateExtraTypes produces the unexported extra field types and helpers
// for a single package. Each package gets its own copy so the types stay
// unexported and package-internal.
func generateExtraTypes(pkgName string) string {
	return `// Code generated by lexgen. DO NOT EDIT.

package ` + pkgName + `

import "github.com/jcalabro/atmos/cbor"

// extraEncoding identifies the wire format of an extraField's value bytes.
type extraEncoding int8

const (
	extraEncodingJSON extraEncoding = 0
	extraEncodingCBOR extraEncoding = 1
)

// extraField holds a single unknown key-value pair encountered during decoding.
// Generated types use a single slice to preserve unknown fields across same-format
// round-trips. A slice (not a map) is used to maintain insertion order, which
// matters for DAG-CBOR determinism and DRISL. The Encoding field distinguishes
// the wire format so that extras from different encodings can coexist in one
// slice without cross-format leakage — CBOR marshal only emits extraEncodingCBOR
// entries, JSON marshal only emits extraEncodingJSON entries.
//
// Cross-format round-trips (e.g. JSON unmarshal → CBOR marshal) will not carry
// extras across because raw bytes are not interchangeable between formats —
// transcoding would require schema knowledge that we explicitly lack for
// unknown fields.
type extraField struct {
	Key      string         // the original field name
	Value    []byte         // raw-encoded value bytes in the format indicated by Encoding
	Encoding extraEncoding  // wire format of Value (extraEncodingJSON, extraEncodingCBOR, etc.)
}

// countExtra returns the number of extra fields with the given encoding.
func countExtra(extras []extraField, enc extraEncoding) int {
	n := 0
	for i := range extras {
		if extras[i].Encoding == enc { n++ }
	}
	return n
}

// clearExtra removes all entries with the given encoding from the slice,
// preserving entries of other encodings. Returns the (possibly shorter) slice.
func clearExtra(extras []extraField, enc extraEncoding) []extraField {
	n := 0
	for i := range extras {
		if extras[i].Encoding != enc {
			extras[n] = extras[i]
			n++
		}
	}
	if n == 0 {
		return nil
	}
	return extras[:n]
}

// appendCBORExtrasBefore appends CBOR-encoded extra fields from extras[idx:]
// that sort before nextKey in DAG-CBOR key order. Non-CBOR entries are skipped.
// If nextKey is empty, all remaining CBOR extras are appended.
//
// CBOR entries MUST be in DAG-CBOR sorted key order (as produced by
// UnmarshalCBORAt). This invariant is maintained by construction — CBOR maps
// decoded from valid DAG-CBOR are always in sorted order.
func appendCBORExtrasBefore(extras []extraField, idx int, nextKey string, buf []byte) (int, []byte) {
	for idx < len(extras) {
		if extras[idx].Encoding != extraEncodingCBOR {
			idx++
			continue
		}
		if nextKey != "" && cbor.CompareCBORKeys(extras[idx].Key, nextKey) >= 0 {
			break
		}
		buf = cbor.AppendTextKey(buf, extras[idx].Key)
		buf = append(buf, extras[idx].Value...)
		idx++
	}
	return idx, buf
}
`
}

// generateDecodeRecord produces a DecodeRecord function for a package.
func generateDecodeRecord(pkgName string, records []recordInfo) string {
	var b strings.Builder
	b.WriteString("// Code generated by lexgen. DO NOT EDIT.\n\n")
	b.WriteString("package " + pkgName + "\n\n")
	b.WriteString("import \"fmt\"\n\n")
	b.WriteString("// DecodeRecord unmarshals a CBOR-encoded record by collection NSID.\n")
	b.WriteString("// Returns a pointer to the decoded record type, or an error if the\n")
	b.WriteString("// collection is not recognized or decoding fails.\n")
	b.WriteString("func DecodeRecord(collection string, data []byte) (any, error) {\n")
	b.WriteString("\tswitch collection {\n")
	for _, r := range records {
		fmt.Fprintf(&b, "\tcase %q:\n", r.nsid)
		fmt.Fprintf(&b, "\t\tvar v %s\n", r.typeName)
		b.WriteString("\t\tif err := v.UnmarshalCBOR(data); err != nil {\n")
		b.WriteString("\t\t\treturn nil, err\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t\treturn &v, nil\n")
	}
	b.WriteString("\tdefault:\n")
	b.WriteString("\t\treturn nil, fmt.Errorf(\"unknown collection: %s\", collection)\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")
	return b.String()
}
