// Code generated by lexgen. DO NOT EDIT.

package chatbsky

import (
	"context"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/atmos/xrpc"
)

// Precomputed JSON key tokens for ConvoLeaveConvo_Output.
var (
	jsonKey_ConvoLeaveConvo_Output_dollar_type = []byte("\"$type\":")
	jsonKey_ConvoLeaveConvo_Output_convoId     = []byte("\"convoId\":")
	jsonKey_ConvoLeaveConvo_Output_rev         = []byte("\"rev\":")
)

func (s *ConvoLeaveConvo_Output) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *ConvoLeaveConvo_Output) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_ConvoLeaveConvo_Output_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_ConvoLeaveConvo_Output_convoId...)
	buf = cbor.AppendJSONString(buf, s.ConvoId)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_ConvoLeaveConvo_Output_rev...)
	buf = cbor.AppendJSONString(buf, s.Rev)
	first = false
	buf = append(buf, '}')
	return buf, nil
}

func (s *ConvoLeaveConvo_Output) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *ConvoLeaveConvo_Output) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "convoId":
			s.ConvoId, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "rev":
			s.Rev, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for ConvoLeaveConvo_Output.
var (
	cborKey_ConvoLeaveConvo_Output_rev         = cbor.AppendTextKey(nil, "rev")
	cborKey_ConvoLeaveConvo_Output_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_ConvoLeaveConvo_Output_convoId     = cbor.AppendTextKey(nil, "convoId")
)

func (s *ConvoLeaveConvo_Output) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *ConvoLeaveConvo_Output) AppendCBOR(buf []byte) ([]byte, error) {
	n := 2
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	buf = append(buf, cborKey_ConvoLeaveConvo_Output_rev...)
	buf = cbor.AppendText(buf, s.Rev)
	if s.LexiconTypeID != "" {
		buf = append(buf, cborKey_ConvoLeaveConvo_Output_dollar_type...)
		buf = cbor.AppendText(buf, s.LexiconTypeID)
	}
	buf = append(buf, cborKey_ConvoLeaveConvo_Output_convoId...)
	buf = cbor.AppendText(buf, s.ConvoId)
	return buf, nil
}

func (s *ConvoLeaveConvo_Output) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *ConvoLeaveConvo_Output) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		key, newPos, err := cbor.ReadText(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch key {
		case "rev":
			s.Rev, pos, err = cbor.ReadText(data, pos)
			if err != nil {
				return 0, err
			}
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
			if err != nil {
				return 0, err
			}
		case "convoId":
			s.ConvoId, pos, err = cbor.ReadText(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
	}
	return pos, nil
}

type ConvoLeaveConvo_Output struct {
	LexiconTypeID string `json:"$type,omitempty"`
	ConvoId       string `json:"convoId"`
	Rev           string `json:"rev"`
}

// Precomputed JSON key tokens for ConvoLeaveConvo_Input.
var (
	jsonKey_ConvoLeaveConvo_Input_dollar_type = []byte("\"$type\":")
	jsonKey_ConvoLeaveConvo_Input_convoId     = []byte("\"convoId\":")
)

func (s *ConvoLeaveConvo_Input) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *ConvoLeaveConvo_Input) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_ConvoLeaveConvo_Input_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_ConvoLeaveConvo_Input_convoId...)
	buf = cbor.AppendJSONString(buf, s.ConvoId)
	first = false
	buf = append(buf, '}')
	return buf, nil
}

func (s *ConvoLeaveConvo_Input) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *ConvoLeaveConvo_Input) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "convoId":
			s.ConvoId, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for ConvoLeaveConvo_Input.
var (
	cborKey_ConvoLeaveConvo_Input_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_ConvoLeaveConvo_Input_convoId     = cbor.AppendTextKey(nil, "convoId")
)

func (s *ConvoLeaveConvo_Input) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *ConvoLeaveConvo_Input) AppendCBOR(buf []byte) ([]byte, error) {
	n := 1
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if s.LexiconTypeID != "" {
		buf = append(buf, cborKey_ConvoLeaveConvo_Input_dollar_type...)
		buf = cbor.AppendText(buf, s.LexiconTypeID)
	}
	buf = append(buf, cborKey_ConvoLeaveConvo_Input_convoId...)
	buf = cbor.AppendText(buf, s.ConvoId)
	return buf, nil
}

func (s *ConvoLeaveConvo_Input) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *ConvoLeaveConvo_Input) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		key, newPos, err := cbor.ReadText(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
			if err != nil {
				return 0, err
			}
		case "convoId":
			s.ConvoId, pos, err = cbor.ReadText(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
	}
	return pos, nil
}

type ConvoLeaveConvo_Input struct {
	LexiconTypeID string `json:"$type,omitempty"`
	ConvoId       string `json:"convoId"`
}

// ConvoLeaveConvo calls the XRPC procedure "chat.bsky.convo.leaveConvo".
func ConvoLeaveConvo(ctx context.Context, c *xrpc.Client, input *ConvoLeaveConvo_Input) (*ConvoLeaveConvo_Output, error) {
	var out ConvoLeaveConvo_Output
	return &out, c.Procedure(ctx, "chat.bsky.convo.leaveConvo", input, &out)
}
