// Code generated by lexgen. DO NOT EDIT.

package chatbsky

import (
	"context"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/atmos/xrpc"
)

// Precomputed JSON key tokens for ConvoGetConvo_Output.
var (
	jsonKey_ConvoGetConvo_Output_dollar_type = []byte("\"$type\":")
	jsonKey_ConvoGetConvo_Output_convo       = []byte("\"convo\":")
)

func (s *ConvoGetConvo_Output) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *ConvoGetConvo_Output) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_ConvoGetConvo_Output_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_ConvoGetConvo_Output_convo...)
	{
		var err error
		buf, err = s.Convo.AppendJSON(buf)
		if err != nil {
			return nil, err
		}
	}
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *ConvoGetConvo_Output) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *ConvoGetConvo_Output) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "convo":
			pos, err = s.Convo.UnmarshalJSONAt(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for ConvoGetConvo_Output.
var (
	cborKey_ConvoGetConvo_Output_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_ConvoGetConvo_Output_convo       = cbor.AppendTextKey(nil, "convo")
)

func (s *ConvoGetConvo_Output) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *ConvoGetConvo_Output) AppendCBOR(buf []byte) ([]byte, error) {
	n := 1 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_ConvoGetConvo_Output_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "convo", buf)
		buf = append(buf, cborKey_ConvoGetConvo_Output_convo...)
		{
			var err error
			buf, err = s.Convo.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_ConvoGetConvo_Output_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		buf = append(buf, cborKey_ConvoGetConvo_Output_convo...)
		{
			var err error
			buf, err = s.Convo.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
	}
	return buf, nil
}

func (s *ConvoGetConvo_Output) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *ConvoGetConvo_Output) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "convo" {
				pos, err = s.Convo.UnmarshalCBORAt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

type ConvoGetConvo_Output struct {
	LexiconTypeID string              `json:"$type,omitempty"`
	Convo         ConvoDefs_ConvoView `json:"convo"`

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// ConvoGetConvo calls the XRPC query "chat.bsky.convo.getConvo".
func ConvoGetConvo(ctx context.Context, c *xrpc.Client, convoId string) (*ConvoGetConvo_Output, error) {
	params := map[string]any{}
	params["convoId"] = convoId
	var out ConvoGetConvo_Output
	return &out, c.Query(ctx, "chat.bsky.convo.getConvo", params, &out)
}
