// Code generated by lexgen. DO NOT EDIT.

package chatbsky

import (
	"context"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/atmos/xrpc"
)

// Precomputed JSON key tokens for ConvoMuteConvo_Output.
var (
	jsonKey_ConvoMuteConvo_Output_dollar_type = []byte("\"$type\":")
	jsonKey_ConvoMuteConvo_Output_convo       = []byte("\"convo\":")
)

func (s *ConvoMuteConvo_Output) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *ConvoMuteConvo_Output) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_ConvoMuteConvo_Output_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_ConvoMuteConvo_Output_convo...)
	{
		var err error
		buf, err = s.Convo.AppendJSON(buf)
		if err != nil {
			return nil, err
		}
	}
	first = false
	buf = append(buf, '}')
	return buf, nil
}

func (s *ConvoMuteConvo_Output) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *ConvoMuteConvo_Output) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "convo":
			pos, err = s.Convo.UnmarshalJSONAt(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for ConvoMuteConvo_Output.
var (
	cborKey_ConvoMuteConvo_Output_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_ConvoMuteConvo_Output_convo       = cbor.AppendTextKey(nil, "convo")
)

func (s *ConvoMuteConvo_Output) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *ConvoMuteConvo_Output) AppendCBOR(buf []byte) ([]byte, error) {
	n := 1
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if s.LexiconTypeID != "" {
		buf = append(buf, cborKey_ConvoMuteConvo_Output_dollar_type...)
		buf = cbor.AppendText(buf, s.LexiconTypeID)
	}
	buf = append(buf, cborKey_ConvoMuteConvo_Output_convo...)
	{
		var err error
		buf, err = s.Convo.AppendCBOR(buf)
		if err != nil {
			return nil, err
		}
	}
	return buf, nil
}

func (s *ConvoMuteConvo_Output) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *ConvoMuteConvo_Output) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		key, newPos, err := cbor.ReadText(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
			if err != nil {
				return 0, err
			}
		case "convo":
			pos, err = s.Convo.UnmarshalCBORAt(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
	}
	return pos, nil
}

type ConvoMuteConvo_Output struct {
	LexiconTypeID string              `json:"$type,omitempty"`
	Convo         ConvoDefs_ConvoView `json:"convo"`
}

// Precomputed JSON key tokens for ConvoMuteConvo_Input.
var (
	jsonKey_ConvoMuteConvo_Input_dollar_type = []byte("\"$type\":")
	jsonKey_ConvoMuteConvo_Input_convoId     = []byte("\"convoId\":")
)

func (s *ConvoMuteConvo_Input) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *ConvoMuteConvo_Input) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_ConvoMuteConvo_Input_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_ConvoMuteConvo_Input_convoId...)
	buf = cbor.AppendJSONString(buf, s.ConvoId)
	first = false
	buf = append(buf, '}')
	return buf, nil
}

func (s *ConvoMuteConvo_Input) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *ConvoMuteConvo_Input) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "convoId":
			s.ConvoId, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for ConvoMuteConvo_Input.
var (
	cborKey_ConvoMuteConvo_Input_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_ConvoMuteConvo_Input_convoId     = cbor.AppendTextKey(nil, "convoId")
)

func (s *ConvoMuteConvo_Input) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *ConvoMuteConvo_Input) AppendCBOR(buf []byte) ([]byte, error) {
	n := 1
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if s.LexiconTypeID != "" {
		buf = append(buf, cborKey_ConvoMuteConvo_Input_dollar_type...)
		buf = cbor.AppendText(buf, s.LexiconTypeID)
	}
	buf = append(buf, cborKey_ConvoMuteConvo_Input_convoId...)
	buf = cbor.AppendText(buf, s.ConvoId)
	return buf, nil
}

func (s *ConvoMuteConvo_Input) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *ConvoMuteConvo_Input) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		key, newPos, err := cbor.ReadText(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
			if err != nil {
				return 0, err
			}
		case "convoId":
			s.ConvoId, pos, err = cbor.ReadText(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
	}
	return pos, nil
}

type ConvoMuteConvo_Input struct {
	LexiconTypeID string `json:"$type,omitempty"`
	ConvoId       string `json:"convoId"`
}

// ConvoMuteConvo calls the XRPC procedure "chat.bsky.convo.muteConvo".
func ConvoMuteConvo(ctx context.Context, c *xrpc.Client, input *ConvoMuteConvo_Input) (*ConvoMuteConvo_Output, error) {
	var out ConvoMuteConvo_Output
	return &out, c.Procedure(ctx, "chat.bsky.convo.muteConvo", input, &out)
}
