// Code generated by lexgen. DO NOT EDIT.

package chatbsky

import (
	"encoding/json"
	"fmt"
	lextypes "github.com/jcalabro/atmos/api/lextypes"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/gt"
)

// EmbedJoinLink is a "main" in the chat.bsky.embed.joinLink schema.
type EmbedJoinLink struct {
	LexiconTypeID string `json:"$type,omitempty"`
	Code          string `json:"code"` // The join link code.

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// Precomputed CBOR key tokens for EmbedJoinLink.
var (
	cborKey_EmbedJoinLink_code        = cbor.AppendTextKey(nil, "code")
	cborKey_EmbedJoinLink_dollar_type = cbor.AppendTextKey(nil, "$type")
)

func (s *EmbedJoinLink) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *EmbedJoinLink) AppendCBOR(buf []byte) ([]byte, error) {
	n := 1 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "code", buf)
		buf = append(buf, cborKey_EmbedJoinLink_code...)
		buf = cbor.AppendText(buf, s.Code)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_EmbedJoinLink_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		buf = append(buf, cborKey_EmbedJoinLink_code...)
		buf = cbor.AppendText(buf, s.Code)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_EmbedJoinLink_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
	}
	return buf, nil
}

func (s *EmbedJoinLink) UnmarshalCBOR(data []byte) error {
	pos, err := s.UnmarshalCBORAt(data, 0)
	if err != nil {
		return err
	}
	return cbor.CheckTrailingData(pos, len(data))
}

func (s *EmbedJoinLink) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	var prevKeyStart, prevKeyEnd int
	keyOrderValid := false
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		if keyOrderValid {
			if err := cbor.CheckMapKeyOrder(data, prevKeyStart, prevKeyEnd, keyStart, keyEnd); err != nil {
				return 0, err
			}
		}
		prevKeyStart, prevKeyEnd = keyStart, keyEnd
		keyOrderValid = true
		pos = newPos
		switch keyEnd - keyStart {
		case 4:
			if string(data[keyStart:keyEnd]) == "code" {
				s.Code, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

// Precomputed JSON key tokens for EmbedJoinLink.
var (
	jsonKey_EmbedJoinLink_dollar_type = []byte("\"$type\":")
	jsonKey_EmbedJoinLink_code        = []byte("\"code\":")
)

func (s *EmbedJoinLink) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *EmbedJoinLink) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_EmbedJoinLink_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_EmbedJoinLink_code...)
	buf = cbor.AppendJSONString(buf, s.Code)
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *EmbedJoinLink) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *EmbedJoinLink) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "code":
			s.Code, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// EmbedJoinLink_View is a "view" in the chat.bsky.embed.joinLink schema.
type EmbedJoinLink_View struct {
	LexiconTypeID   string                             `json:"$type,omitempty"`
	JoinLinkPreview EmbedJoinLink_View_JoinLinkPreview `json:"joinLinkPreview"`

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// EmbedJoinLink_View_JoinLinkPreview is a union type.
type EmbedJoinLink_View_JoinLinkPreview struct {
	GroupDefs_JoinLinkPreviewView         gt.Ref[GroupDefs_JoinLinkPreviewView]
	GroupDefs_DisabledJoinLinkPreviewView gt.Ref[GroupDefs_DisabledJoinLinkPreviewView]
	GroupDefs_InvalidJoinLinkPreviewView  gt.Ref[GroupDefs_InvalidJoinLinkPreviewView]
	Unknown                               gt.Ref[lextypes.UnknownUnionVariant]
}

func (u EmbedJoinLink_View_JoinLinkPreview) MarshalJSON() ([]byte, error) {
	return u.AppendJSON(make([]byte, 0, 256))
}

func (u EmbedJoinLink_View_JoinLinkPreview) AppendJSON(buf []byte) ([]byte, error) {
	if u.GroupDefs_JoinLinkPreviewView.HasVal() {
		v := *u.GroupDefs_JoinLinkPreviewView.Val()
		v.LexiconTypeID = "chat.bsky.group.defs#joinLinkPreviewView"
		return v.AppendJSON(buf)
	}
	if u.GroupDefs_DisabledJoinLinkPreviewView.HasVal() {
		v := *u.GroupDefs_DisabledJoinLinkPreviewView.Val()
		v.LexiconTypeID = "chat.bsky.group.defs#disabledJoinLinkPreviewView"
		return v.AppendJSON(buf)
	}
	if u.GroupDefs_InvalidJoinLinkPreviewView.HasVal() {
		v := *u.GroupDefs_InvalidJoinLinkPreviewView.Val()
		v.LexiconTypeID = "chat.bsky.group.defs#invalidJoinLinkPreviewView"
		return v.AppendJSON(buf)
	}
	if u.Unknown.HasVal() {
		return append(buf, u.Unknown.Val().Raw...), nil
	}
	return nil, fmt.Errorf("cannot marshal empty union EmbedJoinLink_View_JoinLinkPreview")
}

func (u *EmbedJoinLink_View_JoinLinkPreview) UnmarshalJSON(data []byte) error {
	_, err := u.UnmarshalJSONAt(data, 0)
	return err
}

func (u *EmbedJoinLink_View_JoinLinkPreview) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	endPos, err := cbor.SkipJSONValue(data, pos)
	if err != nil {
		return 0, err
	}
	typ, err := cbor.PeekJSONType(data[pos:endPos])
	if err != nil {
		return 0, err
	}
	switch typ {
	case "chat.bsky.group.defs#joinLinkPreviewView":
		var v GroupDefs_JoinLinkPreviewView
		endPos, err = v.UnmarshalJSONAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.GroupDefs_JoinLinkPreviewView = gt.SomeRef(v)
		return endPos, nil
	case "chat.bsky.group.defs#disabledJoinLinkPreviewView":
		var v GroupDefs_DisabledJoinLinkPreviewView
		endPos, err = v.UnmarshalJSONAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.GroupDefs_DisabledJoinLinkPreviewView = gt.SomeRef(v)
		return endPos, nil
	case "chat.bsky.group.defs#invalidJoinLinkPreviewView":
		var v GroupDefs_InvalidJoinLinkPreviewView
		endPos, err = v.UnmarshalJSONAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.GroupDefs_InvalidJoinLinkPreviewView = gt.SomeRef(v)
		return endPos, nil
	default:
		u.Unknown = gt.SomeRef(lextypes.UnknownUnionVariant{Type: typ, Raw: json.RawMessage(data[pos:endPos])})
		return endPos, nil
	}
}

func (u EmbedJoinLink_View_JoinLinkPreview) MarshalCBOR() ([]byte, error) {
	return u.AppendCBOR(make([]byte, 0, 256))
}

func (u EmbedJoinLink_View_JoinLinkPreview) AppendCBOR(buf []byte) ([]byte, error) {
	if u.GroupDefs_JoinLinkPreviewView.HasVal() {
		v := *u.GroupDefs_JoinLinkPreviewView.Val()
		v.LexiconTypeID = "chat.bsky.group.defs#joinLinkPreviewView"
		return v.AppendCBOR(buf)
	}
	if u.GroupDefs_DisabledJoinLinkPreviewView.HasVal() {
		v := *u.GroupDefs_DisabledJoinLinkPreviewView.Val()
		v.LexiconTypeID = "chat.bsky.group.defs#disabledJoinLinkPreviewView"
		return v.AppendCBOR(buf)
	}
	if u.GroupDefs_InvalidJoinLinkPreviewView.HasVal() {
		v := *u.GroupDefs_InvalidJoinLinkPreviewView.Val()
		v.LexiconTypeID = "chat.bsky.group.defs#invalidJoinLinkPreviewView"
		return v.AppendCBOR(buf)
	}
	if u.Unknown.HasVal() {
		return append(buf, u.Unknown.Val().RawCBOR...), nil
	}
	return nil, fmt.Errorf("cannot marshal empty union EmbedJoinLink_View_JoinLinkPreview")
}

func (u *EmbedJoinLink_View_JoinLinkPreview) UnmarshalCBOR(data []byte) error {
	pos, err := u.UnmarshalCBORAt(data, 0)
	if err != nil {
		return err
	}
	return cbor.CheckTrailingData(pos, len(data))
}

func (u *EmbedJoinLink_View_JoinLinkPreview) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	typ, err := cbor.PeekTypeAt(data, pos)
	if err != nil {
		return 0, err
	}
	switch typ {
	case "chat.bsky.group.defs#joinLinkPreviewView":
		var v GroupDefs_JoinLinkPreviewView
		pos, err = v.UnmarshalCBORAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.GroupDefs_JoinLinkPreviewView = gt.SomeRef(v)
		return pos, nil
	case "chat.bsky.group.defs#disabledJoinLinkPreviewView":
		var v GroupDefs_DisabledJoinLinkPreviewView
		pos, err = v.UnmarshalCBORAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.GroupDefs_DisabledJoinLinkPreviewView = gt.SomeRef(v)
		return pos, nil
	case "chat.bsky.group.defs#invalidJoinLinkPreviewView":
		var v GroupDefs_InvalidJoinLinkPreviewView
		pos, err = v.UnmarshalCBORAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.GroupDefs_InvalidJoinLinkPreviewView = gt.SomeRef(v)
		return pos, nil
	default:
		startPos := pos
		pos, err = cbor.SkipValue(data, pos)
		if err != nil {
			return 0, err
		}
		raw := make([]byte, pos-startPos)
		copy(raw, data[startPos:pos])
		u.Unknown = gt.SomeRef(lextypes.UnknownUnionVariant{Type: typ, RawCBOR: raw})
		return pos, nil
	}
}

// Precomputed CBOR key tokens for EmbedJoinLink_View.
var (
	cborKey_EmbedJoinLink_View_dollar_type     = cbor.AppendTextKey(nil, "$type")
	cborKey_EmbedJoinLink_View_joinLinkPreview = cbor.AppendTextKey(nil, "joinLinkPreview")
)

func (s *EmbedJoinLink_View) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *EmbedJoinLink_View) AppendCBOR(buf []byte) ([]byte, error) {
	n := 1 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_EmbedJoinLink_View_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "joinLinkPreview", buf)
		buf = append(buf, cborKey_EmbedJoinLink_View_joinLinkPreview...)
		{
			var err error
			buf, err = s.JoinLinkPreview.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_EmbedJoinLink_View_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		buf = append(buf, cborKey_EmbedJoinLink_View_joinLinkPreview...)
		{
			var err error
			buf, err = s.JoinLinkPreview.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
	}
	return buf, nil
}

func (s *EmbedJoinLink_View) UnmarshalCBOR(data []byte) error {
	pos, err := s.UnmarshalCBORAt(data, 0)
	if err != nil {
		return err
	}
	return cbor.CheckTrailingData(pos, len(data))
}

func (s *EmbedJoinLink_View) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	var prevKeyStart, prevKeyEnd int
	keyOrderValid := false
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		if keyOrderValid {
			if err := cbor.CheckMapKeyOrder(data, prevKeyStart, prevKeyEnd, keyStart, keyEnd); err != nil {
				return 0, err
			}
		}
		prevKeyStart, prevKeyEnd = keyStart, keyEnd
		keyOrderValid = true
		pos = newPos
		switch keyEnd - keyStart {
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 15:
			if string(data[keyStart:keyEnd]) == "joinLinkPreview" {
				pos, err = s.JoinLinkPreview.UnmarshalCBORAt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

// Precomputed JSON key tokens for EmbedJoinLink_View.
var (
	jsonKey_EmbedJoinLink_View_dollar_type     = []byte("\"$type\":")
	jsonKey_EmbedJoinLink_View_joinLinkPreview = []byte("\"joinLinkPreview\":")
)

func (s *EmbedJoinLink_View) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *EmbedJoinLink_View) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_EmbedJoinLink_View_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_EmbedJoinLink_View_joinLinkPreview...)
	{
		var err error
		buf, err = s.JoinLinkPreview.AppendJSON(buf)
		if err != nil {
			return nil, err
		}
	}
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *EmbedJoinLink_View) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *EmbedJoinLink_View) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "joinLinkPreview":
			pos, err = s.JoinLinkPreview.UnmarshalJSONAt(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}
