// Code generated by lexgen. DO NOT EDIT.

package chatbsky

import (
	"context"
	lextypes "github.com/jcalabro/atmos/api/lextypes"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/atmos/xrpc"
	"github.com/jcalabro/gt"
)

// Precomputed JSON key tokens for ModerationUpdateActorAccess_Input.
var (
	jsonKey_ModerationUpdateActorAccess_Input_dollar_type = []byte("\"$type\":")
	jsonKey_ModerationUpdateActorAccess_Input_actor       = []byte("\"actor\":")
	jsonKey_ModerationUpdateActorAccess_Input_allowAccess = []byte("\"allowAccess\":")
	jsonKey_ModerationUpdateActorAccess_Input_ref         = []byte("\"ref\":")
)

func (s *ModerationUpdateActorAccess_Input) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *ModerationUpdateActorAccess_Input) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_ModerationUpdateActorAccess_Input_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_ModerationUpdateActorAccess_Input_actor...)
	buf = cbor.AppendJSONString(buf, s.Actor)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_ModerationUpdateActorAccess_Input_allowAccess...)
	buf = cbor.AppendJSONBool(buf, s.AllowAccess)
	first = false
	if s.Ref.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_ModerationUpdateActorAccess_Input_ref...)
		buf = cbor.AppendJSONString(buf, s.Ref.Val())
		first = false
	}
	for _, ef := range s.extraJSON {
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *ModerationUpdateActorAccess_Input) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *ModerationUpdateActorAccess_Input) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extraJSON = nil
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "actor":
			s.Actor, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "allowAccess":
			s.AllowAccess, pos, err = cbor.ReadJSONBool(data, pos)
			if err != nil {
				return 0, err
			}
		case "ref":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v string
				v, pos, err = cbor.ReadJSONString(data, pos)
				if err != nil {
					return 0, err
				}
				s.Ref = gt.Some(v)
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extraJSON = append(s.extraJSON, lextypes.ExtraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...)})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for ModerationUpdateActorAccess_Input.
var (
	cborKey_ModerationUpdateActorAccess_Input_ref         = cbor.AppendTextKey(nil, "ref")
	cborKey_ModerationUpdateActorAccess_Input_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_ModerationUpdateActorAccess_Input_actor       = cbor.AppendTextKey(nil, "actor")
	cborKey_ModerationUpdateActorAccess_Input_allowAccess = cbor.AppendTextKey(nil, "allowAccess")
)

func (s *ModerationUpdateActorAccess_Input) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *ModerationUpdateActorAccess_Input) AppendCBOR(buf []byte) ([]byte, error) {
	n := 2 + len(s.extraCBOR)
	if s.Ref.HasVal() {
		n++
	}
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	ei := 0
	ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "ref", buf)
	if s.Ref.HasVal() {
		buf = append(buf, cborKey_ModerationUpdateActorAccess_Input_ref...)
		buf = cbor.AppendText(buf, s.Ref.Val())
	}
	ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "$type", buf)
	if s.LexiconTypeID != "" {
		buf = append(buf, cborKey_ModerationUpdateActorAccess_Input_dollar_type...)
		buf = cbor.AppendText(buf, s.LexiconTypeID)
	}
	ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "actor", buf)
	buf = append(buf, cborKey_ModerationUpdateActorAccess_Input_actor...)
	buf = cbor.AppendText(buf, s.Actor)
	ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "allowAccess", buf)
	buf = append(buf, cborKey_ModerationUpdateActorAccess_Input_allowAccess...)
	buf = cbor.AppendBool(buf, s.AllowAccess)
	_, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "", buf)
	return buf, nil
}

func (s *ModerationUpdateActorAccess_Input) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *ModerationUpdateActorAccess_Input) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extraCBOR = nil
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 3:
			if string(data[keyStart:keyEnd]) == "ref" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v string
					v, pos, err = cbor.ReadText(data, pos)
					if err != nil {
						return 0, err
					}
					s.Ref = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
			}
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "actor" {
				s.Actor, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
			}
		case 11:
			if string(data[keyStart:keyEnd]) == "allowAccess" {
				s.AllowAccess, pos, err = cbor.ReadBool(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
		}
	}
	return pos, nil
}

type ModerationUpdateActorAccess_Input struct {
	LexiconTypeID string            `json:"$type,omitempty"`
	Actor         string            `json:"actor"`
	AllowAccess   bool              `json:"allowAccess"`
	Ref           gt.Option[string] `json:"ref,omitzero"`

	// extraJSON and extraCBOR preserve unknown fields for same-format round-trips.
	extraJSON []lextypes.ExtraField
	extraCBOR []lextypes.ExtraField
}

// ModerationUpdateActorAccess calls the XRPC procedure "chat.bsky.moderation.updateActorAccess".
func ModerationUpdateActorAccess(ctx context.Context, c *xrpc.Client, input *ModerationUpdateActorAccess_Input) error {
	return c.Procedure(ctx, "chat.bsky.moderation.updateActorAccess", input, nil)
}
