// Code generated by lexgen. DO NOT EDIT.

package comatproto

import (
	"context"
	"encoding/json"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/atmos/xrpc"
	"github.com/jcalabro/gt"
)

// Precomputed JSON key tokens for IdentitySignPlcOperation_Output.
var (
	jsonKey_IdentitySignPlcOperation_Output_dollar_type = []byte("\"$type\":")
	jsonKey_IdentitySignPlcOperation_Output_operation   = []byte("\"operation\":")
)

func (s *IdentitySignPlcOperation_Output) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *IdentitySignPlcOperation_Output) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_IdentitySignPlcOperation_Output_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_IdentitySignPlcOperation_Output_operation...)
	buf = append(buf, s.Operation...)
	first = false
	buf = append(buf, '}')
	return buf, nil
}

func (s *IdentitySignPlcOperation_Output) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *IdentitySignPlcOperation_Output) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "operation":
			{
				start := pos
				pos, err = cbor.SkipJSONValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.Operation = json.RawMessage(data[start:pos])
			}
		default:
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for IdentitySignPlcOperation_Output.
var (
	cborKey_IdentitySignPlcOperation_Output_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_IdentitySignPlcOperation_Output_operation   = cbor.AppendTextKey(nil, "operation")
)

func (s *IdentitySignPlcOperation_Output) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *IdentitySignPlcOperation_Output) AppendCBOR(buf []byte) ([]byte, error) {
	n := 1
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if s.LexiconTypeID != "" {
		buf = append(buf, cborKey_IdentitySignPlcOperation_Output_dollar_type...)
		buf = cbor.AppendText(buf, s.LexiconTypeID)
	}
	buf = append(buf, cborKey_IdentitySignPlcOperation_Output_operation...)
	buf = cbor.AppendNull(buf)
	return buf, nil
}

func (s *IdentitySignPlcOperation_Output) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *IdentitySignPlcOperation_Output) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		key, newPos, err := cbor.ReadText(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
			if err != nil {
				return 0, err
			}
		case "operation":
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
	}
	return pos, nil
}

type IdentitySignPlcOperation_Output struct {
	LexiconTypeID string          `json:"$type,omitempty"`
	Operation     json.RawMessage `json:"operation"` // A signed DID PLC operation.
}

// Precomputed JSON key tokens for IdentitySignPlcOperation_Input.
var (
	jsonKey_IdentitySignPlcOperation_Input_dollar_type         = []byte("\"$type\":")
	jsonKey_IdentitySignPlcOperation_Input_alsoKnownAs         = []byte("\"alsoKnownAs\":")
	jsonKey_IdentitySignPlcOperation_Input_rotationKeys        = []byte("\"rotationKeys\":")
	jsonKey_IdentitySignPlcOperation_Input_services            = []byte("\"services\":")
	jsonKey_IdentitySignPlcOperation_Input_token               = []byte("\"token\":")
	jsonKey_IdentitySignPlcOperation_Input_verificationMethods = []byte("\"verificationMethods\":")
)

func (s *IdentitySignPlcOperation_Input) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *IdentitySignPlcOperation_Input) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_IdentitySignPlcOperation_Input_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if len(s.AlsoKnownAs) > 0 {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_IdentitySignPlcOperation_Input_alsoKnownAs...)
		buf = append(buf, '[')
		for i, item := range s.AlsoKnownAs {
			if i > 0 {
				buf = append(buf, ',')
			}
			buf = cbor.AppendJSONString(buf, item)
		}
		buf = append(buf, ']')
		first = false
	}
	if len(s.RotationKeys) > 0 {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_IdentitySignPlcOperation_Input_rotationKeys...)
		buf = append(buf, '[')
		for i, item := range s.RotationKeys {
			if i > 0 {
				buf = append(buf, ',')
			}
			buf = cbor.AppendJSONString(buf, item)
		}
		buf = append(buf, ']')
		first = false
	}
	if true {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_IdentitySignPlcOperation_Input_services...)
		buf = append(buf, s.Services...)
		first = false
	}
	if s.Token.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_IdentitySignPlcOperation_Input_token...)
		buf = cbor.AppendJSONString(buf, s.Token.Val())
		first = false
	}
	if true {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_IdentitySignPlcOperation_Input_verificationMethods...)
		buf = append(buf, s.VerificationMethods...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *IdentitySignPlcOperation_Input) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *IdentitySignPlcOperation_Input) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "alsoKnownAs":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.AlsoKnownAs = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem string
					elem, pos, err = cbor.ReadJSONString(data, pos)
					if err != nil {
						return 0, err
					}
					s.AlsoKnownAs = append(s.AlsoKnownAs, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case "rotationKeys":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.RotationKeys = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem string
					elem, pos, err = cbor.ReadJSONString(data, pos)
					if err != nil {
						return 0, err
					}
					s.RotationKeys = append(s.RotationKeys, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case "services":
			{
				start := pos
				pos, err = cbor.SkipJSONValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.Services = json.RawMessage(data[start:pos])
			}
		case "token":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v string
				v, pos, err = cbor.ReadJSONString(data, pos)
				if err != nil {
					return 0, err
				}
				s.Token = gt.Some(v)
			}
		case "verificationMethods":
			{
				start := pos
				pos, err = cbor.SkipJSONValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.VerificationMethods = json.RawMessage(data[start:pos])
			}
		default:
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for IdentitySignPlcOperation_Input.
var (
	cborKey_IdentitySignPlcOperation_Input_dollar_type         = cbor.AppendTextKey(nil, "$type")
	cborKey_IdentitySignPlcOperation_Input_token               = cbor.AppendTextKey(nil, "token")
	cborKey_IdentitySignPlcOperation_Input_services            = cbor.AppendTextKey(nil, "services")
	cborKey_IdentitySignPlcOperation_Input_alsoKnownAs         = cbor.AppendTextKey(nil, "alsoKnownAs")
	cborKey_IdentitySignPlcOperation_Input_rotationKeys        = cbor.AppendTextKey(nil, "rotationKeys")
	cborKey_IdentitySignPlcOperation_Input_verificationMethods = cbor.AppendTextKey(nil, "verificationMethods")
)

func (s *IdentitySignPlcOperation_Input) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *IdentitySignPlcOperation_Input) AppendCBOR(buf []byte) ([]byte, error) {
	n := 0
	if s.LexiconTypeID != "" {
		n++
	}
	if s.Token.HasVal() {
		n++
	}
	if true {
		n++
	}
	if len(s.AlsoKnownAs) > 0 {
		n++
	}
	if len(s.RotationKeys) > 0 {
		n++
	}
	if true {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if s.LexiconTypeID != "" {
		buf = append(buf, cborKey_IdentitySignPlcOperation_Input_dollar_type...)
		buf = cbor.AppendText(buf, s.LexiconTypeID)
	}
	if s.Token.HasVal() {
		buf = append(buf, cborKey_IdentitySignPlcOperation_Input_token...)
		buf = cbor.AppendText(buf, s.Token.Val())
	}
	if true {
		buf = append(buf, cborKey_IdentitySignPlcOperation_Input_services...)
		buf = cbor.AppendNull(buf)
	}
	if len(s.AlsoKnownAs) > 0 {
		buf = append(buf, cborKey_IdentitySignPlcOperation_Input_alsoKnownAs...)
		buf = cbor.AppendArrayHeader(buf, uint64(len(s.AlsoKnownAs)))
		for _, item := range s.AlsoKnownAs {
			buf = cbor.AppendText(buf, item)
		}
	}
	if len(s.RotationKeys) > 0 {
		buf = append(buf, cborKey_IdentitySignPlcOperation_Input_rotationKeys...)
		buf = cbor.AppendArrayHeader(buf, uint64(len(s.RotationKeys)))
		for _, item := range s.RotationKeys {
			buf = cbor.AppendText(buf, item)
		}
	}
	if true {
		buf = append(buf, cborKey_IdentitySignPlcOperation_Input_verificationMethods...)
		buf = cbor.AppendNull(buf)
	}
	return buf, nil
}

func (s *IdentitySignPlcOperation_Input) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *IdentitySignPlcOperation_Input) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		key, newPos, err := cbor.ReadText(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
			if err != nil {
				return 0, err
			}
		case "token":
			if cbor.IsNull(data, pos) {
				pos++
			} else {
				var v string
				v, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
				s.Token = gt.Some(v)
			}
		case "services":
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
		case "alsoKnownAs":
			{
				arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
				if err != nil {
					return 0, err
				}
				pos = newPos
				s.AlsoKnownAs = make([]string, arrLen)
				for idx := range arrLen {
					s.AlsoKnownAs[idx], pos, err = cbor.ReadText(data, pos)
					if err != nil {
						return 0, err
					}
				}
			}
		case "rotationKeys":
			{
				arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
				if err != nil {
					return 0, err
				}
				pos = newPos
				s.RotationKeys = make([]string, arrLen)
				for idx := range arrLen {
					s.RotationKeys[idx], pos, err = cbor.ReadText(data, pos)
					if err != nil {
						return 0, err
					}
				}
			}
		case "verificationMethods":
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
	}
	return pos, nil
}

type IdentitySignPlcOperation_Input struct {
	LexiconTypeID       string            `json:"$type,omitempty"`
	AlsoKnownAs         []string          `json:"alsoKnownAs,omitempty"`
	RotationKeys        []string          `json:"rotationKeys,omitempty"`
	Services            json.RawMessage   `json:"services,omitempty"`
	Token               gt.Option[string] `json:"token,omitzero"` // A token received through com.atproto.identity.requestPlcOperationSignature
	VerificationMethods json.RawMessage   `json:"verificationMethods,omitempty"`
}

// IdentitySignPlcOperation calls the XRPC procedure "com.atproto.identity.signPlcOperation".
//
// Signs a PLC operation to update some value(s) in the requesting DID's document.
func IdentitySignPlcOperation(ctx context.Context, c *xrpc.Client, input *IdentitySignPlcOperation_Input) (*IdentitySignPlcOperation_Output, error) {
	var out IdentitySignPlcOperation_Output
	return &out, c.Procedure(ctx, "com.atproto.identity.signPlcOperation", input, &out)
}
