// Code generated by lexgen. DO NOT EDIT.

package comatproto

import (
	"context"
	"github.com/jcalabro/atmos/xrpc"
)

// IdentityRequestPlcOperationSignature calls the XRPC procedure "com.atproto.identity.requestPlcOperationSignature".
//
// Request an email with a code to in order to request a signed PLC operation. Requires Auth.
func IdentityRequestPlcOperationSignature(ctx context.Context, c *xrpc.Client) error {
	return c.Procedure(ctx, "com.atproto.identity.requestPlcOperationSignature", nil, nil)
}
