// Code generated by lexgen. DO NOT EDIT.

package comatproto

import (
	"context"
	"encoding/json"
	lextypes "github.com/jcalabro/atmos/api/lextypes"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/atmos/xrpc"
)

// Precomputed JSON key tokens for IdentityGetRecommendedDidCredentials_Output.
var (
	jsonKey_IdentityGetRecommendedDidCredentials_Output_dollar_type         = []byte("\"$type\":")
	jsonKey_IdentityGetRecommendedDidCredentials_Output_alsoKnownAs         = []byte("\"alsoKnownAs\":")
	jsonKey_IdentityGetRecommendedDidCredentials_Output_rotationKeys        = []byte("\"rotationKeys\":")
	jsonKey_IdentityGetRecommendedDidCredentials_Output_services            = []byte("\"services\":")
	jsonKey_IdentityGetRecommendedDidCredentials_Output_verificationMethods = []byte("\"verificationMethods\":")
)

func (s *IdentityGetRecommendedDidCredentials_Output) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *IdentityGetRecommendedDidCredentials_Output) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_IdentityGetRecommendedDidCredentials_Output_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if len(s.AlsoKnownAs) > 0 {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_IdentityGetRecommendedDidCredentials_Output_alsoKnownAs...)
		buf = append(buf, '[')
		for i, item := range s.AlsoKnownAs {
			if i > 0 {
				buf = append(buf, ',')
			}
			buf = cbor.AppendJSONString(buf, item)
		}
		buf = append(buf, ']')
		first = false
	}
	if len(s.RotationKeys) > 0 {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_IdentityGetRecommendedDidCredentials_Output_rotationKeys...)
		buf = append(buf, '[')
		for i, item := range s.RotationKeys {
			if i > 0 {
				buf = append(buf, ',')
			}
			buf = cbor.AppendJSONString(buf, item)
		}
		buf = append(buf, ']')
		first = false
	}
	if true {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_IdentityGetRecommendedDidCredentials_Output_services...)
		buf = append(buf, s.Services...)
		first = false
	}
	if true {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_IdentityGetRecommendedDidCredentials_Output_verificationMethods...)
		buf = append(buf, s.VerificationMethods...)
		first = false
	}
	for _, ef := range s.extraJSON {
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *IdentityGetRecommendedDidCredentials_Output) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *IdentityGetRecommendedDidCredentials_Output) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extraJSON = nil
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "alsoKnownAs":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.AlsoKnownAs = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem string
					elem, pos, err = cbor.ReadJSONString(data, pos)
					if err != nil {
						return 0, err
					}
					s.AlsoKnownAs = append(s.AlsoKnownAs, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case "rotationKeys":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.RotationKeys = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem string
					elem, pos, err = cbor.ReadJSONString(data, pos)
					if err != nil {
						return 0, err
					}
					s.RotationKeys = append(s.RotationKeys, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case "services":
			{
				start := pos
				pos, err = cbor.SkipJSONValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.Services = json.RawMessage(data[start:pos])
			}
		case "verificationMethods":
			{
				start := pos
				pos, err = cbor.SkipJSONValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.VerificationMethods = json.RawMessage(data[start:pos])
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extraJSON = append(s.extraJSON, lextypes.ExtraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...)})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for IdentityGetRecommendedDidCredentials_Output.
var (
	cborKey_IdentityGetRecommendedDidCredentials_Output_dollar_type         = cbor.AppendTextKey(nil, "$type")
	cborKey_IdentityGetRecommendedDidCredentials_Output_services            = cbor.AppendTextKey(nil, "services")
	cborKey_IdentityGetRecommendedDidCredentials_Output_alsoKnownAs         = cbor.AppendTextKey(nil, "alsoKnownAs")
	cborKey_IdentityGetRecommendedDidCredentials_Output_rotationKeys        = cbor.AppendTextKey(nil, "rotationKeys")
	cborKey_IdentityGetRecommendedDidCredentials_Output_verificationMethods = cbor.AppendTextKey(nil, "verificationMethods")
)

func (s *IdentityGetRecommendedDidCredentials_Output) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *IdentityGetRecommendedDidCredentials_Output) AppendCBOR(buf []byte) ([]byte, error) {
	n := 0 + len(s.extraCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	if true {
		n++
	}
	if len(s.AlsoKnownAs) > 0 {
		n++
	}
	if len(s.RotationKeys) > 0 {
		n++
	}
	if true {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extraCBOR) > 0 {
		ei := 0
		ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_IdentityGetRecommendedDidCredentials_Output_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "services", buf)
		if true {
			buf = append(buf, cborKey_IdentityGetRecommendedDidCredentials_Output_services...)
			buf = cbor.AppendNull(buf)
		}
		ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "alsoKnownAs", buf)
		if len(s.AlsoKnownAs) > 0 {
			buf = append(buf, cborKey_IdentityGetRecommendedDidCredentials_Output_alsoKnownAs...)
			buf = cbor.AppendArrayHeader(buf, uint64(len(s.AlsoKnownAs)))
			for _, item := range s.AlsoKnownAs {
				buf = cbor.AppendText(buf, item)
			}
		}
		ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "rotationKeys", buf)
		if len(s.RotationKeys) > 0 {
			buf = append(buf, cborKey_IdentityGetRecommendedDidCredentials_Output_rotationKeys...)
			buf = cbor.AppendArrayHeader(buf, uint64(len(s.RotationKeys)))
			for _, item := range s.RotationKeys {
				buf = cbor.AppendText(buf, item)
			}
		}
		ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "verificationMethods", buf)
		if true {
			buf = append(buf, cborKey_IdentityGetRecommendedDidCredentials_Output_verificationMethods...)
			buf = cbor.AppendNull(buf)
		}
		_, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "", buf)
	} else {
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_IdentityGetRecommendedDidCredentials_Output_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		if true {
			buf = append(buf, cborKey_IdentityGetRecommendedDidCredentials_Output_services...)
			buf = cbor.AppendNull(buf)
		}
		if len(s.AlsoKnownAs) > 0 {
			buf = append(buf, cborKey_IdentityGetRecommendedDidCredentials_Output_alsoKnownAs...)
			buf = cbor.AppendArrayHeader(buf, uint64(len(s.AlsoKnownAs)))
			for _, item := range s.AlsoKnownAs {
				buf = cbor.AppendText(buf, item)
			}
		}
		if len(s.RotationKeys) > 0 {
			buf = append(buf, cborKey_IdentityGetRecommendedDidCredentials_Output_rotationKeys...)
			buf = cbor.AppendArrayHeader(buf, uint64(len(s.RotationKeys)))
			for _, item := range s.RotationKeys {
				buf = cbor.AppendText(buf, item)
			}
		}
		if true {
			buf = append(buf, cborKey_IdentityGetRecommendedDidCredentials_Output_verificationMethods...)
			buf = cbor.AppendNull(buf)
		}
	}
	return buf, nil
}

func (s *IdentityGetRecommendedDidCredentials_Output) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *IdentityGetRecommendedDidCredentials_Output) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extraCBOR = nil
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
			}
		case 8:
			if string(data[keyStart:keyEnd]) == "services" {
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
			}
		case 11:
			if string(data[keyStart:keyEnd]) == "alsoKnownAs" {
				{
					arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
					if err != nil {
						return 0, err
					}
					pos = newPos
					s.AlsoKnownAs = make([]string, arrLen)
					for idx := range arrLen {
						s.AlsoKnownAs[idx], pos, err = cbor.ReadText(data, pos)
						if err != nil {
							return 0, err
						}
					}
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
			}
		case 12:
			if string(data[keyStart:keyEnd]) == "rotationKeys" {
				{
					arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
					if err != nil {
						return 0, err
					}
					pos = newPos
					s.RotationKeys = make([]string, arrLen)
					for idx := range arrLen {
						s.RotationKeys[idx], pos, err = cbor.ReadText(data, pos)
						if err != nil {
							return 0, err
						}
					}
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
			}
		case 19:
			if string(data[keyStart:keyEnd]) == "verificationMethods" {
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
		}
	}
	return pos, nil
}

type IdentityGetRecommendedDidCredentials_Output struct {
	LexiconTypeID       string          `json:"$type,omitempty"`
	AlsoKnownAs         []string        `json:"alsoKnownAs,omitempty"`
	RotationKeys        []string        `json:"rotationKeys,omitempty"` // Recommended rotation keys for PLC dids. Should be undefined (or ignored) for did:webs.
	Services            json.RawMessage `json:"services,omitempty"`
	VerificationMethods json.RawMessage `json:"verificationMethods,omitempty"`

	// extraJSON and extraCBOR preserve unknown fields for same-format round-trips.
	extraJSON []lextypes.ExtraField
	extraCBOR []lextypes.ExtraField
}

// IdentityGetRecommendedDidCredentials calls the XRPC query "com.atproto.identity.getRecommendedDidCredentials".
//
// Describe the credentials that should be included in the DID doc of an account that is migrating to this service.
func IdentityGetRecommendedDidCredentials(ctx context.Context, c *xrpc.Client) (*IdentityGetRecommendedDidCredentials_Output, error) {
	var out IdentityGetRecommendedDidCredentials_Output
	return &out, c.Query(ctx, "com.atproto.identity.getRecommendedDidCredentials", nil, &out)
}
