// Code generated by lexgen. DO NOT EDIT.

package comatproto

import (
	"context"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/atmos/xrpc"
)

// Precomputed JSON key tokens for IdentityUpdateHandle_Input.
var (
	jsonKey_IdentityUpdateHandle_Input_dollar_type = []byte("\"$type\":")
	jsonKey_IdentityUpdateHandle_Input_handle      = []byte("\"handle\":")
)

func (s *IdentityUpdateHandle_Input) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *IdentityUpdateHandle_Input) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_IdentityUpdateHandle_Input_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_IdentityUpdateHandle_Input_handle...)
	buf = cbor.AppendJSONString(buf, s.Handle)
	first = false
	buf = append(buf, '}')
	return buf, nil
}

func (s *IdentityUpdateHandle_Input) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *IdentityUpdateHandle_Input) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "handle":
			s.Handle, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for IdentityUpdateHandle_Input.
var (
	cborKey_IdentityUpdateHandle_Input_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_IdentityUpdateHandle_Input_handle      = cbor.AppendTextKey(nil, "handle")
)

func (s *IdentityUpdateHandle_Input) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *IdentityUpdateHandle_Input) AppendCBOR(buf []byte) ([]byte, error) {
	n := 1
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if s.LexiconTypeID != "" {
		buf = append(buf, cborKey_IdentityUpdateHandle_Input_dollar_type...)
		buf = cbor.AppendText(buf, s.LexiconTypeID)
	}
	buf = append(buf, cborKey_IdentityUpdateHandle_Input_handle...)
	buf = cbor.AppendText(buf, s.Handle)
	return buf, nil
}

func (s *IdentityUpdateHandle_Input) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *IdentityUpdateHandle_Input) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		key, newPos, err := cbor.ReadText(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
			if err != nil {
				return 0, err
			}
		case "handle":
			s.Handle, pos, err = cbor.ReadText(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
	}
	return pos, nil
}

type IdentityUpdateHandle_Input struct {
	LexiconTypeID string `json:"$type,omitempty"`
	Handle        string `json:"handle"` // The new handle.
}

// IdentityUpdateHandle calls the XRPC procedure "com.atproto.identity.updateHandle".
//
// Updates the current account's handle. Verifies handle validity, and updates did:plc document if necessary. Implemented by PDS, and requires auth.
func IdentityUpdateHandle(ctx context.Context, c *xrpc.Client, input *IdentityUpdateHandle_Input) error {
	return c.Procedure(ctx, "com.atproto.identity.updateHandle", input, nil)
}
