// Code generated by lexgen. DO NOT EDIT.

package comatproto

import (
	"context"
	"github.com/jcalabro/atmos/xrpc"
	"io"
)

// RepoImportRepo calls the XRPC procedure "com.atproto.repo.importRepo".
//
// Import a repo in the form of a CAR file. Requires Content-Length HTTP header to be set.
func RepoImportRepo(ctx context.Context, c *xrpc.Client, contentType string, body io.Reader) error {
	return c.Do(ctx, "POST", "com.atproto.repo.importRepo", contentType, nil, body, nil)
}
