// Code generated by lexgen. DO NOT EDIT.

package comatproto

import (
	"context"
	"github.com/jcalabro/atmos/xrpc"
)

// Error name constants for ServerDeleteSession.
const (
	ErrServerDeleteSession_InvalidToken = "InvalidToken"
	ErrServerDeleteSession_ExpiredToken = "ExpiredToken"
)

// ServerDeleteSession calls the XRPC procedure "com.atproto.server.deleteSession".
//
// Delete the current session. Requires auth using the 'refreshJwt' (not the 'accessJwt').
func ServerDeleteSession(ctx context.Context, c *xrpc.Client) error {
	return c.Procedure(ctx, "com.atproto.server.deleteSession", nil, nil)
}
