// Code generated by lexgen. DO NOT EDIT.

package comatproto

import (
	"context"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/atmos/xrpc"
)

// Precomputed JSON key tokens for ServerCheckAccountStatus_Output.
var (
	jsonKey_ServerCheckAccountStatus_Output_dollar_type        = []byte("\"$type\":")
	jsonKey_ServerCheckAccountStatus_Output_activated          = []byte("\"activated\":")
	jsonKey_ServerCheckAccountStatus_Output_expectedBlobs      = []byte("\"expectedBlobs\":")
	jsonKey_ServerCheckAccountStatus_Output_importedBlobs      = []byte("\"importedBlobs\":")
	jsonKey_ServerCheckAccountStatus_Output_indexedRecords     = []byte("\"indexedRecords\":")
	jsonKey_ServerCheckAccountStatus_Output_privateStateValues = []byte("\"privateStateValues\":")
	jsonKey_ServerCheckAccountStatus_Output_repoBlocks         = []byte("\"repoBlocks\":")
	jsonKey_ServerCheckAccountStatus_Output_repoCommit         = []byte("\"repoCommit\":")
	jsonKey_ServerCheckAccountStatus_Output_repoRev            = []byte("\"repoRev\":")
	jsonKey_ServerCheckAccountStatus_Output_validDid           = []byte("\"validDid\":")
)

func (s *ServerCheckAccountStatus_Output) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *ServerCheckAccountStatus_Output) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_ServerCheckAccountStatus_Output_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_ServerCheckAccountStatus_Output_activated...)
	buf = cbor.AppendJSONBool(buf, s.Activated)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_ServerCheckAccountStatus_Output_expectedBlobs...)
	buf = cbor.AppendJSONInt(buf, s.ExpectedBlobs)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_ServerCheckAccountStatus_Output_importedBlobs...)
	buf = cbor.AppendJSONInt(buf, s.ImportedBlobs)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_ServerCheckAccountStatus_Output_indexedRecords...)
	buf = cbor.AppendJSONInt(buf, s.IndexedRecords)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_ServerCheckAccountStatus_Output_privateStateValues...)
	buf = cbor.AppendJSONInt(buf, s.PrivateStateValues)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_ServerCheckAccountStatus_Output_repoBlocks...)
	buf = cbor.AppendJSONInt(buf, s.RepoBlocks)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_ServerCheckAccountStatus_Output_repoCommit...)
	buf = cbor.AppendJSONString(buf, s.RepoCommit)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_ServerCheckAccountStatus_Output_repoRev...)
	buf = cbor.AppendJSONString(buf, s.RepoRev)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_ServerCheckAccountStatus_Output_validDid...)
	buf = cbor.AppendJSONBool(buf, s.ValidDid)
	first = false
	buf = append(buf, '}')
	return buf, nil
}

func (s *ServerCheckAccountStatus_Output) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *ServerCheckAccountStatus_Output) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "activated":
			s.Activated, pos, err = cbor.ReadJSONBool(data, pos)
			if err != nil {
				return 0, err
			}
		case "expectedBlobs":
			s.ExpectedBlobs, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "importedBlobs":
			s.ImportedBlobs, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "indexedRecords":
			s.IndexedRecords, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "privateStateValues":
			s.PrivateStateValues, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "repoBlocks":
			s.RepoBlocks, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "repoCommit":
			s.RepoCommit, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "repoRev":
			s.RepoRev, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "validDid":
			s.ValidDid, pos, err = cbor.ReadJSONBool(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for ServerCheckAccountStatus_Output.
var (
	cborKey_ServerCheckAccountStatus_Output_dollar_type        = cbor.AppendTextKey(nil, "$type")
	cborKey_ServerCheckAccountStatus_Output_repoRev            = cbor.AppendTextKey(nil, "repoRev")
	cborKey_ServerCheckAccountStatus_Output_validDid           = cbor.AppendTextKey(nil, "validDid")
	cborKey_ServerCheckAccountStatus_Output_activated          = cbor.AppendTextKey(nil, "activated")
	cborKey_ServerCheckAccountStatus_Output_repoBlocks         = cbor.AppendTextKey(nil, "repoBlocks")
	cborKey_ServerCheckAccountStatus_Output_repoCommit         = cbor.AppendTextKey(nil, "repoCommit")
	cborKey_ServerCheckAccountStatus_Output_expectedBlobs      = cbor.AppendTextKey(nil, "expectedBlobs")
	cborKey_ServerCheckAccountStatus_Output_importedBlobs      = cbor.AppendTextKey(nil, "importedBlobs")
	cborKey_ServerCheckAccountStatus_Output_indexedRecords     = cbor.AppendTextKey(nil, "indexedRecords")
	cborKey_ServerCheckAccountStatus_Output_privateStateValues = cbor.AppendTextKey(nil, "privateStateValues")
)

func (s *ServerCheckAccountStatus_Output) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *ServerCheckAccountStatus_Output) AppendCBOR(buf []byte) ([]byte, error) {
	n := 9
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if s.LexiconTypeID != "" {
		buf = append(buf, cborKey_ServerCheckAccountStatus_Output_dollar_type...)
		buf = cbor.AppendText(buf, s.LexiconTypeID)
	}
	buf = append(buf, cborKey_ServerCheckAccountStatus_Output_repoRev...)
	buf = cbor.AppendText(buf, s.RepoRev)
	buf = append(buf, cborKey_ServerCheckAccountStatus_Output_validDid...)
	buf = cbor.AppendBool(buf, s.ValidDid)
	buf = append(buf, cborKey_ServerCheckAccountStatus_Output_activated...)
	buf = cbor.AppendBool(buf, s.Activated)
	buf = append(buf, cborKey_ServerCheckAccountStatus_Output_repoBlocks...)
	buf = cbor.AppendInt(buf, s.RepoBlocks)
	buf = append(buf, cborKey_ServerCheckAccountStatus_Output_repoCommit...)
	buf = cbor.AppendText(buf, s.RepoCommit)
	buf = append(buf, cborKey_ServerCheckAccountStatus_Output_expectedBlobs...)
	buf = cbor.AppendInt(buf, s.ExpectedBlobs)
	buf = append(buf, cborKey_ServerCheckAccountStatus_Output_importedBlobs...)
	buf = cbor.AppendInt(buf, s.ImportedBlobs)
	buf = append(buf, cborKey_ServerCheckAccountStatus_Output_indexedRecords...)
	buf = cbor.AppendInt(buf, s.IndexedRecords)
	buf = append(buf, cborKey_ServerCheckAccountStatus_Output_privateStateValues...)
	buf = cbor.AppendInt(buf, s.PrivateStateValues)
	return buf, nil
}

func (s *ServerCheckAccountStatus_Output) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *ServerCheckAccountStatus_Output) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case 7:
			if string(data[keyStart:keyEnd]) == "repoRev" {
				s.RepoRev, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case 8:
			if string(data[keyStart:keyEnd]) == "validDid" {
				s.ValidDid, pos, err = cbor.ReadBool(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case 9:
			if string(data[keyStart:keyEnd]) == "activated" {
				s.Activated, pos, err = cbor.ReadBool(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case 10:
			if string(data[keyStart:keyEnd]) == "repoBlocks" {
				s.RepoBlocks, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "repoCommit" {
				s.RepoCommit, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case 13:
			if string(data[keyStart:keyEnd]) == "expectedBlobs" {
				s.ExpectedBlobs, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "importedBlobs" {
				s.ImportedBlobs, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case 14:
			if string(data[keyStart:keyEnd]) == "indexedRecords" {
				s.IndexedRecords, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case 18:
			if string(data[keyStart:keyEnd]) == "privateStateValues" {
				s.PrivateStateValues, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
			}
		default:
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
	}
	return pos, nil
}

type ServerCheckAccountStatus_Output struct {
	LexiconTypeID      string `json:"$type,omitempty"`
	Activated          bool   `json:"activated"`
	ExpectedBlobs      int64  `json:"expectedBlobs"`
	ImportedBlobs      int64  `json:"importedBlobs"`
	IndexedRecords     int64  `json:"indexedRecords"`
	PrivateStateValues int64  `json:"privateStateValues"`
	RepoBlocks         int64  `json:"repoBlocks"`
	RepoCommit         string `json:"repoCommit"`
	RepoRev            string `json:"repoRev"`
	ValidDid           bool   `json:"validDid"`
}

// ServerCheckAccountStatus calls the XRPC query "com.atproto.server.checkAccountStatus".
//
// Returns the status of an account, especially as pertaining to import or recovery. Can be called many times over the course of an account migration. Requires auth and can only be called pertaining to oneself.
func ServerCheckAccountStatus(ctx context.Context, c *xrpc.Client) (*ServerCheckAccountStatus_Output, error) {
	var out ServerCheckAccountStatus_Output
	return &out, c.Query(ctx, "com.atproto.server.checkAccountStatus", nil, &out)
}
