// Code generated by lexgen. DO NOT EDIT.

package comatproto

import (
	"context"
	"github.com/jcalabro/atmos/xrpc"
)

// ServerActivateAccount calls the XRPC procedure "com.atproto.server.activateAccount".
//
// Activates a currently deactivated account. Used to finalize account migration after the account's repo is imported and identity is setup.
func ServerActivateAccount(ctx context.Context, c *xrpc.Client) error {
	return c.Procedure(ctx, "com.atproto.server.activateAccount", nil, nil)
}
