// Code generated by lexgen. DO NOT EDIT.

package comatproto

import (
	"context"
	"github.com/jcalabro/gt"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/atmos/xrpc"
)

// Precomputed JSON key tokens for ServerCreateInviteCode_Output.
var (
	jsonKey_ServerCreateInviteCode_Output_dollar_type = []byte("\"$type\":")
	jsonKey_ServerCreateInviteCode_Output_code        = []byte("\"code\":")
)

func (s *ServerCreateInviteCode_Output) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *ServerCreateInviteCode_Output) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_ServerCreateInviteCode_Output_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_ServerCreateInviteCode_Output_code...)
	buf = cbor.AppendJSONString(buf, s.Code)
	first = false
	buf = append(buf, '}')
	return buf, nil
}

func (s *ServerCreateInviteCode_Output) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *ServerCreateInviteCode_Output) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "code":
			s.Code, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for ServerCreateInviteCode_Output.
var (
	cborKey_ServerCreateInviteCode_Output_code        = cbor.AppendTextKey(nil, "code")
	cborKey_ServerCreateInviteCode_Output_dollar_type = cbor.AppendTextKey(nil, "$type")
)

func (s *ServerCreateInviteCode_Output) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *ServerCreateInviteCode_Output) AppendCBOR(buf []byte) ([]byte, error) {
	n := 1
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	buf = append(buf, cborKey_ServerCreateInviteCode_Output_code...)
	buf = cbor.AppendText(buf, s.Code)
	if s.LexiconTypeID != "" {
		buf = append(buf, cborKey_ServerCreateInviteCode_Output_dollar_type...)
		buf = cbor.AppendText(buf, s.LexiconTypeID)
	}
	return buf, nil
}

func (s *ServerCreateInviteCode_Output) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *ServerCreateInviteCode_Output) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		key, newPos, err := cbor.ReadText(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch key {
		case "code":
			s.Code, pos, err = cbor.ReadText(data, pos)
			if err != nil {
				return 0, err
			}
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
	}
	return pos, nil
}

type ServerCreateInviteCode_Output struct {
	LexiconTypeID string `json:"$type,omitempty"`
	Code          string `json:"code"`
}

// Precomputed JSON key tokens for ServerCreateInviteCode_Input.
var (
	jsonKey_ServerCreateInviteCode_Input_dollar_type = []byte("\"$type\":")
	jsonKey_ServerCreateInviteCode_Input_forAccount  = []byte("\"forAccount\":")
	jsonKey_ServerCreateInviteCode_Input_useCount    = []byte("\"useCount\":")
)

func (s *ServerCreateInviteCode_Input) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *ServerCreateInviteCode_Input) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_ServerCreateInviteCode_Input_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if s.ForAccount.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_ServerCreateInviteCode_Input_forAccount...)
		buf = cbor.AppendJSONString(buf, s.ForAccount.Val())
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_ServerCreateInviteCode_Input_useCount...)
	buf = cbor.AppendJSONInt(buf, s.UseCount)
	first = false
	buf = append(buf, '}')
	return buf, nil
}

func (s *ServerCreateInviteCode_Input) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *ServerCreateInviteCode_Input) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "forAccount":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v string
				v, pos, err = cbor.ReadJSONString(data, pos)
				if err != nil {
					return 0, err
				}
				s.ForAccount = gt.Some(v)
			}
		case "useCount":
			s.UseCount, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for ServerCreateInviteCode_Input.
var (
	cborKey_ServerCreateInviteCode_Input_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_ServerCreateInviteCode_Input_useCount    = cbor.AppendTextKey(nil, "useCount")
	cborKey_ServerCreateInviteCode_Input_forAccount  = cbor.AppendTextKey(nil, "forAccount")
)

func (s *ServerCreateInviteCode_Input) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *ServerCreateInviteCode_Input) AppendCBOR(buf []byte) ([]byte, error) {
	n := 1
	if s.LexiconTypeID != "" {
		n++
	}
	if s.ForAccount.HasVal() {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if s.LexiconTypeID != "" {
		buf = append(buf, cborKey_ServerCreateInviteCode_Input_dollar_type...)
		buf = cbor.AppendText(buf, s.LexiconTypeID)
	}
	buf = append(buf, cborKey_ServerCreateInviteCode_Input_useCount...)
	buf = cbor.AppendInt(buf, s.UseCount)
	if s.ForAccount.HasVal() {
		buf = append(buf, cborKey_ServerCreateInviteCode_Input_forAccount...)
		buf = cbor.AppendText(buf, s.ForAccount.Val())
	}
	return buf, nil
}

func (s *ServerCreateInviteCode_Input) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *ServerCreateInviteCode_Input) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		key, newPos, err := cbor.ReadText(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
			if err != nil {
				return 0, err
			}
		case "useCount":
			s.UseCount, pos, err = cbor.ReadInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "forAccount":
			if cbor.IsNull(data, pos) {
				pos++
			} else {
				var v string
				v, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
				s.ForAccount = gt.Some(v)
			}
		default:
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
	}
	return pos, nil
}

type ServerCreateInviteCode_Input struct {
	LexiconTypeID string            `json:"$type,omitempty"`
	ForAccount    gt.Option[string] `json:"forAccount,omitzero"`
	UseCount      int64             `json:"useCount"`
}

// ServerCreateInviteCode calls the XRPC procedure "com.atproto.server.createInviteCode".
//
// Create an invite code.
func ServerCreateInviteCode(ctx context.Context, c *xrpc.Client, input *ServerCreateInviteCode_Input) (*ServerCreateInviteCode_Output, error) {
	var out ServerCreateInviteCode_Output
	return &out, c.Procedure(ctx, "com.atproto.server.createInviteCode", input, &out)
}
