// Code generated by lexgen. DO NOT EDIT.

package comatproto

import (
	"context"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/atmos/xrpc"
	"github.com/jcalabro/gt"
)

// Precomputed JSON key tokens for ServerReserveSigningKey_Output.
var (
	jsonKey_ServerReserveSigningKey_Output_dollar_type = []byte("\"$type\":")
	jsonKey_ServerReserveSigningKey_Output_signingKey  = []byte("\"signingKey\":")
)

func (s *ServerReserveSigningKey_Output) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *ServerReserveSigningKey_Output) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_ServerReserveSigningKey_Output_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_ServerReserveSigningKey_Output_signingKey...)
	buf = cbor.AppendJSONString(buf, s.SigningKey)
	first = false
	buf = append(buf, '}')
	return buf, nil
}

func (s *ServerReserveSigningKey_Output) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *ServerReserveSigningKey_Output) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "signingKey":
			s.SigningKey, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for ServerReserveSigningKey_Output.
var (
	cborKey_ServerReserveSigningKey_Output_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_ServerReserveSigningKey_Output_signingKey  = cbor.AppendTextKey(nil, "signingKey")
)

func (s *ServerReserveSigningKey_Output) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *ServerReserveSigningKey_Output) AppendCBOR(buf []byte) ([]byte, error) {
	n := 1
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if s.LexiconTypeID != "" {
		buf = append(buf, cborKey_ServerReserveSigningKey_Output_dollar_type...)
		buf = cbor.AppendText(buf, s.LexiconTypeID)
	}
	buf = append(buf, cborKey_ServerReserveSigningKey_Output_signingKey...)
	buf = cbor.AppendText(buf, s.SigningKey)
	return buf, nil
}

func (s *ServerReserveSigningKey_Output) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *ServerReserveSigningKey_Output) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case 10:
			if string(data[keyStart:keyEnd]) == "signingKey" {
				s.SigningKey, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
			}
		default:
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
	}
	return pos, nil
}

type ServerReserveSigningKey_Output struct {
	LexiconTypeID string `json:"$type,omitempty"`
	SigningKey    string `json:"signingKey"` // The public key for the reserved signing key, in did:key serialization.
}

// Precomputed JSON key tokens for ServerReserveSigningKey_Input.
var (
	jsonKey_ServerReserveSigningKey_Input_dollar_type = []byte("\"$type\":")
	jsonKey_ServerReserveSigningKey_Input_did         = []byte("\"did\":")
)

func (s *ServerReserveSigningKey_Input) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *ServerReserveSigningKey_Input) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_ServerReserveSigningKey_Input_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if s.DID.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_ServerReserveSigningKey_Input_did...)
		buf = cbor.AppendJSONString(buf, s.DID.Val())
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *ServerReserveSigningKey_Input) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *ServerReserveSigningKey_Input) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "did":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v string
				v, pos, err = cbor.ReadJSONString(data, pos)
				if err != nil {
					return 0, err
				}
				s.DID = gt.Some(v)
			}
		default:
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for ServerReserveSigningKey_Input.
var (
	cborKey_ServerReserveSigningKey_Input_did         = cbor.AppendTextKey(nil, "did")
	cborKey_ServerReserveSigningKey_Input_dollar_type = cbor.AppendTextKey(nil, "$type")
)

func (s *ServerReserveSigningKey_Input) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *ServerReserveSigningKey_Input) AppendCBOR(buf []byte) ([]byte, error) {
	n := 0
	if s.DID.HasVal() {
		n++
	}
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if s.DID.HasVal() {
		buf = append(buf, cborKey_ServerReserveSigningKey_Input_did...)
		buf = cbor.AppendText(buf, s.DID.Val())
	}
	if s.LexiconTypeID != "" {
		buf = append(buf, cborKey_ServerReserveSigningKey_Input_dollar_type...)
		buf = cbor.AppendText(buf, s.LexiconTypeID)
	}
	return buf, nil
}

func (s *ServerReserveSigningKey_Input) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *ServerReserveSigningKey_Input) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 3:
			if string(data[keyStart:keyEnd]) == "did" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v string
					v, pos, err = cbor.ReadText(data, pos)
					if err != nil {
						return 0, err
					}
					s.DID = gt.Some(v)
				}
			} else {
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
			}
		default:
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
	}
	return pos, nil
}

type ServerReserveSigningKey_Input struct {
	LexiconTypeID string            `json:"$type,omitempty"`
	DID           gt.Option[string] `json:"did,omitzero"` // The DID to reserve a key for.
}

// ServerReserveSigningKey calls the XRPC procedure "com.atproto.server.reserveSigningKey".
//
// Reserve a repo signing key, for use with account creation. Necessary so that a DID PLC update operation can be constructed during an account migraiton. Public and does not require auth; implemented by PDS. NOTE: this endpoint may change when full account migration is implemented.
func ServerReserveSigningKey(ctx context.Context, c *xrpc.Client, input *ServerReserveSigningKey_Input) (*ServerReserveSigningKey_Output, error) {
	var out ServerReserveSigningKey_Output
	return &out, c.Procedure(ctx, "com.atproto.server.reserveSigningKey", input, &out)
}
