// Code generated by lexgen. DO NOT EDIT.

package comatproto

import (
	"context"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/atmos/xrpc"
)

// Precomputed JSON key tokens for ServerRevokeAppPassword_Input.
var (
	jsonKey_ServerRevokeAppPassword_Input_dollar_type = []byte("\"$type\":")
	jsonKey_ServerRevokeAppPassword_Input_name        = []byte("\"name\":")
)

func (s *ServerRevokeAppPassword_Input) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *ServerRevokeAppPassword_Input) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_ServerRevokeAppPassword_Input_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_ServerRevokeAppPassword_Input_name...)
	buf = cbor.AppendJSONString(buf, s.Name)
	first = false
	buf = append(buf, '}')
	return buf, nil
}

func (s *ServerRevokeAppPassword_Input) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *ServerRevokeAppPassword_Input) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "name":
			s.Name, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for ServerRevokeAppPassword_Input.
var (
	cborKey_ServerRevokeAppPassword_Input_name        = cbor.AppendTextKey(nil, "name")
	cborKey_ServerRevokeAppPassword_Input_dollar_type = cbor.AppendTextKey(nil, "$type")
)

func (s *ServerRevokeAppPassword_Input) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *ServerRevokeAppPassword_Input) AppendCBOR(buf []byte) ([]byte, error) {
	n := 1
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	buf = append(buf, cborKey_ServerRevokeAppPassword_Input_name...)
	buf = cbor.AppendText(buf, s.Name)
	if s.LexiconTypeID != "" {
		buf = append(buf, cborKey_ServerRevokeAppPassword_Input_dollar_type...)
		buf = cbor.AppendText(buf, s.LexiconTypeID)
	}
	return buf, nil
}

func (s *ServerRevokeAppPassword_Input) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *ServerRevokeAppPassword_Input) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 4:
			if string(data[keyStart:keyEnd]) == "name" {
				s.Name, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
			}
		default:
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
	}
	return pos, nil
}

type ServerRevokeAppPassword_Input struct {
	LexiconTypeID string `json:"$type,omitempty"`
	Name          string `json:"name"`
}

// ServerRevokeAppPassword calls the XRPC procedure "com.atproto.server.revokeAppPassword".
//
// Revoke an App Password by name.
func ServerRevokeAppPassword(ctx context.Context, c *xrpc.Client, input *ServerRevokeAppPassword_Input) error {
	return c.Procedure(ctx, "com.atproto.server.revokeAppPassword", input, nil)
}
