// Code generated by lexgen. DO NOT EDIT.

package comatproto

import (
	"context"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/atmos/xrpc"
)

// Error name constants for SimplespacePutMember.
const (
	ErrSimplespacePutMember_SpaceNotFound = "SpaceNotFound"
	ErrSimplespacePutMember_NotSpaceOwner = "NotSpaceOwner"
)

// Precomputed JSON key tokens for SimplespacePutMember_Input.
var (
	jsonKey_SimplespacePutMember_Input_dollar_type = []byte("\"$type\":")
	jsonKey_SimplespacePutMember_Input_did         = []byte("\"did\":")
	jsonKey_SimplespacePutMember_Input_read        = []byte("\"read\":")
	jsonKey_SimplespacePutMember_Input_space       = []byte("\"space\":")
	jsonKey_SimplespacePutMember_Input_write       = []byte("\"write\":")
)

func (s *SimplespacePutMember_Input) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *SimplespacePutMember_Input) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_SimplespacePutMember_Input_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_SimplespacePutMember_Input_did...)
	buf = cbor.AppendJSONString(buf, s.DID)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_SimplespacePutMember_Input_read...)
	buf = cbor.AppendJSONBool(buf, s.Read)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_SimplespacePutMember_Input_space...)
	buf = cbor.AppendJSONString(buf, s.Space)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_SimplespacePutMember_Input_write...)
	buf = cbor.AppendJSONBool(buf, s.Write)
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *SimplespacePutMember_Input) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *SimplespacePutMember_Input) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "did":
			s.DID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "read":
			s.Read, pos, err = cbor.ReadJSONBool(data, pos)
			if err != nil {
				return 0, err
			}
		case "space":
			s.Space, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "write":
			s.Write, pos, err = cbor.ReadJSONBool(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for SimplespacePutMember_Input.
var (
	cborKey_SimplespacePutMember_Input_did         = cbor.AppendTextKey(nil, "did")
	cborKey_SimplespacePutMember_Input_read        = cbor.AppendTextKey(nil, "read")
	cborKey_SimplespacePutMember_Input_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_SimplespacePutMember_Input_space       = cbor.AppendTextKey(nil, "space")
	cborKey_SimplespacePutMember_Input_write       = cbor.AppendTextKey(nil, "write")
)

func (s *SimplespacePutMember_Input) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *SimplespacePutMember_Input) AppendCBOR(buf []byte) ([]byte, error) {
	n := 4 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "did", buf)
		buf = append(buf, cborKey_SimplespacePutMember_Input_did...)
		buf = cbor.AppendText(buf, s.DID)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "read", buf)
		buf = append(buf, cborKey_SimplespacePutMember_Input_read...)
		buf = cbor.AppendBool(buf, s.Read)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_SimplespacePutMember_Input_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "space", buf)
		buf = append(buf, cborKey_SimplespacePutMember_Input_space...)
		buf = cbor.AppendText(buf, s.Space)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "write", buf)
		buf = append(buf, cborKey_SimplespacePutMember_Input_write...)
		buf = cbor.AppendBool(buf, s.Write)
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		buf = append(buf, cborKey_SimplespacePutMember_Input_did...)
		buf = cbor.AppendText(buf, s.DID)
		buf = append(buf, cborKey_SimplespacePutMember_Input_read...)
		buf = cbor.AppendBool(buf, s.Read)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_SimplespacePutMember_Input_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		buf = append(buf, cborKey_SimplespacePutMember_Input_space...)
		buf = cbor.AppendText(buf, s.Space)
		buf = append(buf, cborKey_SimplespacePutMember_Input_write...)
		buf = cbor.AppendBool(buf, s.Write)
	}
	return buf, nil
}

func (s *SimplespacePutMember_Input) UnmarshalCBOR(data []byte) error {
	pos, err := s.UnmarshalCBORAt(data, 0)
	if err != nil {
		return err
	}
	return cbor.CheckTrailingData(pos, len(data))
}

func (s *SimplespacePutMember_Input) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	var prevKeyStart, prevKeyEnd int
	keyOrderValid := false
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		if keyOrderValid {
			if err := cbor.CheckMapKeyOrder(data, prevKeyStart, prevKeyEnd, keyStart, keyEnd); err != nil {
				return 0, err
			}
		}
		prevKeyStart, prevKeyEnd = keyStart, keyEnd
		keyOrderValid = true
		pos = newPos
		switch keyEnd - keyStart {
		case 3:
			if string(data[keyStart:keyEnd]) == "did" {
				s.DID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 4:
			if string(data[keyStart:keyEnd]) == "read" {
				s.Read, pos, err = cbor.ReadBool(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "space" {
				s.Space, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "write" {
				s.Write, pos, err = cbor.ReadBool(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

type SimplespacePutMember_Input struct {
	LexiconTypeID string `json:"$type,omitempty"`
	DID           string `json:"did"`   // The DID of the member.
	Read          bool   `json:"read"`  // Whether the member may read under a member-list read policy.
	Space         string `json:"space"` // Reference to the space.
	Write         bool   `json:"write"` // Whether the member's writes are tracked under a member-list write policy.

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// SimplespacePutMember calls the XRPC procedure "com.atproto.simplespace.putMember".
//
// Add a member to a space's host-internal member list or replace their read and write access. Requires auth as the space owner.
func SimplespacePutMember(ctx context.Context, c *xrpc.Client, input *SimplespacePutMember_Input) error {
	return c.Procedure(ctx, "com.atproto.simplespace.putMember", input, nil)
}
