// Code generated by lexgen. DO NOT EDIT.

package comatproto

import (
	"context"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/atmos/xrpc"
)

// Error name constants for SpaceUnregisterNotify.
const (
	ErrSpaceUnregisterNotify_SpaceNotFound = "SpaceNotFound"
)

// Precomputed JSON key tokens for SpaceUnregisterNotify_Input.
var (
	jsonKey_SpaceUnregisterNotify_Input_dollar_type = []byte("\"$type\":")
	jsonKey_SpaceUnregisterNotify_Input_service     = []byte("\"service\":")
	jsonKey_SpaceUnregisterNotify_Input_space       = []byte("\"space\":")
)

func (s *SpaceUnregisterNotify_Input) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *SpaceUnregisterNotify_Input) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_SpaceUnregisterNotify_Input_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_SpaceUnregisterNotify_Input_service...)
	buf = cbor.AppendJSONString(buf, s.Service)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_SpaceUnregisterNotify_Input_space...)
	buf = cbor.AppendJSONString(buf, s.Space)
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *SpaceUnregisterNotify_Input) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *SpaceUnregisterNotify_Input) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "service":
			s.Service, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "space":
			s.Space, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for SpaceUnregisterNotify_Input.
var (
	cborKey_SpaceUnregisterNotify_Input_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_SpaceUnregisterNotify_Input_space       = cbor.AppendTextKey(nil, "space")
	cborKey_SpaceUnregisterNotify_Input_service     = cbor.AppendTextKey(nil, "service")
)

func (s *SpaceUnregisterNotify_Input) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *SpaceUnregisterNotify_Input) AppendCBOR(buf []byte) ([]byte, error) {
	n := 2 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_SpaceUnregisterNotify_Input_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "space", buf)
		buf = append(buf, cborKey_SpaceUnregisterNotify_Input_space...)
		buf = cbor.AppendText(buf, s.Space)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "service", buf)
		buf = append(buf, cborKey_SpaceUnregisterNotify_Input_service...)
		buf = cbor.AppendText(buf, s.Service)
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_SpaceUnregisterNotify_Input_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		buf = append(buf, cborKey_SpaceUnregisterNotify_Input_space...)
		buf = cbor.AppendText(buf, s.Space)
		buf = append(buf, cborKey_SpaceUnregisterNotify_Input_service...)
		buf = cbor.AppendText(buf, s.Service)
	}
	return buf, nil
}

func (s *SpaceUnregisterNotify_Input) UnmarshalCBOR(data []byte) error {
	pos, err := s.UnmarshalCBORAt(data, 0)
	if err != nil {
		return err
	}
	return cbor.CheckTrailingData(pos, len(data))
}

func (s *SpaceUnregisterNotify_Input) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	var prevKeyStart, prevKeyEnd int
	keyOrderValid := false
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		if keyOrderValid {
			if err := cbor.CheckMapKeyOrder(data, prevKeyStart, prevKeyEnd, keyStart, keyEnd); err != nil {
				return 0, err
			}
		}
		prevKeyStart, prevKeyEnd = keyStart, keyEnd
		keyOrderValid = true
		pos = newPos
		switch keyEnd - keyStart {
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "space" {
				s.Space, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 7:
			if string(data[keyStart:keyEnd]) == "service" {
				s.Service, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

type SpaceUnregisterNotify_Input struct {
	LexiconTypeID string `json:"$type,omitempty"`
	Service       string `json:"service"` // Service identifier of the subscriber to remove, as passed to registerNotify.
	Space         string `json:"space"`   // Reference to the space.

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// SpaceUnregisterNotify calls the XRPC procedure "com.atproto.space.unregisterNotify".
//
// Withdraw a write-notification registration made through registerNotify. Called on the space host. Idempotent: succeeds whether or not a matching registration existed. Registrations also lapse on their own at the expiry returned by registerNotify, so this is for explicit withdrawal rather than cleanup. Authenticated with a space credential.
func SpaceUnregisterNotify(ctx context.Context, c *xrpc.Client, input *SpaceUnregisterNotify_Input) error {
	return c.Procedure(ctx, "com.atproto.space.unregisterNotify", input, nil)
}
