// Code generated by lexgen. DO NOT EDIT.

package comatproto

import (
	"context"
	"encoding/json"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/atmos/xrpc"
	"github.com/jcalabro/gt"
)

// Error name constants for SpaceListRecords.
const (
	ErrSpaceListRecords_SpaceNotFound   = "SpaceNotFound"
	ErrSpaceListRecords_RepoNotFound    = "RepoNotFound"
	ErrSpaceListRecords_RepoTakendown   = "RepoTakendown"
	ErrSpaceListRecords_RepoSuspended   = "RepoSuspended"
	ErrSpaceListRecords_RepoDeactivated = "RepoDeactivated"
)

// Precomputed JSON key tokens for SpaceListRecords_Output.
var (
	jsonKey_SpaceListRecords_Output_dollar_type = []byte("\"$type\":")
	jsonKey_SpaceListRecords_Output_cursor      = []byte("\"cursor\":")
	jsonKey_SpaceListRecords_Output_records     = []byte("\"records\":")
)

func (s *SpaceListRecords_Output) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *SpaceListRecords_Output) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_SpaceListRecords_Output_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if s.Cursor.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_SpaceListRecords_Output_cursor...)
		buf = cbor.AppendJSONString(buf, s.Cursor.Val())
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_SpaceListRecords_Output_records...)
	buf = append(buf, '[')
	for i, item := range s.Records {
		if i > 0 {
			buf = append(buf, ',')
		}
		var err error
		buf, err = item.AppendJSON(buf)
		if err != nil {
			return nil, err
		}
	}
	buf = append(buf, ']')
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *SpaceListRecords_Output) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *SpaceListRecords_Output) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "cursor":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v string
				v, pos, err = cbor.ReadJSONString(data, pos)
				if err != nil {
					return 0, err
				}
				s.Cursor = gt.Some(v)
			}
		case "records":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.Records = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem SpaceListRecords_Record
					pos, err = elem.UnmarshalJSONAt(data, pos)
					if err != nil {
						return 0, err
					}
					s.Records = append(s.Records, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for SpaceListRecords_Output.
var (
	cborKey_SpaceListRecords_Output_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_SpaceListRecords_Output_cursor      = cbor.AppendTextKey(nil, "cursor")
	cborKey_SpaceListRecords_Output_records     = cbor.AppendTextKey(nil, "records")
)

func (s *SpaceListRecords_Output) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *SpaceListRecords_Output) AppendCBOR(buf []byte) ([]byte, error) {
	n := 1 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	if s.Cursor.HasVal() {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_SpaceListRecords_Output_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "cursor", buf)
		if s.Cursor.HasVal() {
			buf = append(buf, cborKey_SpaceListRecords_Output_cursor...)
			buf = cbor.AppendText(buf, s.Cursor.Val())
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "records", buf)
		buf = append(buf, cborKey_SpaceListRecords_Output_records...)
		buf = cbor.AppendArrayHeader(buf, uint64(len(s.Records)))
		for _, item := range s.Records {
			var err error
			buf, err = item.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_SpaceListRecords_Output_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		if s.Cursor.HasVal() {
			buf = append(buf, cborKey_SpaceListRecords_Output_cursor...)
			buf = cbor.AppendText(buf, s.Cursor.Val())
		}
		buf = append(buf, cborKey_SpaceListRecords_Output_records...)
		buf = cbor.AppendArrayHeader(buf, uint64(len(s.Records)))
		for _, item := range s.Records {
			var err error
			buf, err = item.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
	}
	return buf, nil
}

func (s *SpaceListRecords_Output) UnmarshalCBOR(data []byte) error {
	pos, err := s.UnmarshalCBORAt(data, 0)
	if err != nil {
		return err
	}
	return cbor.CheckTrailingData(pos, len(data))
}

func (s *SpaceListRecords_Output) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	var prevKeyStart, prevKeyEnd int
	keyOrderValid := false
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		if keyOrderValid {
			if err := cbor.CheckMapKeyOrder(data, prevKeyStart, prevKeyEnd, keyStart, keyEnd); err != nil {
				return 0, err
			}
		}
		prevKeyStart, prevKeyEnd = keyStart, keyEnd
		keyOrderValid = true
		pos = newPos
		switch keyEnd - keyStart {
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 6:
			if string(data[keyStart:keyEnd]) == "cursor" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v string
					v, pos, err = cbor.ReadText(data, pos)
					if err != nil {
						return 0, err
					}
					s.Cursor = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 7:
			if string(data[keyStart:keyEnd]) == "records" {
				{
					arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
					if err != nil {
						return 0, err
					}
					if err := cbor.CheckArrayLen(arrLen, data, newPos); err != nil {
						return 0, err
					}
					pos = newPos
					s.Records = make([]SpaceListRecords_Record, arrLen)
					for idx := range arrLen {
						pos, err = s.Records[idx].UnmarshalCBORAt(data, pos)
						if err != nil {
							return 0, err
						}
					}
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

type SpaceListRecords_Output struct {
	LexiconTypeID string                    `json:"$type,omitempty"`
	Cursor        gt.Option[string]         `json:"cursor,omitzero"`
	Records       []SpaceListRecords_Record `json:"records"`

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// SpaceListRecords calls the XRPC query "com.atproto.space.listRecords".
//
// List the records in an account's repo within a permissioned space, optionally filtered by collection. By default each record's value is inlined; set excludeValues for a metadata-only listing (collection, rkey, cid). Used for full-state recovery. Callable with either OAuth (for the authenticated user's own data) or a space credential (for syncing services). Throws RepoNotFound when the account holds no repo in the space; this does not distinguish a member that has never written from a non-member.
func SpaceListRecords(ctx context.Context, c *xrpc.Client, collection string, cursor string, excludeValues bool, limit int64, repo string, reverse bool, space string) (*SpaceListRecords_Output, error) {
	params := map[string]any{}
	if collection != "" {
		params["collection"] = collection
	}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if excludeValues {
		params["excludeValues"] = excludeValues
	}
	if limit != 0 {
		params["limit"] = limit
	}
	params["repo"] = repo
	if reverse {
		params["reverse"] = reverse
	}
	params["space"] = space
	var out SpaceListRecords_Output
	return &out, c.Query(ctx, "com.atproto.space.listRecords", params, &out)
}

// SpaceListRecords_Record is a "record" in the com.atproto.space.listRecords schema.
type SpaceListRecords_Record struct {
	LexiconTypeID string          `json:"$type,omitempty"`
	CID           string          `json:"cid"`
	Collection    string          `json:"collection"`
	Rkey          string          `json:"rkey"`
	Value         json.RawMessage `json:"value,omitempty"` // The record's value. Inlined by default; omitted when excludeValues is set.

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// Precomputed CBOR key tokens for SpaceListRecords_Record.
var (
	cborKey_SpaceListRecords_Record_cid         = cbor.AppendTextKey(nil, "cid")
	cborKey_SpaceListRecords_Record_rkey        = cbor.AppendTextKey(nil, "rkey")
	cborKey_SpaceListRecords_Record_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_SpaceListRecords_Record_value       = cbor.AppendTextKey(nil, "value")
	cborKey_SpaceListRecords_Record_collection  = cbor.AppendTextKey(nil, "collection")
)

func (s *SpaceListRecords_Record) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *SpaceListRecords_Record) AppendCBOR(buf []byte) ([]byte, error) {
	n := 3 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	if s.Value != nil {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "cid", buf)
		buf = append(buf, cborKey_SpaceListRecords_Record_cid...)
		buf = cbor.AppendText(buf, s.CID)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "rkey", buf)
		buf = append(buf, cborKey_SpaceListRecords_Record_rkey...)
		buf = cbor.AppendText(buf, s.Rkey)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_SpaceListRecords_Record_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "value", buf)
		if s.Value != nil {
			buf = append(buf, cborKey_SpaceListRecords_Record_value...)
			buf = cbor.AppendNull(buf)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "collection", buf)
		buf = append(buf, cborKey_SpaceListRecords_Record_collection...)
		buf = cbor.AppendText(buf, s.Collection)
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		buf = append(buf, cborKey_SpaceListRecords_Record_cid...)
		buf = cbor.AppendText(buf, s.CID)
		buf = append(buf, cborKey_SpaceListRecords_Record_rkey...)
		buf = cbor.AppendText(buf, s.Rkey)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_SpaceListRecords_Record_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		if s.Value != nil {
			buf = append(buf, cborKey_SpaceListRecords_Record_value...)
			buf = cbor.AppendNull(buf)
		}
		buf = append(buf, cborKey_SpaceListRecords_Record_collection...)
		buf = cbor.AppendText(buf, s.Collection)
	}
	return buf, nil
}

func (s *SpaceListRecords_Record) UnmarshalCBOR(data []byte) error {
	pos, err := s.UnmarshalCBORAt(data, 0)
	if err != nil {
		return err
	}
	return cbor.CheckTrailingData(pos, len(data))
}

func (s *SpaceListRecords_Record) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	var prevKeyStart, prevKeyEnd int
	keyOrderValid := false
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		if keyOrderValid {
			if err := cbor.CheckMapKeyOrder(data, prevKeyStart, prevKeyEnd, keyStart, keyEnd); err != nil {
				return 0, err
			}
		}
		prevKeyStart, prevKeyEnd = keyStart, keyEnd
		keyOrderValid = true
		pos = newPos
		switch keyEnd - keyStart {
		case 3:
			if string(data[keyStart:keyEnd]) == "cid" {
				s.CID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 4:
			if string(data[keyStart:keyEnd]) == "rkey" {
				s.Rkey, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "value" {
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 10:
			if string(data[keyStart:keyEnd]) == "collection" {
				s.Collection, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

// Precomputed JSON key tokens for SpaceListRecords_Record.
var (
	jsonKey_SpaceListRecords_Record_dollar_type = []byte("\"$type\":")
	jsonKey_SpaceListRecords_Record_cid         = []byte("\"cid\":")
	jsonKey_SpaceListRecords_Record_collection  = []byte("\"collection\":")
	jsonKey_SpaceListRecords_Record_rkey        = []byte("\"rkey\":")
	jsonKey_SpaceListRecords_Record_value       = []byte("\"value\":")
)

func (s *SpaceListRecords_Record) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *SpaceListRecords_Record) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_SpaceListRecords_Record_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_SpaceListRecords_Record_cid...)
	buf = cbor.AppendJSONString(buf, s.CID)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_SpaceListRecords_Record_collection...)
	buf = cbor.AppendJSONString(buf, s.Collection)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_SpaceListRecords_Record_rkey...)
	buf = cbor.AppendJSONString(buf, s.Rkey)
	first = false
	if s.Value != nil {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_SpaceListRecords_Record_value...)
		buf = append(buf, s.Value...)
		first = false
	}
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *SpaceListRecords_Record) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *SpaceListRecords_Record) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "cid":
			s.CID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "collection":
			s.Collection, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "rkey":
			s.Rkey, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "value":
			{
				start := pos
				pos, err = cbor.SkipJSONValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.Value = json.RawMessage(data[start:pos])
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}
