// Code generated by lexgen. DO NOT EDIT.

package comatproto

import (
	"context"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/atmos/xrpc"
	"github.com/jcalabro/gt"
)

// Error name constants for SyncListBlobs.
const (
	ErrSyncListBlobs_RepoNotFound    = "RepoNotFound"
	ErrSyncListBlobs_RepoTakendown   = "RepoTakendown"
	ErrSyncListBlobs_RepoSuspended   = "RepoSuspended"
	ErrSyncListBlobs_RepoDeactivated = "RepoDeactivated"
)

// Precomputed JSON key tokens for SyncListBlobs_Output.
var (
	jsonKey_SyncListBlobs_Output_dollar_type = []byte("\"$type\":")
	jsonKey_SyncListBlobs_Output_cids        = []byte("\"cids\":")
	jsonKey_SyncListBlobs_Output_cursor      = []byte("\"cursor\":")
)

func (s *SyncListBlobs_Output) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *SyncListBlobs_Output) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_SyncListBlobs_Output_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_SyncListBlobs_Output_cids...)
	buf = append(buf, '[')
	for i, item := range s.Cids {
		if i > 0 {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, item)
	}
	buf = append(buf, ']')
	first = false
	if s.Cursor.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_SyncListBlobs_Output_cursor...)
		buf = cbor.AppendJSONString(buf, s.Cursor.Val())
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *SyncListBlobs_Output) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *SyncListBlobs_Output) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "cids":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.Cids = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem string
					elem, pos, err = cbor.ReadJSONString(data, pos)
					if err != nil {
						return 0, err
					}
					s.Cids = append(s.Cids, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case "cursor":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v string
				v, pos, err = cbor.ReadJSONString(data, pos)
				if err != nil {
					return 0, err
				}
				s.Cursor = gt.Some(v)
			}
		default:
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for SyncListBlobs_Output.
var (
	cborKey_SyncListBlobs_Output_cids        = cbor.AppendTextKey(nil, "cids")
	cborKey_SyncListBlobs_Output_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_SyncListBlobs_Output_cursor      = cbor.AppendTextKey(nil, "cursor")
)

func (s *SyncListBlobs_Output) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *SyncListBlobs_Output) AppendCBOR(buf []byte) ([]byte, error) {
	n := 1
	if s.LexiconTypeID != "" {
		n++
	}
	if s.Cursor.HasVal() {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	buf = append(buf, cborKey_SyncListBlobs_Output_cids...)
	buf = cbor.AppendArrayHeader(buf, uint64(len(s.Cids)))
	for _, item := range s.Cids {
		buf = cbor.AppendText(buf, item)
	}
	if s.LexiconTypeID != "" {
		buf = append(buf, cborKey_SyncListBlobs_Output_dollar_type...)
		buf = cbor.AppendText(buf, s.LexiconTypeID)
	}
	if s.Cursor.HasVal() {
		buf = append(buf, cborKey_SyncListBlobs_Output_cursor...)
		buf = cbor.AppendText(buf, s.Cursor.Val())
	}
	return buf, nil
}

func (s *SyncListBlobs_Output) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *SyncListBlobs_Output) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 4:
			if string(data[keyStart:keyEnd]) == "cids" {
				{
					arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
					if err != nil {
						return 0, err
					}
					pos = newPos
					s.Cids = make([]string, arrLen)
					for idx := range arrLen {
						s.Cids[idx], pos, err = cbor.ReadText(data, pos)
						if err != nil {
							return 0, err
						}
					}
				}
			} else {
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case 6:
			if string(data[keyStart:keyEnd]) == "cursor" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v string
					v, pos, err = cbor.ReadText(data, pos)
					if err != nil {
						return 0, err
					}
					s.Cursor = gt.Some(v)
				}
			} else {
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
			}
		default:
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
		}
	}
	return pos, nil
}

type SyncListBlobs_Output struct {
	LexiconTypeID string            `json:"$type,omitempty"`
	Cids          []string          `json:"cids"`
	Cursor        gt.Option[string] `json:"cursor,omitzero"`
}

// SyncListBlobs calls the XRPC query "com.atproto.sync.listBlobs".
//
// List blob CIDs for an account, since some repo revision. Does not require auth; implemented by PDS.
func SyncListBlobs(ctx context.Context, c *xrpc.Client, cursor string, did string, limit int64, since string) (*SyncListBlobs_Output, error) {
	params := map[string]any{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	params["did"] = did
	if limit != 0 {
		params["limit"] = limit
	}
	if since != "" {
		params["since"] = since
	}
	var out SyncListBlobs_Output
	return &out, c.Query(ctx, "com.atproto.sync.listBlobs", params, &out)
}
