// Code generated by lexgen. DO NOT EDIT.

package comatproto

import (
	"context"
	lextypes "github.com/jcalabro/atmos/api/lextypes"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/atmos/xrpc"
)

// Precomputed JSON key tokens for TempRevokeAccountCredentials_Input.
var (
	jsonKey_TempRevokeAccountCredentials_Input_dollar_type = []byte("\"$type\":")
	jsonKey_TempRevokeAccountCredentials_Input_account     = []byte("\"account\":")
)

func (s *TempRevokeAccountCredentials_Input) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *TempRevokeAccountCredentials_Input) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_TempRevokeAccountCredentials_Input_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_TempRevokeAccountCredentials_Input_account...)
	buf = cbor.AppendJSONString(buf, s.Account)
	first = false
	for _, ef := range s.extraJSON {
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *TempRevokeAccountCredentials_Input) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *TempRevokeAccountCredentials_Input) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extraJSON = nil
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "account":
			s.Account, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extraJSON = append(s.extraJSON, lextypes.ExtraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...)})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for TempRevokeAccountCredentials_Input.
var (
	cborKey_TempRevokeAccountCredentials_Input_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_TempRevokeAccountCredentials_Input_account     = cbor.AppendTextKey(nil, "account")
)

func (s *TempRevokeAccountCredentials_Input) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *TempRevokeAccountCredentials_Input) AppendCBOR(buf []byte) ([]byte, error) {
	n := 1 + len(s.extraCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extraCBOR) > 0 {
		ei := 0
		ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_TempRevokeAccountCredentials_Input_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "account", buf)
		buf = append(buf, cborKey_TempRevokeAccountCredentials_Input_account...)
		buf = cbor.AppendText(buf, s.Account)
		_, buf = lextypes.AppendCBORExtrasBefore(s.extraCBOR, ei, "", buf)
	} else {
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_TempRevokeAccountCredentials_Input_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		buf = append(buf, cborKey_TempRevokeAccountCredentials_Input_account...)
		buf = cbor.AppendText(buf, s.Account)
	}
	return buf, nil
}

func (s *TempRevokeAccountCredentials_Input) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *TempRevokeAccountCredentials_Input) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extraCBOR = nil
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
			}
		case 7:
			if string(data[keyStart:keyEnd]) == "account" {
				s.Account, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extraCBOR = append(s.extraCBOR, lextypes.ExtraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...)})
		}
	}
	return pos, nil
}

type TempRevokeAccountCredentials_Input struct {
	LexiconTypeID string `json:"$type,omitempty"`
	Account       string `json:"account"`

	// extraJSON and extraCBOR preserve unknown fields for same-format round-trips.
	extraJSON []lextypes.ExtraField
	extraCBOR []lextypes.ExtraField
}

// TempRevokeAccountCredentials calls the XRPC procedure "com.atproto.temp.revokeAccountCredentials".
//
// Revoke sessions, password, and app passwords associated with account. May be resolved by a password reset.
func TempRevokeAccountCredentials(ctx context.Context, c *xrpc.Client, input *TempRevokeAccountCredentials_Input) error {
	return c.Procedure(ctx, "com.atproto.temp.revokeAccountCredentials", input, nil)
}
